### ISSUE TITLE
./autogen.sh --- system failed with error

### ISSUE THREAD

**Issue by chandrureddy** [kimchi-project/ginger#10]
1. Down loaded the source code from https://github.com/kimchi-project/ginger using "Download ZIP".
2. Extracted the zip file
3. Run autogen.sh failed with the following
[chandra@localhost ginger-master]$ ./autogen.sh --system
configure.ac:41: installing 'build-aux/compile'
configure.ac:41: installing 'build-aux/config.guess'
configure.ac:41: installing 'build-aux/config.sub'
configure.ac:35: installing 'build-aux/install-sh'
configure.ac:35: installing 'build-aux/missing'
Makefile.am:29: installing 'build-aux/py-compile'
configure: loading site script /usr/share/config.site
configure: error: package version not defined

Machine Details: Fedora 21
$ uname -a
Linux localhost.localdomain 3.18.3-201.fc21.x86_64 #1 SMP Mon Jan 19 15:59:31 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

But when I tried download source code using git command "git clone https://github.com/kimchi-project/ginger" instead "Download ZIP", autogen.sh went fine with out any issues. Now I am able to install ginger successfully. 

So was there a difference in git vs "Download ZIP" content ?

Thanks in advance,
Chandra

**Comment by danielhb** [comment]
This issue was fixed in the lastest Ginger release 1.3.0.1

Thanks!
