### ISSUE TITLE
failed to comply with json shcema for dasd device

### ISSUE THREAD

**Issue by sureshab** [kimchi-project/ginger#100]
When executed GET operation on unformatted dasd device, size attribute is missing.
API doc doesn't say its an optional attribute.
[root@zfwcec103 gingers390x]# curl -k -u root -H "Content-Type: application/json" -H "Accept: application/json" -X GET 'https://127.0.0.1:8001/plugins/ginger/dasddevs/0.0.0201'
Enter host password for user 'root':
{
  "status":"n/f",
  "blocks":"None",
  "name":"dasdc",
  "uid":"IBM.750000000DX111.0001.2a",
  "readonly":"0",
  "erplog":"0",
  "use_diag":"0",
  "bus-id":"0.0.0201",
  "device":"948",
  "blksz":"None",
  "type":"ECKD",
  "eer_enabled":"0"
}

Also from API doc, it appears that "active" and "n/f" are also the json keys. But its the value of "status" key. 
![screenshot from 2015-12-30 18 38 20](https://cloud.githubusercontent.com/assets/12499230/12051107/b30568f6-af24-11e5-93ee-bc01038b61f3.png)

It could be changed to 
* status: Status of the DASD device. "active" if dasd device is in active state, "n/f" if dasd device is in unformatted state

**Comment by sureshab** [comment]
we can assign "Unknown" to "size" in case of unformatted dasd

**Comment by harche** [comment]
I will be working on this issue

**Comment by danielhb** [comment]
Closing. Thanks
