### ISSUE TITLE
GET /plugins/ginger/dasdpartitions/dasdi fails with 500

### ISSUE THREAD

**Issue by sureshab** [kimchi-project/ginger#101]
[root@zfwcec103 ~]# curl -k -u root -H "Content-Type: application/json" -H "Accept: application/json" -X GET 'https://127.0.0.1:8001/plugins/ginger/dasdpartitions/dasdi'
Enter host password for user 'root':
{
  "reason":"GINDASDPAR0002E: Error while getting block device information",
  "code":"500 Internal Server Error"
}

**Comment by pkulkark** [comment]
I will be working on this issue

**Comment by danielhb** [comment]
Fixed by c653c0d
