### ISSUE TITLE
Create partition fails with 500

### ISSUE THREAD

**Issue by sureshab** [kimchi-project/ginger#102]
[root@zfwcec103 ~]# curl -k -u root -H "Content-Type: application/json" -H "Accept: application/json" -X POST -d '{"dev_name":"dasda", "size":20}' 'https://127.0.0.1:8001/plugins/ginger/dasdpartitions'
{
  "reason":"The server encountered an unexpected condition which prevented it from fulfilling the request.",
  "code":"500 Internal Server Error"
} 

log captured:

[31/Dec/2015:09:14:26] HTTP Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cherrypy/_cprequest.py", line 656, in respond
    response.body = self.handler()
  File "/usr/lib/python2.7/site-packages/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/cherrypy/_cpdispatch.py", line 34, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/lib/python2.7/site-packages/wok/control/base.py", line 353, in index
    return self.create(parse_request(), *args)
  File "/usr/lib/python2.7/site-packages/wok/control/base.py", line 285, in create
    name = create(*args)
  File "/usr/lib/python2.7/site-packages/wok/plugins/ginger/models/dasdpartitions.py", line 50, in create
    dasd_utils._create_dasd_part(dev_name, size)
  File "/usr/lib/python2.7/site-packages/wok/plugins/ginger/models/dasd_utils.py", line 307, in _create_dasd_part
    p_str = _form_part_str(size)
  File "/usr/lib/python2.7/site-packages/wok/plugins/ginger/models/dasd_utils.py", line 323, in _form_part_str
    part_str = '\nn\n \n' + '+' + size + 'M' + '\n' + 'w\n'
TypeError: cannot concatenate 'str' and 'int' objects

**Comment by sureshab** [comment]
also, a quick query,, whats the unit of size? is it bytes?

**Comment by sureshab** [comment]
few more observations
Case1)  when "size" is empty string in input json,, request succeeds without any error, 
[root@zfwcec103 ~]# curl -k -u root -H "Content-Type: application/json" -H "Accept: application/json" -X POST -d '{"dev_name":"dasda", "size":""}' 'https://127.0.0.1:8001/plugins/ginger/dasdpartitions'
{
  "available":false,
  "name":"dasda",
  "fstype":"",
  "path":"/dev/dasda",
  "mountpoint":"",
  "type":"disk",
  "size":"48306585600"
}
Is it Expected behavior? I believe API request should fail with 400.

Case 2) When "dev_name" is empty string, request fails with 500
[root@zfwcec103 ~]# curl -k -u root -H "Content-Type: application/json" -H "Accept: application/json" -X POST -d '{"dev_name":"", "size":""}' 'https://127.0.0.1:8001/plugins/ginger/dasdpartitions'
{
  "reason":"GINDASDPAR0007E: Failed to create partition",
  "code":"500 Internal Server Error"
}

**Comment by sureshab** [comment]
Another scenario:

[root@zfwcec164 ~]# curl -k -u root:pass -H "Content-Type: application/json" -H "Accept: application/json" -X POST -d '{"dev_name":"invalid","size":"unknown"}' 'https://localhost:8001/plugins/ginger/dasdpartitions'
{
  "reason":"GINDASDPAR0007E: Failed to create partition",
  "code":"500 Internal Server Error"
}

**Comment by sureshab** [comment]
On success api returns parent dasd device instead of created partition-

[root@zfwcec164 ~]# curl -k -u root:pass4root -H "Content-Type: application/json" -H "Accept: application/json" -X POST -d '{"dev_name":"dasdd","size":"500"}' 'https://localhost:8001/plugins/ginger/dasdpartitions'
{
  "available":false,
  "name":"dasdd",
  "fstype":"",
  "path":"/dev/dasdd",
  "mountpoint":"",
  "type":"disk",
  "size":"24153292800"
[root@zfwcec164 ~]#

**Comment by sureshab** [comment]
When size is given as empty,,whole dasd size is used for creating partition:

[root@zfwcec164 ~]# lsblk -bo name,type,fstype,mountpoint,size,maj:minNAME                                TYPE  FSTYPE       MOUNTPOINT        SIZE MAJ:MIN
sda                                 disk  mpath_member             3031741440   8:0  
└─20017380030290006                 mpath                          3031741440 253:0  
sdb                                 disk  mpath_member             1073741824   8:16 
└─36005076802810d504800000000002f5f mpath                          1073741824 253:3  
sdc                                 disk  mpath_member             1073741824   8:32 
└─36005076802810d504800000000002f4b mpath                          1073741824 253:4  
sdd                                 disk  mpath_member            21474836480   8:48 
└─36005076802810d504800000000002c20 mpath LVM2_member             21474836480 253:1  
  └─testvg2-lvol0                   lvm                              20971520 253:5  
sde                                 disk  mpath_member             1073741824   8:64 
└─36005076802810d504800000000002f60 mpath                          1073741824 253:2  
dasda                               disk                          24153292800  94:0  
└─dasda1                            part  ext3         /          24153194496  94:1  
dasdd                               disk                          24153292800  94:12 
└─dasdd1                            part                            524255232  94:13 
dasde                               disk                          24153292800  94:16 
[root@zfwcec164 ~]# curl -k -u root:pass -H "Content-Type: application/json" -H "Accept: application/json" -X POST -d '{"dev_name":"dasde","size":""}' 'https://localhost:8001/plugins/ginger/dasdpartitions'
{
  "available":false,
  "name":"dasde",
  "fstype":"",
  "path":"/dev/dasde",
  "mountpoint":"",
  "type":"disk",
  "size":"24153292800"
}[root@zfwcec164 ~]# 
[root@zfwcec164 ~]# lsblk -bo name,type,fstype,mountpoint,size,maj:minNAME                                TYPE  FSTYPE       MOUNTPOINT        SIZE MAJ:MIN
sda                                 disk  mpath_member             3031741440   8:0  
└─20017380030290006                 mpath                          3031741440 253:0  
sdb                                 disk  mpath_member             1073741824   8:16 
└─36005076802810d504800000000002f5f mpath                          1073741824 253:3  
sdc                                 disk  mpath_member             1073741824   8:32 
└─36005076802810d504800000000002f4b mpath                          1073741824 253:4  
sdd                                 disk  mpath_member            21474836480   8:48 
└─36005076802810d504800000000002c20 mpath LVM2_member             21474836480 253:1  
  └─testvg2-lvol0                   lvm                              20971520 253:5  
sde                                 disk  mpath_member             1073741824   8:64 
└─36005076802810d504800000000002f60 mpath                          1073741824 253:2  
dasda                               disk                          24153292800  94:0  
└─dasda1                            part  ext3         /          24153194496  94:1  
dasdd                               disk                          24153292800  94:12 
└─dasdd1                            part                            524255232  94:13 
dasde                               disk                          24153292800  94:16 
└─dasde1                            part                          24153194496  94:17 
[root@zfwcec164 ~]# 


I guess here validating size throwing error would safe instead of using whole disk,,,

**Comment by sureshab** [comment]
with valid device and size as "unknown"

[root@zfwcec164 ~]# curl -k -u root -H "Content-Type: application/json" -H "Accept: application/json" -X POST -d '{"dev_name":"dasde","size":"unknown"}' 'https://localhost:8001/plugins/ginger/dasdpartitions'
Enter host password for user 'root':
{
  "available":false,
  "name":"dasde",
  "fstype":"",
  "path":"/dev/dasde",
  "mountpoint":"",
  "type":"disk",
  "size":"24153292800"
}[root@zfwcec164 ~]# 


It creates using whole disk. how ever api should fail since is size is given as "unknown/invlaid"

**Comment by sureshab** [comment]
***
WOKD STOPS WITH CREATE OPERATION WITH SIZE MORE THAN DASD SIZE
***

create api with size more than disk size

[root@zfwcec164 ~]# lsblk -bo name,type,fstype,mountpoint,size,maj:minNAME                                TYPE  FSTYPE       MOUNTPOINT        SIZE MAJ:MIN
sda                                 disk  mpath_member             3031741440   8:0  
└─20017380030290006                 mpath                          3031741440 253:0  
sdb                                 disk  mpath_member             1073741824   8:16 
└─36005076802810d504800000000002f5f mpath                          1073741824 253:3  
sdc                                 disk  mpath_member             1073741824   8:32 
└─36005076802810d504800000000002f4b mpath                          1073741824 253:4  
sdd                                 disk  mpath_member            21474836480   8:48 
└─36005076802810d504800000000002c20 mpath LVM2_member             21474836480 253:1  
  └─testvg2-lvol0                   lvm                              20971520 253:5  
sde                                 disk  mpath_member             1073741824   8:64 
└─36005076802810d504800000000002f60 mpath                          1073741824 253:2  
dasda                               disk                          24153292800  94:0  
└─dasda1                            part  ext3         /          24153194496  94:1  
dasdd                               disk                          24153292800  94:12 
└─dasdd1                            part                            524255232  94:13 
dasde  

[root@zfwcec164 ~]# curl -k -u root -H "Content-Type: application/json" -H "Accept: application/json" -X POST -d '{"dev_name":"dasde","size":"500000000000"}' 'https://localhost:8001/plugins/ginger/dasdpartitions'
Enter host password for user 'root':
<html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.6.2</center>
</body>
</html>
[root@zfwcec164 ~]# service wokd  status
Redirecting to /bin/systemctl status  wokd.service
wokd.service - Wok - Webserver Originated from Kimchi
   Loaded: loaded (/usr/lib/systemd/system/wokd.service; disabled)
   Active: failed (Result: exit-code) since Fri 2016-01-08 19:29:37 CET; 12s ago
  Process: 16199 ExecStop=/bin/kill -TERM $MAINPID (code=exited, status=1/FAILURE)
  Process: 14280 ExecStart=/usr/bin/wokd (code=killed, signal=KILL)
 Main PID: 14280 (code=killed, signal=KILL)

Jan 08 19:29:37 zfwcec164 kill[16199]: -a, --all              do not restrict the name-to-pid conversion to processes
Jan 08 19:29:37 zfwcec164 kill[16199]: with the same uid as the present process
Jan 08 19:29:37 zfwcec164 kill[16199]: -s, --signal <sig>     send specified signal
Jan 08 19:29:37 zfwcec164 kill[16199]: -q, --queue <sig>      use sigqueue(2) rather than kill(2)
Jan 08 19:29:37 zfwcec164 kill[16199]: -p, --pid              print pids without signaling them
Jan 08 19:29:37 zfwcec164 kill[16199]: -l, --list [=<signal>] list signal names, or convert one to a name
Jan 08 19:29:37 zfwcec164 kill[16199]: -L, --table            list signal names and numbers
Jan 08 19:29:37 zfwcec164 kill[16199]: -h, --help     display this help and exit
Jan 08 19:29:37 zfwcec164 kill[16199]: -V, --version  output version information and exit
Jan 08 19:29:37 zfwcec164 kill[16199]: For more details see kill(1).
Jan 08 19:29:37 zfwcec164 systemd[1]: wokd.service: control process exited, code=exited status=1
Jan 08 19:29:37 zfwcec164 systemd[1]: Unit wokd.service entered failed state.


When I tried for second time,, it was hung  and lpar was also not responding properly...(I could see some memory full msgs in SE with a process id)

**Comment by danielhb** [comment]
Fixed in ca9f1d8
