### ISSUE TITLE
Issues observed for VLAN interface on Fedora 22

### ISSUE THREAD

**Issue by chandrureddy** [kimchi-project/ginger#103]
1. Created the VLAN interface using Network Manager UI. let us say enp0s3.1002.

file created :  ifcfg-VLAN_connection_1

[root@localhost network-scripts]# cat ifcfg-VLAN_connection_1

VLAN=yes
TYPE=Vlan
DEVICE=enp0s3.1002
PHYSDEV=enp0s3
VLAN_ID=1002
REORDER_HDR=0
BOOTPROTO=dhcp
DEFROUTE=yes
PEERDNS=yes
PEERROUTES=yes
IPV4_FAILURE_FATAL=no
IPV6INIT=yes
IPV6_AUTOCONF=yes
IPV6_DEFROUTE=yes
IPV6_PEERDNS=yes
IPV6_PEERROUTES=yes
IPV6_FAILURE_FATAL=no
IPV6_PRIVACY=no
NAME="VLAN connection 1"
UUID=84368c41-217d-4ad8-8489-7be02afb7114
ONBOOT=yes

[root@localhost network-scripts]# ip addr show
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default 
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: enp0s3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 08:00:27:bd:ce:67 brd ff:ff:ff:ff:ff:ff
    inet 10.0.2.15/24 brd 10.0.2.255 scope global dynamic enp0s3
       valid_lft 77665sec preferred_lft 77665sec
    inet6 fe80::a00:27ff:febd:ce67/64 scope link 
       valid_lft forever preferred_lft forever
3: enp0s8: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 08:00:27:5e:64:dc brd ff:ff:ff:ff:ff:ff
4: enp0s9: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 08:00:27:29:58:09 brd ff:ff:ff:ff:ff:ff
7: virbr0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default 
    link/ether 52:54:00:6b:d0:5b brd ff:ff:ff:ff:ff:ff
    inet 192.168.122.1/24 brd 192.168.122.255 scope global virbr0
       valid_lft forever preferred_lft forever
8: virbr0-nic: <BROADCAST,MULTICAST> mtu 1500 qdisc fq_codel master virbr0 state DOWN group default qlen 500
    link/ether 52:54:00:6b:d0:5b brd ff:ff:ff:ff:ff:ff
13: enp0s3.1001@enp0s3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether 08:00:27:bd:ce:67 brd ff:ff:ff:ff:ff:ff
17: enp0s3.1002@enp0s3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether 08:00:27:bd:ce:67 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::a00:27ff:febd:ce67/64 scope link 
       valid_lft forever preferred_lft forever

Now vlan interface was not detected by the rest api cfginterfces :
[root@localhost network-scripts]# curl -k -u root:passw0rd -H "Content-Type: application/json" -H "Accept: application/json" -X GET 'https://127.0.0.1:8001/plugins/ginger/network/cfginterfaces'
[
  {
    "IPV4_INFO":{
      "PEERROUTES":"\"yes\"",
      "BOOTPROTO":"\"dhcp\"",
      "DEFROUTE":"\"yes\"",
      "PEERDNS":"\"yes\"",
      "IPV4_FAILURE_FATAL":"\"no\""
    },
    "BASIC_INFO":{
      "UUID":"\"3e3431f4-7aa6-46cd-a775-737b2e43995b\"",
      "MTU":"1500",
      "HWADDR":"\"08:00:27:BD:CE:67\"",
      "TYPE":"\"Ethernet\"",
      "ONBOOT":"\"yes\"",
      "NAME":"\"enp0s3\""
    },
    "IPV6_INFO":{
      "IPV6INIT":"\"yes\"",
      "IPV6_PEERDNS":"\"yes\"",
      "IPV6_DEFROUTE":"\"yes\"",
      "IPV6_AUTOCONF":"\"yes\"",
      "IPV6_FAILURE_FATAL":"\"no\"",
      "IPV6_PEERROUTES":"\"yes\""
    }
  },
  {
    "IPV4_INFO":{
      "PEERROUTES":"yes",
      "BOOTPROTO":"dhcp",
      "DEFROUTE":"yes",
      "PEERDNS":"yes",
      "IPV4_FAILURE_FATAL":"no"
    },
    "BASIC_INFO":{
      "DEVICE":"enp0s3.1001",
      "MTU":"1500",
      "TYPE":"Vlan",
      "ONBOOT":"yes",
      "VLANINFO":{
        "PHYSDEV":"enp0s3",
        "VLAN":"yes",
        "VLANID":"1001"
      }
    },
    "IPV6_INFO":{
      "IPV6INIT":"yes",
      "IPV6_PEERDNS":"yes",
      "IPV6_PRIVACY":"no",
      "IPV6_DEFROUTE":"yes",
      "IPV6_AUTOCONF":"yes",
      "IPV6_FAILURE_FATAL":"no",
      "IPV6_PEERROUTES":"yes"
    }
  },
  {
    "IPV4_INFO":{},
    "BASIC_INFO":{
      "DEVICE":"lo",
      "MTU":"1500",
      "NAME":"loopback",
      "ONBOOT":"yes"
    },
    "IPV6_INFO":{}
  }
]

Second observation, If I do:
1. changed the file name from  ifcfg-VLAN_connection_1 to ifcfg-enp0s3.1002
mv ifcfg-VLAN_connection_1 ifcfg-enp0s3.1002
2. Remove the UUID from the file
3. ifup ifcfg-enp0s3.1002

[root@localhost network-scripts]# curl -k -u root:passw0rd -H "Content-Type: application/json" -H "Accept: application/json" -X GET 'https://127.0.0.1:8001/plugins/ginger/network/cfginterfaces'
[
  {
    "IPV4_INFO":{
      "PEERROUTES":"\"yes\"",
      "BOOTPROTO":"\"dhcp\"",
      "DEFROUTE":"\"yes\"",
      "PEERDNS":"\"yes\"",
      "IPV4_FAILURE_FATAL":"\"no\""
    },
    "BASIC_INFO":{
      "UUID":"\"3e3431f4-7aa6-46cd-a775-737b2e43995b\"",
      "MTU":"1500",
      "HWADDR":"\"08:00:27:BD:CE:67\"",
      "TYPE":"\"Ethernet\"",
      "ONBOOT":"\"yes\"",
      "NAME":"\"enp0s3\""
    },
    "IPV6_INFO":{
      "IPV6INIT":"\"yes\"",
      "IPV6_PEERDNS":"\"yes\"",
      "IPV6_DEFROUTE":"\"yes\"",
      "IPV6_AUTOCONF":"\"yes\"",
      "IPV6_FAILURE_FATAL":"\"no\"",
      "IPV6_PEERROUTES":"\"yes\""
    }
  },
  {
    "IPV4_INFO":{
      "PEERROUTES":"yes",
      "BOOTPROTO":"dhcp",
      "DEFROUTE":"yes",
      "PEERDNS":"yes",
      "IPV4_FAILURE_FATAL":"no"
    },
    "BASIC_INFO":{
      "DEVICE":"enp0s3.1001",
      "MTU":"1500",
      "TYPE":"Vlan",
      "ONBOOT":"yes",
      "VLANINFO":{
        "PHYSDEV":"enp0s3",
        "VLAN":"yes",
        "VLANID":"1001"
      }
    },
    "IPV6_INFO":{
      "IPV6INIT":"yes",
      "IPV6_PEERDNS":"yes",
      "IPV6_PRIVACY":"no",
      "IPV6_DEFROUTE":"yes",
      "IPV6_AUTOCONF":"yes",
      "IPV6_FAILURE_FATAL":"no",
      "IPV6_PEERROUTES":"yes"
    }
  },
  {
    "IPV4_INFO":{
      "PEERROUTES":"yes",
      "BOOTPROTO":"dhcp",
      "DEFROUTE":"yes",
      "PEERDNS":"yes",
      "IPV4_FAILURE_FATAL":"no"
    },
    "BASIC_INFO":{
      "NAME":"\"VLAN connection 1\"",
      "VLANINFO":{
        "REORDER_HDR":"0",
        "PHYSDEV":"enp0s3",
        "VLAN":"yes"
      },
      "MTU":"1500",
      "DEVICE":"enp0s3.1002",
      "TYPE":"Vlan",
      "ONBOOT":"yes"
    },
    "IPV6_INFO":{
      "IPV6INIT":"yes",
      "IPV6_PEERDNS":"yes",
      "IPV6_PRIVACY":"no",
      "IPV6_DEFROUTE":"yes",
      "IPV6_AUTOCONF":"yes",
      "IPV6_FAILURE_FATAL":"no",
      "IPV6_PEERROUTES":"yes"
    }
  },
  {
    "IPV4_INFO":{},
    "BASIC_INFO":{
      "DEVICE":"lo",
      "MTU":"1500",
      "NAME":"loopback",
      "ONBOOT":"yes"
    },
    "IPV6_INFO":{}
  }
]

One more observation was Network Manager using VLAN_ID but from our code I guess we are using VLANID, Because of this VLANID value not shown for the interface enp0s3.1002.

**Comment by jay-katta** [comment]
Fix has given as part of the patch with following commit message -

Fixing vlan and bond issues in cfginterfaces
This patch addresses below issues
        1. Correcting vlan key from VLANID to VLAN_ID
        2. Relaxing VLAN_ID key in case of vlan id given as part
           of device name
        3. Validations added for the vland id if it is given as
           part of device name
	4. For bond, added validation to check blank device name

**Comment by abhiramkulkarni** [comment]
Fix working in latest upstreamed code.
