### ISSUE TITLE
REST API list interfaces returns the type incorrectly

### ISSUE THREAD

**Issue by chandrureddy** [kimchi-project/ginger#105]
I have interface enp0s3 with following details in the cfg file:[root@localhost network-scripts]# cat ifcfg-enp0s3
HWADDR="08:00:27:BD:CE:67"
TYPE="Ethernet"
BOOTPROTO="dhcp"
DEFROUTE="yes"
IPV4_FAILURE_FATAL="no"
IPV6INIT="yes"
IPV6_AUTOCONF="yes"
IPV6_DEFROUTE="yes"
IPV6_FAILURE_FATAL="no"
NAME="enp0s3"
UUID="3e3431f4-7aa6-46cd-a775-737b2e43995b"
ONBOOT="yes"
PEERDNS="yes"
PEERROUTES="yes"
IPV6_PEERDNS="yes"
IPV6_PEERROUTES="yes"

REST API interfaces returns the type as "nic" which I suppose expect it to be "Ethernet"
[root@localhost network-scripts]# curl -k -u root:passw0rd -H "Content-Type: application/json" -H "Accept: application/json" -X GET 'https://127.0.0.1:8001/plugins/ginger/network/interfaces'
[
  {
    "status":"up",
    "macaddr":"08:00:27:bd:ce:67",
    "name":"enp0s3",
    "editable":false,
    "ipaddr":"10.0.2.15",
    "netmask":"255.255.255.0",
    "type":"nic"
  },
  {
    "status":"up",
    "macaddr":"08:00:27:bd:ce:67",
    "name":"enp0s3.1001",
    "editable":true,
    "ipaddr":"",
    "netmask":"",
    "type":"vlan"
  },
  {
    "status":"up",
    "macaddr":"08:00:27:bd:ce:67",
    "name":"enp0s3.1002",
    "editable":true,
    "ipaddr":"",
    "netmask":"",
    "type":"vlan"
  },
  {
    "status":"up",
    "macaddr":"08:00:27:5e:64:dc",
    "name":"enp0s8",
    "editable":false,
    "ipaddr":"",
    "netmask":"",
    "type":"nic"
  },
  {
    "status":"up",
    "macaddr":"08:00:27:29:58:09",
    "name":"enp0s9",
    "editable":false,
    "ipaddr":"",
    "netmask":"",
    "type":"nic"
  },
  {
    "status":"unknown",
    "macaddr":"00:00:00:00:00:00",
    "name":"lo",
    "editable":true,
    "ipaddr":"127.0.0.1",
    "netmask":"255.0.0.0",
    "type":"unknown"
  },
  {
    "status":"down",
    "macaddr":"52:54:00:6b:d0:5b",
    "name":"virbr0",
    "editable":false,
    "ipaddr":"192.168.122.1",
    "netmask":"255.255.255.0",
    "type":"bridge"
  },
  {
    "status":"down",
    "macaddr":"52:54:00:6b:d0:5b",
    "name":"virbr0-nic",
    "editable":false,
    "ipaddr":"",
    "netmask":"",
    "type":"unknown"
  }
]

Not sure if it is still correct but this could be kind of confusing return type value for me.

**Comment by jay-katta** [comment]
Please assign this to me

**Comment by danielhb** [comment]
Fix was pushed upstream. Please verify if it works

**Comment by chandrureddy** [comment]
Fix work as expected. Please close the ticket.
