### ISSUE TITLE
List cfginterfaces/interfaces should consistently return DEVICE/NAME

### ISSUE THREAD

**Issue by chandrureddy** [kimchi-project/ginger#106]
List cfginterfaces/interfaces should consistently return DEVICE/NAME .
I guess DEVICE should returned across the REST API calls for consistency. Right now it is returning DEVICE or NAME values may be one but not both. some what confusing to get it right from UI point of view.

I would expect at least DEVICE must be returned for list of both cfginterfaces/interfaces. If possible both :-)

[root@localhost network-scripts]# curl -k -u root:passw0rd -H "Content-Type: application/json" -H "Accept: application/json" -X GET 'https://127.0.0.1:8001/plugins/ginger/network/cfginterfaces'
[
  {
    "IPV4_INFO":{
      "PEERROUTES":"\"yes\"",
      "BOOTPROTO":"\"dhcp\"",
      "DEFROUTE":"\"yes\"",
      "PEERDNS":"\"yes\"",
      "IPV4_FAILURE_FATAL":"\"no\""
    },
    "BASIC_INFO":{
      "UUID":"\"3e3431f4-7aa6-46cd-a775-737b2e43995b\"",
      "MTU":"1500",
      "HWADDR":"\"08:00:27:BD:CE:67\"",
      "TYPE":"\"Ethernet\"",
      "ONBOOT":"\"yes\"",
      "NAME":"\"enp0s3\""
    },
    "IPV6_INFO":{
      "IPV6INIT":"\"yes\"",
      "IPV6_PEERDNS":"\"yes\"",
      "IPV6_DEFROUTE":"\"yes\"",
      "IPV6_AUTOCONF":"\"yes\"",
      "IPV6_FAILURE_FATAL":"\"no\"",
      "IPV6_PEERROUTES":"\"yes\""
    }
  },
  {
    "IPV4_INFO":{
      "PEERROUTES":"yes",
      "BOOTPROTO":"dhcp",
      "DEFROUTE":"yes",
      "PEERDNS":"yes",
      "IPV4_FAILURE_FATAL":"no"
    },
    "BASIC_INFO":{
      "VLANINFO":{
        "PHYSDEV":"enp0s3",
        "VLAN":"yes",
        "VLANID":"1001"
      },
      "MTU":"1500",
      "HWADDR":"\"08:00:27:BD:CE:67\"",
      "DEVICE":"enp0s3.1001",
      "TYPE":"Vlan",
      "ONBOOT":"yes"
    },
    "IPV6_INFO":{
      "IPV6INIT":"yes",
      "IPV6_PEERDNS":"yes",
      "IPV6_PRIVACY":"no",
      "IPV6_DEFROUTE":"yes",
      "IPV6_AUTOCONF":"yes",
      "IPV6_FAILURE_FATAL":"no",
      "IPV6_PEERROUTES":"yes"
    }
  },
  {
    "IPV4_INFO":{
      "PEERROUTES":"yes",
      "BOOTPROTO":"dhcp",
      "DEFROUTE":"yes",
      "PEERDNS":"yes",
      "IPV4_FAILURE_FATAL":"no"
    },
    "BASIC_INFO":{
      "NAME":"\"VLAN connection 1\"",
      "VLANINFO":{
        "REORDER_HDR":"0",
        "PHYSDEV":"enp0s3",
        "VLAN":"yes"
      },
      "MTU":"1500",
      "DEVICE":"enp0s3.1002",
      "TYPE":"Vlan",
      "ONBOOT":"yes"
    },
    "IPV6_INFO":{
      "IPV6INIT":"yes",
      "IPV6_PEERDNS":"yes",
      "IPV6_PRIVACY":"no",
      "IPV6_DEFROUTE":"yes",
      "IPV6_AUTOCONF":"yes",
      "IPV6_FAILURE_FATAL":"no",
      "IPV6_PEERROUTES":"yes"
    }
  },
  {
    "IPV4_INFO":{},
    "BASIC_INFO":{
      "DEVICE":"lo",
      "MTU":"1500",
      "NAME":"loopback",
      "ONBOOT":"yes"
    },
    "IPV6_INFO":{}
  }
[root@localhost network-scripts]# curl -k -u root:passw0rd -H "Content-Type: application/json" -H "Accept: application/json" -X GET 'https://127.0.0.1:8001/plugins/ginger/network/interfaces'
[
  {
    "status":"up",
    "macaddr":"08:00:27:bd:ce:67",
    "name":"enp0s3",
    "editable":false,
    "ipaddr":"10.0.2.15",
    "netmask":"255.255.255.0",
    "type":"nic"
  },
  {
    "status":"up",
    "macaddr":"08:00:27:bd:ce:67",
    "name":"enp0s3.1001",
    "editable":true,
    "ipaddr":"",
    "netmask":"",
    "type":"vlan"
  },
  {
    "status":"up",
    "macaddr":"08:00:27:bd:ce:67",
    "name":"enp0s3.1002",
    "editable":true,
    "ipaddr":"",
    "netmask":"",
    "type":"vlan"
  },
  {
    "status":"up",
    "macaddr":"08:00:27:5e:64:dc",
    "name":"enp0s8",
    "editable":false,
    "ipaddr":"",
    "netmask":"",
    "type":"nic"
  },
  {
    "status":"up",
    "macaddr":"08:00:27:29:58:09",
    "name":"enp0s9",
    "editable":false,
    "ipaddr":"",
    "netmask":"",
    "type":"nic"
  },
  {
    "status":"unknown",
    "macaddr":"00:00:00:00:00:00",
    "name":"lo",
    "editable":true,
    "ipaddr":"127.0.0.1",
    "netmask":"255.0.0.0",
    "type":"unknown"
  },
  {
    "status":"down",
    "macaddr":"52:54:00:6b:d0:5b",
    "name":"virbr0",
    "editable":false,
    "ipaddr":"192.168.122.1",
    "netmask":"255.255.255.0",
    "type":"bridge"
  },
  {
    "status":"down",
    "macaddr":"52:54:00:6b:d0:5b",
    "name":"virbr0-nic",
    "editable":false,
    "ipaddr":"",
    "netmask":"",
    "type":"unknown"
  }
][root@localhost network-scripts]#

**Comment by jay-katta** [comment]
Please assign this to me.

**Comment by danielhb** [comment]
Fix was pushed upstream. Please verify if it works

**Comment by jay-katta** [comment]
Verified

**Comment by abhiramkulkarni** [comment]
Working in latest upstreamed code
