### ISSUE TITLE
NW: Getting "Bootpro missing" for PUT operation for cfginterface

### ISSUE THREAD

**Issue by archu-s** [kimchi-project/ginger#108]
With below curl command getting "Bootpro missing".

curl -u root -H "Content-Type: application/json" -H "Accept:application/jsn" -X GET "http://localhost:8010/plugins/ginger/network/cfginterfaces/enp0s3d"^C
[archana@localhost ginger]$ curl -u root -H "Content-Type: application/json" -H "Accept:application/json" -X PUT -d '{"BASIC_INFO":{"ONBOOT":"yes","DEVICE":"enp0s3d","MTU":"None"},"IPV4_INFO":{"IPV4INIT":"yes","BOOTPROTO":"none","IPV4Addresses":[{"PREFIX":"24","IPADDR":"10.10.10.15","GATEWAY":"10.10.10.10"},{"PREFIX":"24","IPADDR":"10.10.10.17","GATEWAY":"10.10.10.10"},{"PREFIX":"24","IPADDR":"10.10.10.12","GATEWAY":"10.10.10.10"},{"PREFIX":"24","IPADDR":"10.10.10.18","GATEWAY":"10.10.10.10"}],"DNSAddresses":["9.9.9.9"],"ROUTES":[{"METRIC":"9.9.9.9","NETMASK":"9.9.9.9","GATEWAY":"9.9.9.9","ADDRESS":"9.9.9.9"}]},"IPV6_INFO":{"IPV6INIT":"yes","DNSAddresses":["9.9.9.9"]}}' "http://localhost:8010/plugins/ginger/network/cfginterfaces/enp0s3d"
Enter host password for user 'root':
{
  "reason":"GINNET0023E: Boot protocol is missing.",
  "code":"500 Internal Server Error"
}

**Comment by abhiramkulkarni** [comment]
Here bootprotocol is missing. Probably this can be taken as enhancement of messages displayed.

Please find the working curl below.
curl -u root -H "Content-Type: application/json" -H "Accept:application/json" -X PUT -d '{"BASIC_INFO":{"ONBOOT":"yes","DEVICE":"enp0s3d","MTU":"None"},"IPV4_INFO":{IPV4INIT":"yes","BOOTPROTO":"none","IPV4Addresses":[{"PREFIX":"24","IPADDR":"10.10.10.15","GATEWAY":"10.10.10.10"},{"PREFIX":"24","IPADDR":"10.10.10.17","GATEWAY":"10.10.10.10"},{"PREFIX":"24","IPADDR":"10.10.10.12","GATEWAY":"10.10.10.10"},{"PREFIX":"24","IPADDR":"10.10.10.18","GATEWAY":"10.10.10.10"}],"DNSAddresses":["9.9.9.9"],"ROUTES":[{"METRIC":"9.9.9.9","NETMASK":"9.9.9.9","GATEWAY":"9.9.9.9","ADDRESS":"9.9.9.9"}]},"IPV6_INFO":{"IPV6INIT":"yes","IPV6_AUTOCONF": "yes","DNSAddresses":["9.9.9.9"]}}' "http://localhost:8010/plugins/ginger/network/cfginterfaces/eth0"

**Comment by abhiramkulkarni** [comment]
Fix is working in latest upstream code.
