### ISSUE TITLE
NW: cfginterface GET operation is not getting IPV4init value

### ISSUE THREAD

**Issue by archu-s** [kimchi-project/ginger#110]
cfginterface GET operation is not getting IPV4init value.

curl -u root -H "Content-Type: application/json" -H "Accept:application/jn" -X GET "http://localhost:8010/plugins/ginger/network/cfginterfaces/enp0s3d"Enter host password for user 'root':
{
  "IPV4_INFO":{
    "PEERROUTES":"\"yes\"",
    "DEFROUTE":"\"yes\"",
    "PEERDNS":"\"yes\"",
    "IPV4_FAILURE_FATAL":"\"no\"",
    "IPV4Addresses":[
      {
        "PREFIX":"24",
        "IPADDR":"10.10.10.15",
        "GATEWAY":"10.10.10.10"
      },
      {
        "PREFIX":"24",
        "IPADDR":"10.10.10.17",
        "GATEWAY":"10.10.10.10"
      },
      {
        "PREFIX":"24",
        "IPADDR":"10.10.10.12",
        "GATEWAY":"10.10.10.10"
      },
      {
        "PREFIX":"24",
        "IPADDR":"10.10.10.18",
        "GATEWAY":"10.10.10.10"
      }
    ],
    "BOOTPROTO":"none",
    "DNSAddresses":[
      "9.9.9.9"
    ],
    "ROUTES":[
      {
        "METRIC":"9.9.9.9",
        "NETMASK":"9.9.9.9",
        "GATEWAY":"9.9.9.9",
        "ADDRESS":"9.9.9.9"
      }
    ]
  },
  "BASIC_INFO":{
    "UUID":"\"7241d3b4-2b15-49a8-994e-b788062a9b02\"",
    "MTU":"None",
    "HWADDR":"08:00:27:65:33:7F",
    "DEVICE":"enp0s3d",
    "TYPE":"Ethernet",
    "ONBOOT":"yes",
    "NAME":"enp0s3d"
  },
  "IPV6_INFO":{
    "IPV6INIT":"\"yes\"",
    "IPV6_PEERDNS":"\"yes\"",
    "IPV6_DEFROUTE":"\"yes\"",
    "IPV6_AUTOCONF":"\"yes\"",
    "IPV6_FAILURE_FATAL":"\"no\"",
    "IPV6_PEERROUTES":"\"yes\""
  }

**Comment by abhiramkulkarni** [comment]
I will be working on this issue and provide the patch

**Comment by abhiramkulkarni** [comment]
Earlier code was implemented only considering the keys that are allowed in ifcfg file. IPV4INIT will not been added to cfg file. But since UI needs this value , if there are any IPV4 information, then IPV4INIT=yes will be set in backend code and sent in lookup. If no IPV4 information, then IPV4INIT=no will be set in backend code

**Comment by danielhb** [comment]
A fix is available in current master. Please check if it works.

**Comment by abhiramkulkarni** [comment]
The current patch provided is fine, but still need to investigate further how to retain the value of IPV4 init since its not an attribute in ifcfg file.

**Comment by abhiramkulkarni** [comment]
Fix is working in latest upstream code.
