### ISSUE TITLE
NW: operation failed for cfginterface PUT with "BOOTPROTO":"autoip" for ipv4 

### ISSUE THREAD

**Issue by archu-s** [kimchi-project/ginger#111]
Below curl gives "The server encountered an unexpected condition which prevented it from fulfilling the request". If passed "BOOTPROTO":"none", then it works fine. But with "BOOTPROTO":"autoip" it give the error.

curl -u root -H "Content-Type: application/json" -H "Accept:application/json" -X PUT -d '{"BASIC_INFO":{"ONBOOT":"yes","DEVICE":"enp0s3d","MTU":"None"},"IPV4_INFO":{"BOOTPROTO":"autoip","IPV4INIT":"yes","IPV4Addresses":[{"PREFIX":"24","IPADDR":"10.10.10.15","GATEWAY":"10.10.10.10"},{"PREFIX":"24","IPADDR":"10.10.10.17","GATEWAY":"10.10.10.10"},{"PREFIX":"24","IPADDR":"10.10.10.12","GATEWAY":"10.10.10.10"},{"PREFIX":"24","IPADDR":"10.10.10.18","GATEWAY":"10.10.10.10"}],"DNSAddresses":["9.9.9.9"],"ROUTES":[{"METRIC":"9.9.9.9","NETMASK":"9.9.9.9","GATEWAY":"9.9.9.9","ADDRESS":"9.9.9.9"}]}}' "http://localhost:8010/plugins/ginger/network/cfginterfaces/enp0s3d"

**Comment by abhiramkulkarni** [comment]
This is a bug, need to fix. Please assign the defect to me

**Comment by danielhb** [comment]
A fix is available in current master. Please check if it works.

**Comment by abhiramkulkarni** [comment]
Fix is working in latest upstream code.
