### ISSUE TITLE
NW: operation failed for cfginterface PUT with "BOOTPROTO":"dhcp" for ipv4

### ISSUE THREAD

**Issue by archu-s** [kimchi-project/ginger#112]
Below curl gives "The server encountered an unexpected condition which prevented it from fulfilling the request". If passed "BOOTPROTO":"none", then it works fine. But with "BOOTPROTO":"dhcp" it give the error.

curl -u root -H "Content-Type: application/json" -H "Accept:application/json" -X PUT -d '{"BASIC_INFO":{"ONBOOT":"yes","DEVICE":"enp0s3d","MTU":"None"},"IPV4_INFO":{"IPV4INIT":"yes","BOOTPROTO":"dhcp","DNSAddresses":["9.9.9.9"],"ROUTES":[{"METRIC":"9.9.9.9","NETMASK":"9.9.9.9","GATEWAY":"9.9.9.9","ADDRESS":"9.9.9.9"}]}}' "http://localhost:8010/plugins/ginger/network/cfginterfaces/enp0s3d"

**Comment by abhiramkulkarni** [comment]
This issue will happen when bootproto is dhcp and defroute is not provided.

  File "/usr/lib/python2.7/site-packages/wok/plugins/ginger/models/cfginterfaces.py", line 787, in update
    cfgmap = self.update_ipv4(cfgmap, params)
  File "/usr/lib/python2.7/site-packages/wok/plugins/ginger/models/cfginterfaces.py", line 768, in update_ipv4
    cfgmap = self.update_ipv4_bootproto(cfgmap, params)
  File "/usr/lib/python2.7/site-packages/wok/plugins/ginger/models/cfginterfaces.py", line 725, in update_ipv4_bootproto
    if DEFROUTE in params[IPV4_ID][DEFROUTE]:
KeyError: 'DEFROUTE'



This is bug, should look for defroute only if it is provided. Will provide patch for same.

After fixing, 

bash-4.3# curl -u root -H "Content-Type: application/json" -H "Accept:application/json" -X PUT -d '{"BASIC_INFO":{"ONBOOT":"yes","DEVICE":"enp0s3d","MTU":"None"},"IPV4INIT":"yes","BOOTPROTO":"dhcp","DNSAddresses":["9.9.9.9"],"ROUTES":[{"METRIC":"9.9.9.9","NETMASK":"9.9.9.9","GATEWAY":"9.9.9.9","ADDRESS":"9.9.9.9"}]}}' "http://localhost:8010/plugins/ginger/network/cfginterfaces/eth0"
Enter host password for user 'root':
{
  "IPV4_INFO":{
    "PEERROUTES":"yes",
    "DEFROUTE":"yes",
    "PEERDNS":"yes",
    "BOOTPROTO":"dhcp",
    "DNSAddresses":[
      "9.9.9.9"
    ],
    "ROUTES":[
      {
        "METRIC":"9.9.9.9",
        "NETMASK":"9.9.9.9",
        "GATEWAY":"9.9.9.9",
        "ADDRESS":"9.9.9.9"
      }
    ]
  },
  "BASIC_INFO":{
    "DEVICE":"enp0s3d",
    "MTU":"None",
    "NAME":"eth0",
    "ZONE":"FedoraServer",
    "ONBOOT":"yes"
  },
  "IPV6_INFO":{}

**Comment by abhiramkulkarni** [comment]
Please assign this bug to me

**Comment by danielhb** [comment]
A fix is available in current master. Please check if it works.

**Comment by abhiramkulkarni** [comment]
Fix is working in latest upstream code
