### ISSUE TITLE
VLAN interface creation should allow creation of 0-4094 vlan ids on each interface

### ISSUE THREAD

**Issue by chandrureddy** [kimchi-project/ginger#114]
Right now back end code allows creation of vlan interfaces 0-4094 across all the interfaces which means it is not allow you to create vlan interface with same vlanid on multiple interfaces. 

Ideally implementation should allow creation of vlan interfaces with same vlanid on multiple interfaces with out any issue. ie we could have 0-4094 vlan interfaces on each interface/nic present on the machine.

**Comment by jay-katta** [comment]
Assign this to me.

**Comment by danielhb** [comment]
Fix was pushed upstream. Please verify if it works

**Comment by chandrureddy** [comment]
Fix works as expected. Please close the ticket.
