### ISSUE TITLE
Few Links to the pages are missing under Storage Devices

### ISSUE THREAD

**Issue by rajatgupta21** [kimchi-project/ginger#115]
1. Under Storage tab, open Storage Devices section and click on Add -> Add ECKD Devices. Page does not open pop.
2.  Under Storage tab, open the Storage Devices section, Add -> "Add iSCSI" is not implemented hence please comment the code for now.
3. For GingerS390x under Storage tab open "SAN Adapters" section, Add button is always disabled please enable the and point to respective page.

**Comment by chandrureddy** [comment]
Working on it. Will send patch soon

**Comment by danielhb** [comment]
Fix was pushed upstream. Please verify if it works
