### ISSUE TITLE
NW: Failed to set Ipv6Init to No

### ISSUE THREAD

**Issue by archu-s** [kimchi-project/ginger#118]
Put operation for cfginterface with below data failed.
{"BASIC_INFO":{"ONBOOT":"yes","DEVICE":"enp0s3d","MTU":"None"},"IPV4_INFO":{"IPV4INIT":"yes","BOOTPROTO":"none","IPV4Addresses":[{"PREFIX":"24","IPADDR":"10.10.10.15","GATEWAY":"10.10.10.10"},{"PREFIX":"24","IPADDR":"10.10.10.17","GATEWAY":"10.10.10.10"},{"PREFIX":"24","IPADDR":"10.10.10.12","GATEWAY":"10.10.10.10"},{"PREFIX":"24","IPADDR":"10.10.10.18","GATEWAY":"10.10.10.10"}],"DNSAddresses":["9.9.9.9"],"ROUTES":[{"METRIC":"9.9.9.9","NETMASK":"9.9.9.9","GATEWAY":"9.9.9.9","ADDRESS":"9.9.9.9"}]},"IPV6_INFO":{"IPV6INIT":"no"}}

result:
{
  "reason":"GINNET0027E: Missing ipv6 initialization key.",
  "code":"500 Internal Server Error"
}

**Comment by abhiramkulkarni** [comment]
This issue is same as ipv4 issue  #109 and same has been handled along with patch #109 

Let me know if issue is not fixed there.

**Comment by abhiramkulkarni** [comment]
Fix is working in latest upstream code.
