### ISSUE TITLE
Makefile.am of controls and models not updated for sysmodules

### ISSUE THREAD

**Issue by jay-katta** [kimchi-project/ginger#119]
Makefile.am of controls and models not updated for sysmodules

Error log:
Failed to import plugin plugins.ginger.Ginger, error: Class plugins.ginger.Ginger can not be imported, error: No module named sysmodules

**Comment by danielhb** [comment]
On it

**Comment by danielhb** [comment]
I'll add the files to Makefile.am, but how did you get this error? I've tried with a clean git clone and couldn't get it

**Comment by danielhb** [comment]
Done. Let me know if the issue if fixed, @jay-katta 

And let me know how can I reproduced it to avoid screwing up in the future :)

**Comment by danielhb** [comment]
@jay-katta can we close this one?

**Comment by jay-katta** [comment]
Steps to reproduce:
1. Clean uninstall of existing wok and its plugins
2. Clone wok and its plugins
3. Compile and install - wok,gingerbase and ginger
4. Run any one API call of ginger

**Comment by jay-katta** [comment]
@danielhb , I am closing this issue.
