### ISSUE TITLE
Change Power Management Options does not work on a Power System.

### ISSUE THREAD

**Issue by jrziviani** [kimchi-project/ginger#120]
If I try to activate any **Power Option** under **Host** → **Administration** I get the error:
```
Error GINPOWER004E: Error activating power saving profile undefined.
```
However it's possible to change the power management profile in the command line:

```bash
# tuned-adm active
Current active profile: balanced
# tuned-adm profile default
# tuned-adm active
Current active profile: default
```
* Note: the log is being flooded with messages like *Sensors hdd: /dev/sdc: AMI Virtual HDisk1: S.M.A.R.T. not available* that it makes a hard time trying to find something in there.

**Comment by danielhb** [comment]
It works in F23 using curl:

```
[danielhb@arthas wok_danielhb_repos]$ tuned-adm active
Current active profile: throughput-performance
[danielhb@arthas wok_danielhb_repos]$
[danielhb@arthas wok_danielhb_repos]$ curl -u root -H "Content-Type: application/json" -H "Accept: application/json" -k "https://localhost:8001/plugins/ginger/powerprofiles/balanced" -X PUT -d'{"active":true}'
Enter host password for user 'root':
{
  "active":true,
  "name":"balanced"
}[danielhb@arthas wok_danielhb_repos]$
[danielhb@arthas wok_danielhb_repos]$ tuned-adm active
Current active profile: balanced
[danielhb@arthas wok_danielhb_repos]$ 

```

Perhaps it is an UI issue?

**Comment by danielhb** [comment]
It is an UI issue. It happened in the same env that works fine using curl:

![image](https://cloud.githubusercontent.com/assets/866780/12120016/00a3d5d0-b3b6-11e5-821b-de2fc57479dd.png)


I'll update the tags accordingly.
