### ISSUE TITLE
Mismatched password opens three error message windows.

### ISSUE THREAD

**Issue by jrziviani** [kimchi-project/ginger#123]
Navigate to **Host** → **Administration** → **User Management**, click on **Add User**. Fill the form with your new user credentials _(enable the **Use Other** and type a group name due to Issue #122)_ **BUT** use different password values for both **Password** and **Confirm Password** fields.

You will get three error message windows:
![image](https://cloud.githubusercontent.com/assets/670087/12121443/7f919e08-b3bc-11e5-86ab-06f2adb97270.png)

**Comment by alinefm** [comment]
HI @jrziviani 

I could not reproduce it on 82d17adfc840b783ebb2e37e53a7e9109a7bfad1

Could you confirm that and provide your results here?

**Comment by jrziviani** [comment]
Problem fixed:

![image](https://cloud.githubusercontent.com/assets/670087/16678081/2501aa96-44b2-11e6-8545-3819884cd891.png)

Thank you
