### ISSUE TITLE
NW: cfginterface put with Ipv6 DNAddresses is not getting added to ifcfg file

### ISSUE THREAD

**Issue by archu-s** [kimchi-project/ginger#124]
For below curl data for PUT opration for cfginterface, is not adding DNS addresses ifcfg file.

{"BASIC_INFO":{"ONBOOT":"yes","DEVICE":"enp0s3d","MTU":"None"},"IPV4_INFO":{"IPV4INIT":"yes","BOOTPROTO":"none","IPV4Addresses":[{"PREFIX":"24","IPADDR":"10.10.10.15","GATEWAY":"10.10.10.10"},{"PREFIX":"24","IPADDR":"10.10.10.17","GATEWAY":"10.10.10.10"},{"PREFIX":"24","IPADDR":"10.10.10.12","GATEWAY":"10.10.10.10"},{"PREFIX":"24","IPADDR":"10.10.10.18","GATEWAY":"10.10.10.10"}],"DNSAddresses":["9.9.9.9"],"ROUTES":[{"METRIC":"9.9.9.9","NETMASK":"9.9.9.9","GATEWAY":"9.9.9.9","ADDRESS":"9.9.9.9"}]},"IPV6_INFO":{"IPV6INIT":"yes","IPV6_AUTOCONF":"no","IPV6Addresses":[{"PREFIX":"fe80::ff:fe23:9f4d","IPADDR":"fe80::ff:fe23:9f4d"}],"DNSAddresses":["fe80::ff:fe23:9f4d"],"ROUTES":[{"METRIC":"fe80::ff:fe23:9f4d","NETMASK":"fe80::ff:fe23:9f4d","GATEWAY":"fe80::ff:fe23:9f4d","ADDRESS":"fe80::ff:fe23:9f4d"}]}

GET response of the interface after the above put operation:
{
  "IPV4_INFO":{
    "PEERROUTES":"\"yes\"",
    "DEFROUTE":"\"yes\"",
    "PEERDNS":"\"yes\"",
    "IPV4_FAILURE_FATAL":"\"no\"",
    "IPV4Addresses":[
      {
        "PREFIX":"24",
        "IPADDR":"10.10.10.15",
        "GATEWAY":"10.10.10.10"
      },
      {
        "PREFIX":"24",
        "IPADDR":"10.10.10.17",
        "GATEWAY":"10.10.10.10"
      },
      {
        "PREFIX":"24",
        "IPADDR":"10.10.10.12",
        "GATEWAY":"10.10.10.10"
      },
      {
        "PREFIX":"24",
        "IPADDR":"10.10.10.18",
        "GATEWAY":"10.10.10.10"
      }
    ],
    "BOOTPROTO":"none",
    "DNSAddresses":[
      "9.9.9.9"
    ],
    "ROUTES":[
      {
        "METRIC":"9.9.9.9",
        "NETMASK":"9.9.9.9",
        "GATEWAY":"9.9.9.9",
        "ADDRESS":"9.9.9.9"
      }
    ]
  },
  "BASIC_INFO":{
    "UUID":"\"7241d3b4-2b15-49a8-994e-b788062a9b02\"",
    "MTU":"None",
    "HWADDR":"08:00:27:65:33:7F",
    "DEVICE":"enp0s3d",
    "TYPE":"Ethernet",
    "ONBOOT":"yes",
    "NAME":"enp0s3d"
  },
  "IPV6_INFO":{
    "IPV6INIT":"\"yes\"",
    "IPV6_PEERDNS":"\"yes\"",
    "IPV6Addresses":[
      {
        "PREFIX":"fe80::ff:fe23:9f4d",
        "IPADDR":"fe80::ff:fe23:9f4d"
      }
    ],
    "IPV6_DEFROUTE":"\"yes\"",
    "ROUTES":[
      {
        "METRIC":"fe80::ff:fe23:9f4d",
        "NETMASK":"fe80::ff:fe23:9f4d",
        "GATEWAY":"fe80::ff:fe23:9f4d",
        "ADDRESS":"fe80::ff:fe23:9f4d"
      }
    ],
    "IPV6_AUTOCONF":"no",
    "IPV6_FAILURE_FATAL":"\"no\"",
    "DHCPV6C":"yes",
    "IPV6_PEERROUTES":"\"yes\""
  }
}

**Comment by abhiramkulkarni** [comment]
@archu-s 

can you please help with sequence of operations you performed here?
Is it a first time update? Because first time update will work.

This case also might be similar to Issue #126 

Issue #126 i was able to identiy, here your steps will help me investigate further.

Thanks.

**Comment by abhiramkulkarni** [comment]
Fix is working in latest upstream code
