### ISSUE TITLE
Delete volumegroup fails with 500

### ISSUE THREAD

**Issue by sureshab** [kimchi-project/ginger#125]
Delete volume group which has lv:

[root@zfwcec164 ~]# vgdisplay testvg2 
  --- Volume group ---
  VG Name               testvg2
  System ID             
  Format                lvm2
  Metadata Areas        1
  Metadata Sequence No  2
  VG Access             read/write
  VG Status             resizable
  MAX LV                0
  Cur LV                1
  Open LV               0
  Max PV                0
  Cur PV                1
  Act PV                1
  VG Size               20.00 GiB
  PE Size               4.00 MiB
  Total PE              5119
  Alloc PE / Size       5 / 20.00 MiB
  Free  PE / Size       5114 / 19.98 GiB
  VG UUID               h20dQg-YqLE-713j-1HhD-WDi2-Mu32-5PM5mr

[root@zfwcec164 ~]# curl -k -u root -H "Content-Type: application/json" -H "Accept: application/json" -X DELETE 'https://localhost:8001/plugins/ginger/vgs/testvg2'
Enter host password for user 'root':
{
  "reason":"GINVG00004E: Failed to delete VG",
  "code":"500 Internal Server Error"
} 

More to do with Status code here.

**Comment by harche** [comment]
I will be working on this issue
