### ISSUE TITLE
NW: cfginterface for ipv4 address, GET after PUT operation with multiple DNS address is not getting all the values.

### ISSUE THREAD

**Issue by archu-s** [kimchi-project/ginger#126]
data for curl command:

{"BASIC_INFO":{"ONBOOT":"yes","DEVICE":"enp0s3d","MTU":"None"},"IPV4_INFO":{"IPV4INIT":"yes","BOOTPROTO":"none","IPV4Addresses":[{"PREFIX":"24","IPADDR":"10.10.10.15","GATEWAY":"10.10.10.10"},{"PREFIX":"24","IPADDR":"10.10.10.17","GATEWAY":"10.10.10.10"},{"PREFIX":"24","IPADDR":"10.10.10.12","GATEWAY":"10.10.10.10"},{"PREFIX":"24","IPADDR":"10.10.10.18","GATEWAY":"10.10.10.10"}],"DNSAddresses":["9.9.9.9","10.10.10.10"],"ROUTES":[{"METRIC":"9.9.9.9","NETMASK":"9.9.9.9","GATEWAY":"9.9.9.9","ADDRESS":"9.9.9.9"}]},"IPV6_INFO":{"IPV6INIT":"yes","IPV6_AUTOCONF":"no","IPV6Addresses":[{"PREFIX":"fe80::ff:fe23:9f4d","IPADDR":"fe80::ff:fe23:9f4d"}],"ROUTES":[{"METRIC":"fe80::ff:fe23:9f4d","NETMASK":"fe80::ff:fe23:9f4d","GATEWAY":"fe80::ff:fe23:9f4d","ADDRESS":"fe80::ff:fe23:9f4d"}]}}

Get output after above put operation, gets just one DNS address

{
  "IPV4_INFO":{
    "PEERROUTES":"\"yes\"",
    "DEFROUTE":"\"yes\"",
    "PEERDNS":"\"yes\"",
    "IPV4_FAILURE_FATAL":"\"no\"",
    "IPV4Addresses":[
      {
        "PREFIX":"24",
        "IPADDR":"10.10.10.15",
        "GATEWAY":"10.10.10.10"
      },
      {
        "PREFIX":"24",
        "IPADDR":"10.10.10.17",
        "GATEWAY":"10.10.10.10"
      },
      {
        "PREFIX":"24",
        "IPADDR":"10.10.10.12",
        "GATEWAY":"10.10.10.10"
      },
      {
        "PREFIX":"24",
        "IPADDR":"10.10.10.18",
        "GATEWAY":"10.10.10.10"
      }
    ],
    "BOOTPROTO":"none",
    "DNSAddresses":[
      "9.9.9.9"
    ],
    "ROUTES":[
      {
        "METRIC":"9.9.9.9",
        "NETMASK":"9.9.9.9",
        "GATEWAY":"9.9.9.9",
        "ADDRESS":"9.9.9.9"
      }
    ]
  },
  "BASIC_INFO":{
    "UUID":"\"7241d3b4-2b15-49a8-994e-b788062a9b02\"",
    "MTU":"None",
    "HWADDR":"08:00:27:65:33:7F",
    "DEVICE":"enp0s3d",
    "TYPE":"Ethernet",
    "ONBOOT":"yes",
    "NAME":"enp0s3d"
  },
  "IPV6_INFO":{
    "IPV6INIT":"\"yes\"",
    "IPV6_PEERDNS":"\"yes\"",
    "IPV6Addresses":[
      {
        "PREFIX":"fe80::ff:fe23:9f4d",
        "IPADDR":"fe80::ff:fe23:9f4d"
      }
    ],
    "IPV6_DEFROUTE":"\"yes\"",
    "ROUTES":[
      {
        "METRIC":"fe80::ff:fe23:9f4d",
        "NETMASK":"fe80::ff:fe23:9f4d",
        "GATEWAY":"fe80::ff:fe23:9f4d",
        "ADDRESS":"fe80::ff:fe23:9f4d"
      }
    ],
    "IPV6_AUTOCONF":"no",
    "IPV6_FAILURE_FATAL":"\"no\"",
    "DHCPV6C":"yes",
    "IPV6_PEERROUTES":"\"yes\""
  }
}

And ifcfg file got below DNS Address:

DNS=9.9.9.9
DNS1=9.9.9.9
DNS2=10.10.10.10

**Comment by abhiramkulkarni** [comment]
In first update of DNS addresses, things work fine.

When we try to update second time, there is issue as we still need to deal with story of cleaning of existing attributes before doing update. 

Problem with DNS attributes is, 

if there is single DNS, then it will be stored as DNS,
if there are multple DNS, then it will be stored as DNS1,DNS2.

So here case was, first put operation is done with single DNS, followed by put operation of multiple DNS.

This will need investigation and handle as, case is not same for ipv4 and ipv6 again.

**Comment by pkulkark** [comment]
PUT operation on VLAN with DNS Address does not get added to ifcfg file even when it is the first put operation
curl command:
curl -k -u root -H "Content-Type: application/json" -H "Accept: application/json" -X PUT -d '{"BASIC_INFO" :{"DEVIE" : "en001530.0010"}, "IPV4_INFO" : {"IPV4INIT" : "yes", "BOOTPROTO" : "none", "DNS" : ["10.10.10.1"]}}' 'https://127.0.0.1:8001/plugins/ginger/network/cfginterfaces/en001530.0010'
Enter host password for user 'root':
{
  "IPV4_INFO":{
    "IPV4Addresses":[],
    "BOOTPROTO":"none",
    "IPV4INIT":"yes"
  },
  "BASIC_INFO":{
    "DEVICE":"en001530.0010",
    "MTU":"1500",
    "TYPE":"Vlan",
    "NAME":"en001530.0010",
    "VLANINFO":{
      "PHYSDEV":"enccw0.0.1530",
      "VLAN":"yes",
      "VLANID":"10"
    }
  },
  "IPV6_INFO":{
    "IPV6_AUTOCONF":"no",
    "IPV6Addresses":[
      {
        "PREFIX":"64",
        "IPADDR":"fe80::221:ccff:fe72:d02e"
      }
    ],
    "IPV6INIT":"yes"
  }
}

**Comment by abhiramkulkarni** [comment]
Fix is working in latest upstream code
