### ISSUE TITLE
Extend volume group fails

### ISSUE THREAD

**Issue by sureshab** [kimchi-project/ginger#127]
[root@zfwcec164 ~]# curl -k -u root -H "Content-Type: application/json" -H "Accept: application/json" -X POST -d '{"pv_path":["/dev/mapper/36005076802810d504800000000002f56", "/dev/mapper/36005076802810d504800000000002f5c"]}' 'https://localhost:8001/plugins/ginger/vgs/testvg2/extend'
Enter host password for user 'root':
{
  "reason":"The server encountered an unexpected condition which prevented it from fulfilling the request.",
  "code":"500 Internal Server Error"
}                                                                                                                                                      

pvdisplay output:
[root@zfwcec164 ~]# pvdisplay 
  --- Physical volume ---
  PV Name               /dev/mapper/36005076802810d504800000000002c1f
  VG Name               testvg
  PV Size               20.00 GiB / not usable 4.00 MiB
  Allocatable           yes 
  PE Size               4.00 MiB
  Total PE              5119
  Free PE               5119
  Allocated PE          0
  PV UUID               WYqVap-Ua7O-bx0R-1T7w-3pDG-AD53-cQfA4s
   
  --- Physical volume ---
  PV Name               /dev/mapper/36005076802810d504800000000002c20
  VG Name               testvg2
  PV Size               20.00 GiB / not usable 4.00 MiB
  Allocatable           yes 
  PE Size               4.00 MiB
  Total PE              5119
  Free PE               5114
  Allocated PE          5
  PV UUID               RPxI4U-KlU0-vK2g-OgSF-0vD2-H9zQ-r2uI0r
   
  "/dev/mapper/36005076802810d504800000000002ef2" is a new physical volume of "1.00 GiB"
  --- NEW Physical volume ---
  PV Name               /dev/mapper/36005076802810d504800000000002ef2
  VG Name               
  PV Size               1.00 GiB
  Allocatable           NO
  PE Size               0   
  Total PE              0
  Free PE               0
  Allocated PE          0
  PV UUID               rcnxbt-KQIS-lCbu-EbDy-K68N-K1QM-og4Wes
   
  "/dev/mapper/36005076802810d504800000000002f56" is a new physical volume of "1.00 GiB"
  --- NEW Physical volume ---
  PV Name               /dev/mapper/36005076802810d504800000000002f56
  VG Name               
  PV Size               1.00 GiB
  Allocatable           NO
  PE Size               0   
  Total PE              0
  Free PE               0
  Allocated PE          0
  PV UUID               vLYq1p-qLfz-bFZA-rl6W-UnD3-tKdo-sbJvY6
   
  "/dev/mapper/36005076802810d504800000000002f5c" is a new physical volume of "1.00 GiB"
  --- NEW Physical volume ---
  PV Name               /dev/mapper/36005076802810d504800000000002f5c
  VG Name               
  PV Size               1.00 GiB
  Allocatable           NO
  PE Size               0   
  Total PE              0
  Free PE               0
  Allocated PE          0
  PV UUID               seTFlF-Onfa-io0w-Kssa-auW6-BDZb-PfVLKM

vgdisplay output:
[root@zfwcec164 ~]# vgdisplay 
  --- Volume group ---
  VG Name               testvg
  System ID             
  Format                lvm2
  Metadata Areas        1
  Metadata Sequence No  1
  VG Access             read/write
  VG Status             resizable
  MAX LV                0
  Cur LV                0
  Open LV               0
  Max PV                0
  Cur PV                1
  Act PV                1
  VG Size               20.00 GiB
  PE Size               4.00 MiB
  Total PE              5119
  Alloc PE / Size       0 / 0   
  Free  PE / Size       5119 / 20.00 GiB
  VG UUID               36fYRI-qve5-vgqR-zEBf-CMXM-RUNh-dKQLEc
   
  --- Volume group ---
  VG Name               testvg2
  System ID             
  Format                lvm2
  Metadata Areas        1
  Metadata Sequence No  2
  VG Access             read/write
  VG Status             resizable
  MAX LV                0
  Cur LV                1
  Open LV               0
  Max PV                0
  Cur PV                1
  Act PV                1
  VG Size               20.00 GiB
  PE Size               4.00 MiB
  Total PE              5119
  Alloc PE / Size       5 / 20.00 MiB
  Free  PE / Size       5114 / 19.98 GiB
  VG UUID               h20dQg-YqLE-713j-1HhD-WDi2-Mu32-5PM5mr
   
[root@zfwcec164 ~]# 

wok error log :

[06/Jan/2016:08:59:18] HTTP Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cherrypy/_cprequest.py", line 656, in respond
    response.body = self.handler()
  File "/usr/lib/python2.7/site-packages/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/cherrypy/_cpdispatch.py", line 34, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/lib/python2.7/site-packages/wok/control/base.py", line 119, in wrapper
    action_result = action_fn(*model_args)
  File "/usr/lib/python2.7/site-packages/wok/plugins/ginger/models/vol_group.py", line 108, in extend
    utils._extend_vg(name, paths)
  File "/usr/lib/python2.7/site-packages/wok/plugins/ginger/models/utils.py", line 501, in _extend_vg
    cmd = ["vgextend", name] + [paths[i] for i in range(len(paths))]
TypeError: object of type 'NoneType' has no len()

[06/Jan/2016:08:59:18] HTTP Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cherrypy/_cprequest.py", line 656, in respond
    response.body = self.handler()
  File "/usr/lib/python2.7/site-packages/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/cherrypy/_cpdispatch.py", line 34, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/lib/python2.7/site-packages/wok/control/base.py", line 119, in wrapper
    action_result = action_fn(*model_args)
  File "/usr/lib/python2.7/site-packages/wok/plugins/ginger/models/vol_group.py", line 108, in extend
    utils._extend_vg(name, paths)
  File "/usr/lib/python2.7/site-packages/wok/plugins/ginger/models/utils.py", line 501, in _extend_vg
    cmd = ["vgextend", name] + [paths[i] for i in range(len(paths))]
TypeError: object of type 'NoneType' has no len()

**Comment by harche** [comment]
I will be working on this issue

**Comment by sureshab** [comment]
[root@zfwcec164 ~]# pvdisplay /dev/mapper/36005076802810d504800000000002f56
  "/dev/mapper/36005076802810d504800000000002f56" is a new physical volume of "1.00 GiB"
  --- NEW Physical volume ---
  PV Name               /dev/mapper/36005076802810d504800000000002f56
  VG Name               
  PV Size               1.00 GiB
  Allocatable           NO
  PE Size               0   
  Total PE              0
  Free PE               0
  Allocated PE          0
  PV UUID               vLYq1p-qLfz-bFZA-rl6W-UnD3-tKdo-sbJvY6

[root@zfwcec164 ~]# pvdisplay /dev/mapper/36005076802810d504800000000002f5c
  "/dev/mapper/36005076802810d504800000000002f5c" is a new physical volume of "1.00 GiB"
  --- NEW Physical volume ---
  PV Name               /dev/mapper/36005076802810d504800000000002f5c
  VG Name               
  PV Size               1.00 GiB
  Allocatable           NO
  PE Size               0   
  Total PE              0
  Free PE               0
  Allocated PE          0
  PV UUID               seTFlF-Onfa-io0w-Kssa-auW6-BDZb-PfVLKM
   
[root@zfwcec164 ~]# vgdisplay testvg3 
  --- Volume group ---
  VG Name               testvg3
  System ID             
  Format                lvm2
  Metadata Areas        1
  Metadata Sequence No  1
  VG Access             read/write
  VG Status             resizable
  MAX LV                0
  Cur LV                0
  Open LV               0
  Max PV                0
  Cur PV                1
  Act PV                1
  VG Size               1020.00 MiB
  PE Size               4.00 MiB
  Total PE              255
  Alloc PE / Size       0 / 0   
  Free  PE / Size       255 / 1020.00 MiB
  VG UUID               QM3L8h-1Eug-BUqe-sHXt-8YOL-V0uQ-OF60Ff


#####

Selecting volume group "testvg3" with "pv_paths" as ["/dev/mapper/36005076802810d504800000000002f56","invalid_pv","/dev/mapper/36005076802810d504800000000002f5c"]
######

[root@zfwcec164 ~]# curl -k -u root -H "Content-Type: application/json" -H "Accept: application/json" -X POST -d '{"pv_paths":["/dev/mapper/36005076802810d504800000000002f56","invalid_pv","/dev/mapper/36005076802810d504800000000002f5c"]}' 'https://localhost:8001/plugins/ginger/vgs/testvg3/extend'
Enter host password for user 'root':
{
  "reason":"GINVG00005E: Failed to extend VG",
  "code":"500 Internal Server Error"
} 

[root@zfwcec164 ~]# vgdisplay testvg3
  --- Volume group ---
  VG Name               testvg3
  System ID             
  Format                lvm2
  Metadata Areas        1
  Metadata Sequence No  1
  VG Access             read/write
  VG Status             resizable
  MAX LV                0
  Cur LV                0
  Open LV               0
  Max PV                0
  Cur PV                1
  Act PV                1
  VG Size               1020.00 MiB
  PE Size               4.00 MiB
  Total PE              255
  Alloc PE / Size       0 / 0   
  Free  PE / Size       255 / 1020.00 MiB
  VG UUID               QM3L8h-1Eug-BUqe-sHXt-8YOL-V0uQ-OF60Ff
   
[root@zfwcec164 ~]# pvdisplay /dev/mapper/36005076802810d504800000000002f56
  "/dev/mapper/36005076802810d504800000000002f56" is a new physical volume of "1.00 GiB"
  --- NEW Physical volume ---
  PV Name               /dev/mapper/36005076802810d504800000000002f56
  VG Name               
  PV Size               1.00 GiB
  Allocatable           NO
  PE Size               0   
  Total PE              0
  Free PE               0
  Allocated PE          0
  PV UUID               vLYq1p-qLfz-bFZA-rl6W-UnD3-tKdo-sbJvY6

[root@zfwcec164 ~]# pvdisplay /dev/mapper/36005076802810d504800000000002f5c
  "/dev/mapper/36005076802810d504800000000002f5c" is a new physical volume of "1.00 GiB"
  --- NEW Physical volume ---
  PV Name               /dev/mapper/36005076802810d504800000000002f5c
  VG Name               
  PV Size               1.00 GiB
  Allocatable           NO
  PE Size               0   
  Total PE              0
  Free PE               0
  Allocated PE          0
  PV UUID               seTFlF-Onfa-io0w-Kssa-auW6-BDZb-PfVLKM

in the above example, pv_paths is list of two valid and available pvs with one invalid_pv
API failed with 500 and None of the pvs are added to vg.
Is it how the api is expected to behave? or should it all add valid pvs in pv_paths and fail only invalid pvs?
Which is better approach?

**Comment by sureshab** [comment]
Observation for "reduce" action with valid and invalid pv_path combination:

[root@zfwcec164 ~]# vgdisplay testvg3 
  --- Volume group ---
  VG Name               testvg3
  System ID             
  Format                lvm2
  Metadata Areas        3
  Metadata Sequence No  3
  VG Access             read/write
  VG Status             resizable
  MAX LV                0
  Cur LV                0
  Open LV               0
  Max PV                0
  Cur PV                3
  Act PV                3
  VG Size               2.99 GiB
  PE Size               4.00 MiB
  Total PE              765
  Alloc PE / Size       0 / 0   
  Free  PE / Size       765 / 2.99 GiB
  VG UUID               QM3L8h-1Eug-BUqe-sHXt-8YOL-V0uQ-OF60Ff
   
[root@zfwcec164 ~]# pvdisplay 
  --- Physical volume ---
  PV Name               /dev/mapper/36005076802810d504800000000002c1f
  VG Name               testvg
  PV Size               20.00 GiB / not usable 4.00 MiB
  Allocatable           yes 
  PE Size               4.00 MiB
  Total PE              5119
  Free PE               2534
  Allocated PE          2585
  PV UUID               WYqVap-Ua7O-bx0R-1T7w-3pDG-AD53-cQfA4s
   
  --- Physical volume ---
  PV Name               /dev/mapper/36005076802810d504800000000002c20
  VG Name               testvg2
  PV Size               20.00 GiB / not usable 4.00 MiB
  Allocatable           yes 
  PE Size               4.00 MiB
  Total PE              5119
  Free PE               5114
  Allocated PE          5
  PV UUID               RPxI4U-KlU0-vK2g-OgSF-0vD2-H9zQ-r2uI0r
   
  --- Physical volume ---
  PV Name               /dev/mapper/36005076802810d504800000000002ef2
  VG Name               testvg3
  PV Size               1.00 GiB / not usable 4.00 MiB
  Allocatable           yes 
  PE Size               4.00 MiB
  Total PE              255
  Free PE               255
  Allocated PE          0
  PV UUID               rcnxbt-KQIS-lCbu-EbDy-K68N-K1QM-og4Wes
   
  --- Physical volume ---
  PV Name               /dev/mapper/36005076802810d504800000000002f56
  VG Name               testvg3
  PV Size               1.00 GiB / not usable 4.00 MiB
  Allocatable           yes 
  PE Size               4.00 MiB
  Total PE              255
  Free PE               255
  Allocated PE          0
  PV UUID               vLYq1p-qLfz-bFZA-rl6W-UnD3-tKdo-sbJvY6
   
  --- Physical volume ---
  PV Name               /dev/mapper/36005076802810d504800000000002f5c
  VG Name               testvg3
  PV Size               1.00 GiB / not usable 4.00 MiB
  Allocatable           yes 
  PE Size               4.00 MiB
  Total PE              255
  Free PE               255
  Allocated PE          0
  PV UUID               seTFlF-Onfa-io0w-Kssa-auW6-BDZb-PfVLKM
   
[root@zfwcec164 ~]#

=============================
volume group "testvg3" has 3 pvs - /dev/mapper/36005076802810d504800000000002ef2, /dev/mapper/36005076802810d504800000000002f56 and /dev/mapper/36005076802810d504800000000002f5c

"reduce" action with pv_paths=["/dev/mapper/36005076802810d504800000000002f56","invalid_pv","/dev/mapper/36005076802810d504800000000002f5c"]
=============================

[root@zfwcec164 ~]# curl -k -u root -H "Content-Type: application/json" -H "Accept: application/json" -X POST -d '{"pv_paths":["/dev/mapper/36005076802810d504800000000002f56","invalid_pv","/dev/mapper/36005076802810d504800000000002f5c"]}' 'https://localhost:8001/plugins/ginger/vgs/testvg3/reduce'
Enter host password for user 'root':
{
  "reason":"GINVG00006E: Failed to reduce VG",
  "code":"500 Internal Server Error"
} 

=======
After api call testvg3 is left with  only one pv, two other pvs were successfully removed.
=======
[root@zfwcec164 ~]# vgdisplay testvg3
  --- Volume group ---
  VG Name               testvg3
  System ID             
  Format                lvm2
  Metadata Areas        1
  Metadata Sequence No  5
  VG Access             read/write
  VG Status             resizable
  MAX LV                0
  Cur LV                0
  Open LV               0
  Max PV                0
  Cur PV                1
  Act PV                1
  VG Size               1020.00 MiB
  PE Size               4.00 MiB
  Total PE              255
  Alloc PE / Size       0 / 0   
  Free  PE / Size       255 / 1020.00 MiB
  VG UUID               QM3L8h-1Eug-BUqe-sHXt-8YOL-V0uQ-OF60Ff
   
[root@zfwcec164 ~]# pvdisplay
  --- Physical volume ---
  PV Name               /dev/mapper/36005076802810d504800000000002c1f
  VG Name               testvg
  PV Size               20.00 GiB / not usable 4.00 MiB
  Allocatable           yes
  PE Size               4.00 MiB
  Total PE              5119
  Free PE               2534
  Allocated PE          2585
  PV UUID               WYqVap-Ua7O-bx0R-1T7w-3pDG-AD53-cQfA4s
   
  --- Physical volume ---
  PV Name               /dev/mapper/36005076802810d504800000000002c20
  VG Name               testvg2
  PV Size               20.00 GiB / not usable 4.00 MiB
  Allocatable           yes
  PE Size               4.00 MiB
  Total PE              5119
  Free PE               5114
  Allocated PE          5
  PV UUID               RPxI4U-KlU0-vK2g-OgSF-0vD2-H9zQ-r2uI0r
   
  --- Physical volume ---
  PV Name               /dev/mapper/36005076802810d504800000000002ef2
  VG Name               testvg3
  PV Size               1.00 GiB / not usable 4.00 MiB
  Allocatable           yes
  PE Size               4.00 MiB
  Total PE              255
  Free PE               255
  Allocated PE          0
  PV UUID               rcnxbt-KQIS-lCbu-EbDy-K68N-K1QM-og4Wes
   
  "/dev/mapper/36005076802810d504800000000002f56" is a new physical volume of "1.00 GiB"
  --- NEW Physical volume ---
  PV Name               /dev/mapper/36005076802810d504800000000002f56
  VG Name               
  PV Size               1.00 GiB
  Allocatable           NO
  PE Size               0   
  Total PE              0
  Free PE               0
  Allocated PE          0
  PV UUID               vLYq1p-qLfz-bFZA-rl6W-UnD3-tKdo-sbJvY6
   
  "/dev/mapper/36005076802810d504800000000002f5c" is a new physical volume of "1.00 GiB"
  --- NEW Physical volume ---
  PV Name               /dev/mapper/36005076802810d504800000000002f5c
  VG Name               
  PV Size               1.00 GiB
  Allocatable           NO
  PE Size               0   
  Total PE              0
  Free PE               0
  Allocated PE          0
  PV UUID               seTFlF-Onfa-io0w-Kssa-auW6-BDZb-PfVLKM
   
[root@zfwcec164 ~]#

########################
So in case of "reduce" action with valid and invalid combination, it successfully removes all valid pv_paths,,
but in case of "extend" action with valid and invalid combination, it did not add any pv to vg.

Per my opinion we should have only one approach here...adding all valid pv_paths and failing invalid pv_paths would good idea.

Request "expert comments" :-)

**Comment by danielhb** [comment]
@sureshab is this issue still valid?

**Comment by sureshab** [comment]
we can close the issue
