### ISSUE TITLE
extend volume group with pv which is part of another vg - fails with 500

### ISSUE THREAD

**Issue by sureshab** [kimchi-project/ginger#128]
[root@zfwcec164 ~]# pvdisplay 
  --- Physical volume ---
  PV Name               /dev/mapper/36005076802810d504800000000002c1f
  VG Name               testvg
  PV Size               20.00 GiB / not usable 4.00 MiB
  Allocatable           yes 
  PE Size               4.00 MiB
  Total PE              5119
  Free PE               5119
  Allocated PE          0
  PV UUID               WYqVap-Ua7O-bx0R-1T7w-3pDG-AD53-cQfA4s
   
  --- Physical volume ---
  PV Name               /dev/mapper/36005076802810d504800000000002c20
  VG Name               testvg2
  PV Size               20.00 GiB / not usable 4.00 MiB
  Allocatable           yes 
  PE Size               4.00 MiB
  Total PE              5119
  Free PE               5114
  Allocated PE          5
  PV UUID               RPxI4U-KlU0-vK2g-OgSF-0vD2-H9zQ-r2uI0r

using /dev/mapper/36005076802810d504800000000002c1f to extend testvg2:

[root@zfwcec164 ~]# curl -k -u root -H "Content-Type: application/json" -H "Accept: application/json" -X POST -d '{"pv_paths":["/dev/mapper/36005076802810d504800000000002c1f"]}' 'https://localhost:8001/plugins/ginger/vgs/testvg2/extend'
Enter host password for user 'root':
{
  "reason":"GINVG00005E: Failed to extend VG",
  "code":"500 Internal Server Error"
} 

log:

rc: 5 error: File descriptor 3 (/var/log/wok/wok-access.log) leaked on vgextend invocation. Parent PID 7722: python2
File descriptor 4 (/var/log/wok/wok-error.log) leaked on vgextend invocation. Parent PID 7722: python2
File descriptor 5 (/var/log/wok/wok-access.log) leaked on vgextend invocation. Parent PID 7722: python2
File descriptor 6 (/var/log/wok/wok-error.log) leaked on vgextend invocation. Parent PID 7722: python2
  Physical volume '/dev/mapper/36005076802810d504800000000002c1f' is already in volume group 'testvg'
  Unable to add physical volume '/dev/mapper/36005076802810d504800000000002c1f' to volume group 'testvg2'.
 returned from cmd: vgextend testvg2 /dev/mapper/36005076802810d504800000000002c1f
rc: 5 error: File descriptor 3 (/var/log/wok/wok-access.log) leaked on vgextend invocation. Parent PID 7722: python2
File descriptor 4 (/var/log/wok/wok-error.log) leaked on vgextend invocation. Parent PID 7722: python2
File descriptor 5 (/var/log/wok/wok-access.log) leaked on vgextend invocation. Parent PID 7722: python2
File descriptor 6 (/var/log/wok/wok-error.log) leaked on vgextend invocation. Parent PID 7722: python2
  Physical volume '/dev/mapper/36005076802810d504800000000002c1f' is already in volume group 'testvg'
  Unable to add physical volume '/dev/mapper/36005076802810d504800000000002c1f' to volume group 'testvg2'.
 returned from cmd: vgextend testvg2 /dev/mapper/36005076802810d504800000000002c1f
GINVG00011E: vgextend command failed
GINVG00011E: vgextend command failed
failed to extend vg
failed to extend vg
GINVG00005E: Failed to extend VG
GINVG00005E: Failed to extend VG

**Comment by harche** [comment]
I will be working on this issue
