### ISSUE TITLE
Reduce Volume Group fails with 500 status code.

### ISSUE THREAD

**Issue by sureshab** [kimchi-project/ginger#129]
Use case 1:
VG which has only one pv.

[root@zfwcec164 ~]# vgdisplay testvg3 
  --- Volume group ---
  VG Name               testvg3
  System ID             
  Format                lvm2
  Metadata Areas        1
  Metadata Sequence No  1
  VG Access             read/write
  VG Status             resizable
  MAX LV                0
  Cur LV                0
  Open LV               0
  Max PV                0
  Cur PV                1
  Act PV                1
  VG Size               1020.00 MiB
  PE Size               4.00 MiB
  Total PE              255
  Alloc PE / Size       0 / 0   
  Free  PE / Size       255 / 1020.00 MiB
  VG UUID               QM3L8h-1Eug-BUqe-sHXt-8YOL-V0uQ-OF60Ff
   
[root@zfwcec164 ~]# pvdisplay /dev/mapper/36005076802810d504800000000002ef2 
  --- Physical volume ---
  PV Name               /dev/mapper/36005076802810d504800000000002ef2
  VG Name               testvg3
  PV Size               1.00 GiB / not usable 4.00 MiB
  Allocatable           yes 
  PE Size               4.00 MiB
  Total PE              255
  Free PE               255
  Allocated PE          0
  PV UUID               rcnxbt-KQIS-lCbu-EbDy-K68N-K1QM-og4Wes
   

[root@zfwcec164 ~]# curl -k -u root -H "Content-Type: application/json" -H "Accept: application/json" -X POST -d '{"pv_paths":["/dev/mapper/36005076802810d504800000000002ef2"]}' 'https://localhost:8001/plugins/ginger/vgs/testvg3/reduce'
Enter host password for user 'root':
{
  "reason":"GINVG00006E: Failed to reduce VG",
  "code":"500 Internal Server Error"
}  

log: 

rc: 5 error: File descriptor 3 (/var/log/wok/wok-access.log) leaked on vgreduce invocation. Parent PID 51163: python2
File descriptor 4 (/var/log/wok/wok-error.log) leaked on vgreduce invocation. Parent PID 51163: python2
File descriptor 5 (/var/log/wok/wok-access.log) leaked on vgreduce invocation. Parent PID 51163: python2
File descriptor 6 (/var/log/wok/wok-error.log) leaked on vgreduce invocation. Parent PID 51163: python2
  Can't remove final physical volume "/dev/mapper/36005076802810d504800000000002ef2" from volume group "testvg3"
 returned from cmd: vgreduce testvg3 /dev/mapper/36005076802810d504800000000002ef2
rc: 5 error: File descriptor 3 (/var/log/wok/wok-access.log) leaked on vgreduce invocation. Parent PID 51163: python2
File descriptor 4 (/var/log/wok/wok-error.log) leaked on vgreduce invocation. Parent PID 51163: python2
File descriptor 5 (/var/log/wok/wok-access.log) leaked on vgreduce invocation. Parent PID 51163: python2
File descriptor 6 (/var/log/wok/wok-error.log) leaked on vgreduce invocation. Parent PID 51163: python2
  Can't remove final physical volume "/dev/mapper/36005076802810d504800000000002ef2" from volume group "testvg3"
 returned from cmd: vgreduce testvg3 /dev/mapper/36005076802810d504800000000002ef2
GINVG00012E: vgreduce command failed
GINVG00012E: vgreduce command failed
failed to reduce vg
failed to reduce vg
GINVG00006E: Failed to reduce VG
GINVG00006E: Failed to reduce VG

**Comment by sureshab** [comment]
Use case 2:
Without pv_paths in curl command.

[root@zfwcec164 ~]# curl -k -u root -H "Content-Type: application/json" -H "Accept: application/json" -X POST -d '{}' 'https://localhost:8001/plugins/ginger/vgs/testvg3/reduce'
Enter host password for user 'root':
{
  "reason":"The server encountered an unexpected condition which prevented it from fulfilling the request.",
  "code":"500 Internal Server Error"
}                                                                                                                                                        

log:

[06/Jan/2016:11:43:13] HTTP Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cherrypy/_cprequest.py", line 656, in respond
    response.body = self.handler()
  File "/usr/lib/python2.7/site-packages/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/cherrypy/_cpdispatch.py", line 34, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/lib/python2.7/site-packages/wok/control/base.py", line 119, in wrapper
    action_result = action_fn(*model_args)
  File "/usr/lib/python2.7/site-packages/wok/plugins/ginger/models/vol_group.py", line 115, in reduce
    utils._reduce_vg(name, paths)
  File "/usr/lib/python2.7/site-packages/wok/plugins/ginger/models/utils.py", line 515, in _reduce_vg
    cmd = ["vgreduce", name] + [paths[i] for i in range(len(paths))]
TypeError: object of type 'NoneType' has no len()

[06/Jan/2016:11:43:13] HTTP Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cherrypy/_cprequest.py", line 656, in respond
    response.body = self.handler()
  File "/usr/lib/python2.7/site-packages/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/cherrypy/_cpdispatch.py", line 34, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/lib/python2.7/site-packages/wok/control/base.py", line 119, in wrapper
    action_result = action_fn(*model_args)
  File "/usr/lib/python2.7/site-packages/wok/plugins/ginger/models/vol_group.py", line 115, in reduce
    utils._reduce_vg(name, paths)
  File "/usr/lib/python2.7/site-packages/wok/plugins/ginger/models/utils.py", line 515, in _reduce_vg
    cmd = ["vgreduce", name] + [paths[i] for i in range(len(paths))]
TypeError: object of type 'NoneType' has no len()

**Comment by sureshab** [comment]
Not sure why File Descriptor error is logged. I have noticed it in couple of other issues also.

File descriptor 6 (/var/log/wok/wok-error.log) leaked on vgreduce invocation. Parent PID 51163: python2

**Comment by harche** [comment]
I will be working on this issue
