### ISSUE TITLE
NW: cfginterface GET not getting subchannel value on s390x machine

### ISSUE THREAD

**Issue by archu-s** [kimchi-project/ginger#131]
1) Added ifcfg file for the nwdevice using below curl command:

[root@zfwpc159 ginger]#curl -k -u root -H "Content-Type: application/json" -H "Accept: application/json" -X POST -d {} 'https://9.152.151.67:8001/plugins/gingers390x/nwdevices/0.0.1f10/configure'
Enter host password for user 'root':
{
  "status":"running",
  "message":"",
  "id":"29",
  "target_uri":"/plugins/gingers390x/nwdevices/0.0.1f10/configure"
[root@zfwpc159 ginger]# curl -k -u root:pass4root -H "Content-Type: application/json" -H "Accept: application/json" -X GET 'https://127.0.0.1:8001/plugins/gingers390x/tasks/29'
{
  "status":"finished",
  "message":"Successfully configured network device 0.0.1f10",
  "id":"29",
  "target_uri":"/plugins/gingers390x/nwdevices/0.0.1f10/configure"
}

2) GET for the above cfginterface, does not give subchannel values.

curl -k -u root -H "Content-Type: application/json" -H "Accept: application/json" -X GET 'https://9.152.151.67:8001/plugins/ginger/network/cfginterfaces/enccw0.0.1f10'
Enter host password for user 'root':
{
  "IPV4_INFO":{},
  "BASIC_INFO":{
    "DEVICE":"enccw0.0.1f10",
    "ONBOOT":"yes",
    "MTU":"1500"
  },
  "IPV6_INFO":{}
}

3) ifcfg file contains below values:

DEVICE=enccw0.0.1f10
ONBOOT=yes
NETTYPE=qeth
SUBCHANNELS=0.0.1f10,0.0.1f11,0.0.1f12

**Comment by abhiramkulkarni** [comment]
The architecture information is being got based on TYPE="Ethernet".

Since this information is not present in ifcfg file, its not able to get NETTYPE,  SUBCHANNEL.

Based on investigation, irrespective of TYPE, we should be able to get the information.

Hence the condition will be removed TYPE=Ethernet.

I will be handling this issue.

**Comment by danielhb** [comment]
Fix was pushed upstream. Let me know if it fixed this issue

**Comment by abhiramkulkarni** [comment]
Fix is working in latest upstream code
