### ISSUE TITLE
Swaps API returns code 500 when accessing invalid swap

### ISSUE THREAD

**Issue by sureshab** [kimchi-project/ginger#135]
[root@zfwcec164 ~]# curl -k -u root -H "Content-Type: application/json" -H "Accept: application/json" -X GET 'https://127.0.0.1:8001/plugins/ginger/swaps/invalid_swap'
Enter host password for user 'root':
{
  "reason":"GINSP00015E: Unable to get single swap device info. ",
  "code":"500 Internal Server Error"
}

**Comment by danielhb** [comment]
I'm solving this

**Comment by sureshab** [comment]
Delete operation also fails with 500,,,delete on fake swap device.
[root@zfwcec164 ~]# curl -k -u root -H "Content-Type: application/json" -H "Accept: application/json" -X DELETE 'https://127.0.0.1:8001/plugins/ginger/swaps/invalid'
Enter host password for user 'root':
{
  "reason":"GINSP00015E: Unable to get single swap device info. ",
  "code":"500 Internal Server Error"
}                                                                                                                                                        
I guess this will get fixed with the patch for GET.

**Comment by harche** [comment]
@danielhb This can be closed. The fix works fine.
