### ISSUE TITLE
Update README file

### ISSUE THREAD

**Issue by clnperez** [kimchi-project/ginger#14]
A few things to add:

1. Mention SEP
2. Getting Started Section
 <br> 2a. Include packages that need to be installed, and those that should be installed for certain components.
  <br> 2b. How to run from source with kimchi ($ ln -s /ginger/dir/path/ kimchi/plugins/ginger)

Anything else?

**Comment by danielhb** [comment]
This is related to https://github.com/kimchi-project/ginger/issues/21 . We need a proper documentation in the README and the Wiki page about:

- how to install from source (install dependencies, feature dependencies)
- how to run from source
- how to run after installing via tarball
- list of current features supported

**Comment by danielhb** [comment]
Readme file was updated in the 2.0 release

Thanks for reporting the issue, @clnperez !
