### ISSUE TITLE
NW : Feature to include vlan/bond in list of interfaces.

### ISSUE THREAD

**Issue by abhiramkulkarni** [kimchi-project/ginger#142]
Current implementation in get of /interfaces returns interface names ethtool.getdevices().

This is nothing but all active/deactive devices which are physical interfaces and active bond/vlan/bridge interfaces.

Now since this api is used in UI to list the interfaces, we will not be able to list bond/vlan interfaces which are inactive,eventhough ifcfg file is present after creating them.

User needs someway to activate/deactivate them.

In order to support this list/get of /interfaces will be modifed as below.
1)ethtool.getdevices + scan ifcfg files with TYPE=Bond/Vlan, and get the device names of those bond/vlan and add to list.
Note :- Currently we will not do any data validation of bond/vlan files.
2)ethtool.getdevices also lists devices that do not have ifcfg files. This we will not remove, as we can perform activate/deactivate operation on these devices. On trying of edit, UI will display message no persistent file.
Note :- Future we have to consider, how to handle edit of devices which do not have ifcfg file from out tool.
3)Lookup for bond/vlan devices which are not active will have empty information.
for ex :- ipaddr="",macaddr="",subnet=""

Please add any suggestions further in this issue.

**Comment by abhiramkulkarni** [comment]
Patch sent with subject [PATCH][Ginger]GET of interfaces to include inactibe Bond and Vlan interfaces.

Waiting for feedback.

**Comment by chandrureddy** [comment]
In the absence of data missing from "ip addr link show", I feel this will be much needed to at least list the created interfaces of type bond/vlan which are not activated yet.

For sure we need to dig deeper and fine tune these aspects.

**Comment by danielhb** [comment]
Patch was pushed upstream

Please verify and close this issue if fixed

**Comment by abhiramkulkarni** [comment]
The implemented feature is working as expected.

Since i raised the issue and sent the patch, someone else needs to verify before i close it?

**Comment by abhiramkulkarni** [comment]
Working as expected in latest upstreamed code
