### ISSUE TITLE
NW: creating VLAN over bond fails for slave interfaces with status 'unknown' in s390

### ISSUE THREAD

**Issue by pkulkark** [kimchi-project/ginger#144]
Some interfaces have status 'unknown' after ifup is executed on them.
When a bond interface is created with these interfaces as slaves, and a VLAN is created over this bond, it fails with the following message:
curl -k -u root -H "Content-Type: application/json" -H "Accept: application/json" -X POST -d '{"BASIC_INFO" : {"TYPE" : "Vlan", "VLANINFO" : {"PHYSDEV" : "bond0", "VLANID" : "10", "VLAN" : "yes"}}}' 'https://127.0.0.1:8001/plugins/ginger/network/cfginterfaces'
Enter host password for user 'root':
{
  "reason":"GINNET0047E: For vlan creation over bond, slaves has to be up",
  "code":"500 Internal Server Error"
}

**Comment by jay-katta** [comment]
Will be relaxing operstate value for "unknown"
Please assign this to me ...

**Comment by abhiramkulkarni** [comment]
Fix working in latest upstreamed code.
