### ISSUE TITLE
Generate default backup initially gives blank tar files

### ISSUE THREAD

**Issue by rajatgupta21** [kimchi-project/ginger#146]
click Administration→Configuration Backup→Action→Generate Default Backup
Immediately it generates records if we click we get blank tar file.

later if we click same link we are able to see the file.
![config_backup_6 1](https://cloud.githubusercontent.com/assets/511072/12196374/100dd83e-b624-11e5-93b6-0ef38e158e31.png)
![config_backup_6 2](https://cloud.githubusercontent.com/assets/511072/12196378/14e2bfb4-b624-11e5-8463-8d7cbf5db9b3.png)
![config_backup_6 3](https://cloud.githubusercontent.com/assets/511072/12196380/180375a8-b624-11e5-92f7-ad7a2113c4d4.png)
![config_backup_6 4](https://cloud.githubusercontent.com/assets/511072/12196381/1ae36120-b624-11e5-9ffd-01cedb92279b.png)

**Comment by danielhb** [comment]
A fix was deployed. Please close this issue if it's solved now.

Thanks
