### ISSUE TITLE
configuration backup remove giving error message

### ISSUE THREAD

**Issue by rajatgupta21** [kimchi-project/ginger#147]
Click Administration→Configuration Backup→Remove

1. Due to duplication of records post custom backup some of records giving error message : “WOKOBJST0001E: WOKOBJST0001E”
2. Error message appears as close able but gets auto close after few seconds it should display on the page constantly until user close the error message. 

![config_backup_remove_9 1](https://cloud.githubusercontent.com/assets/511072/12196612/0d1f79b4-b626-11e5-8c26-e3b93168c681.png)

**Comment by jrziviani** [comment]
Please, assign this bug to me.

**Comment by danielhb** [comment]
A fix was deployed. Please close this issue if it's solved now.

Thanks
