### ISSUE TITLE
New Custom Backup allows blank data and generate duplicate records

### ISSUE THREAD

**Issue by rajatgupta21** [kimchi-project/ginger#148]
Click Administration→Configuration Backup→New Custom Backup	

POP up allows us to generate back up even if we don't specify paths (included and excluded) and on screen multiple records gets generate

![config_custombackup_13 1](https://cloud.githubusercontent.com/assets/511072/12196969/d7aa332a-b628-11e5-9ae3-963ac7827fe8.png)

**Comment by jrziviani** [comment]
Please, assign this bug to me.

**Comment by danielhb** [comment]
A fix was deployed. Please close this issue if it's solved now.

Thanks
