### ISSUE TITLE
Duplicate records are generating in New custom Backup 

### ISSUE THREAD

**Issue by rajatgupta21** [kimchi-project/ginger#149]
Click Administration→Configuration Backup→New Custom Backup → Generate Backup	

Creates two or more records with same paths

![config_custombackup_13 1](https://cloud.githubusercontent.com/assets/511072/12197000/1f4ec2e0-b629-11e5-9f33-71348d95f95c.png)

**Comment by jrziviani** [comment]
Please, assign this bug to me.

**Comment by danielhb** [comment]
A fix was pushed upstream. Please verify it and close this issue if it's solved now.

Thanks
