### ISSUE TITLE
configuration backup records on click open and close multiple times

### ISSUE THREAD

**Issue by rajatgupta21** [kimchi-project/ginger#150]
Click Administration→Configuration Backup→New Custom Backup → Paths icons 	

click on path Down and up arrow it starts animation effect where it opens and close multiple times

**Comment by jrziviani** [comment]
Please, assign this bug to me.

**Comment by danielhb** [comment]
A fix was pushed upstream. Please verify it and close this issue if it's solved now.

Thanks
