### ISSUE TITLE
configuration backup delete giving error message

### ISSUE THREAD

**Issue by rajatgupta21** [kimchi-project/ginger#151]
Click Administration→Configuration Backup→New Custom Backup → Delete	

1. got error message WOKOBJST0001E: WOKOBJST0001E	
Possibly due to duplicate records generated while creating custom backup

2. Some of the records are not getting deleted as it shows the error message

3. Pop up message input fields should give one sample example what data needs to enter.

![config_backup_remove_17 1](https://cloud.githubusercontent.com/assets/511072/12197226/3b3e58f6-b62b-11e5-99ed-0cccac231abf.png)

**Comment by jrziviani** [comment]
Please, assign this bug to me.

**Comment by danielhb** [comment]
A fix was pushed upstream. Please verify it and close this issue if it's solved now.

Thanks
