### ISSUE TITLE
Adding Administrator user gives error message

### ISSUE THREAD

**Issue by rajatgupta21** [kimchi-project/ginger#152]
Click Administration→User Management→Add User	
1. While adding administrator users getting errors
2. While navigating from parent page to add user page it shows previous errors along with error CSS.
3. If any issue occurs while adding users then it deletes all users previously saved post re-login

![admin_user_23 1](https://cloud.githubusercontent.com/assets/511072/12204020/dd3d672e-b657-11e5-80bf-f024b7e31854.png)

**Comment by danielhb** [comment]
There were multiple fixes in this dialog. Can you please verify to see if this issue is happening yet?

**Comment by danielhb** [comment]
I really believe this issue is fixed. @jrziviani can you take a look into this when possible?

**Comment by jrziviani** [comment]
Yes, I'm able to create users, including administrator.

**Comment by danielhb** [comment]
Closing the issue. Feel free to reopen if you're still experiencing it
