### ISSUE TITLE
Not able to bring network UP

### ISSUE THREAD

**Issue by rajatgupta21** [kimchi-project/ginger#155]
1. Click Network→Network Configuration → UP	
       Select any network for example virbr0, try to bring it up it gives error message : Bring up interface virbr0 failed !

**Comment by danielhb** [comment]
I've just fixed a bunch of errors in the network UI. Please let me know if it fixed these issues you're reporting

**Comment by danielhb** [comment]
@rajatgupta21 please test it again. I believe this was fixed in current master.
