### ISSUE TITLE
Not able to bring network Down

### ISSUE THREAD

**Issue by rajatgupta21** [kimchi-project/ginger#156]
Click Network→Network Configuration → Down
Shows error : Bring down interface enccw0.0.3b00 failed !
some records are taking too long time almost more than 10 minutes
background page is still enable to edit

**Comment by danielhb** [comment]
@rajatgupta21 please test it again. I believe this was fixed in current master.

**Comment by chandrureddy** [comment]
Rajat, Please verify now if still this is the case.
I am sure this can be rejected.
