### ISSUE TITLE
Hide settings, vlan and bond options on Ubuntu and SuSe

### ISSUE THREAD

**Issue by chandrureddy** [kimchi-project/ginger#157]
Hide settings, vlan and bond options on Ubuntu and SuSe
At the moment cfginterface API implementation may not work for Ubuntu and SuSe as they are different in the way networking configurations made on Fedora/Redhat.

Once we have compatibility UI code we can enable them back for these distros.

**Comment by chandrureddy** [comment]
Will work on this.

**Comment by chandrureddy** [comment]
Daniel, patch been sent by Atreyee. So please assign the ticket to Atreyee.

**Comment by danielhb** [comment]
It was fixed. Thanks!
