### ISSUE TITLE
Unable to login with newly created kimchi user ,virt user or admin user

### ISSUE THREAD

**Issue by papusagar83** [kimchi-project/ginger#16]
When i try to login with created kimchi user,virt user or  admin user its throwing message that username and password is incorrect.

I am running kimchi-ginger   https://9.152.151.63:8001/#tabs/host "mozilla firefox ESR 31.8.0 ESR".

How to reproduce

1)Install and launch the kimchi.
2)Login with an admin user.(root).
3)Switch to administrator tab
4)Go to User management and create a kimchi user,virt user or admin user 
5)Logout from admin user root
6)Login with created kimchi user,virt user or admin user 

Actual behavior

1)Login fail with message "Username and password in incorrect."

Expected behavior

1)Login should be successful with created kimchi user,virt user or admin user.

Snaps

i) Created a kimchi user as "test"

![nuew_kimchi_user_test](https://cloud.githubusercontent.com/assets/13309902/8716021/73188e80-2ba8-11e5-8de0-a60d060eb9a3.PNG)

ii)Login fail with kimchi user "test"

![login_with_kimchi_user_test](https://cloud.githubusercontent.com/assets/13309902/8716034/89cc7c86-2ba8-11e5-8303-8b940f00a92d.PNG)

**Comment by danielhb** [comment]
I'll look into it ASAP

**Comment by danielhb** [comment]
The user is being created in the system but won't log in at all, even on linux shell. I'll investigate if there is a problem in the way ginger assigns the password for the created user

**Comment by danielhb** [comment]
The fix was sent for community review/approval. ETA to be publicly available is Monday 27th.

**Comment by danielhb** [comment]
A fix was committed in the latest upstream code. Please try again using latest ginger and see if the bug persists

Thanks
