### ISSUE TITLE
Page data and add option items are mismatch

### ISSUE THREAD

**Issue by rajatgupta21** [kimchi-project/ginger#160]
Click Network→Network Configuration → Add 	
Options says adding Bond, VLAN or Adapter but on the page couldn,t relate with any of the records or items

**Comment by danielhb** [comment]
@rajatgupta21 please test it again. The UI wasn't completed when you've tested it

**Comment by chandrureddy** [comment]
Rajat, Please verify now if still this is the case.
I am sure this can be rejected.
