### ISSUE TITLE
Missing "device_name" in /filesystems

### ISSUE THREAD

**Issue by sureshab** [kimchi-project/ginger#164]
API.md -

Resource: File System

URI: /plugins/ginger/filesystems/:mount_point

Methods:*

GET: Retrieve the full description of the mounted filesystem

use%: Percentage of the filesystem used
used: Amount of space used in filesystem
size: Total size of the filesystem
mounted_on: Mount point of the filesystem
avail : Total space available on the filesystem
device_name : Backing device name of the filesystem.
type : Filesystem type.

i guess device_name is replaced with filesystem in json --

[root@zfwcec164 gingers390x]# curl -k -u root -H "Content-Type: application/json" -H "Accept: application/json" -X GET 'https://localhost:8001/plugins/ginger/filesystems'
Enter host password for user 'root':
[
  {
    "use%":"16%",
    "used":"3.2G",
    "mounted_on":"/",
    "avail":"18G",
    "filesystem":"/dev/dasda1",
    "type":"ext3",
    "size":"23G"
  },
  {
    "use%":"0%",
    "used":"0",
    "mounted_on":"/dev",
    "avail":"1.9G",
    "filesystem":"devtmpfs",
    "type":"devtmpfs",
    "size":"1.9G"
  },
  {
    "use%":"1%",
    "used":"4.0K",
    "mounted_on":"/dev/shm",
    "avail":"1.9G",
    "filesystem":"tmpfs",
    "type":"tmpfs",
    "size":"1.9G"
  },
  {
    "use%":"2%",
    "used":"26M",
    "mounted_on":"/run",
    "avail":"1.9G",
    "filesystem":"tmpfs",
    "type":"tmpfs",
    "size":"1.9G"
  },
  {
    "use%":"0%",
    "used":"0",
    "mounted_on":"/sys/fs/cgroup",
    "avail":"1.9G",
    "filesystem":"tmpfs",
    "type":"tmpfs",
    "size":"1.9G"
  }
]

**Comment by pkulkark** [comment]
I will be sending a patch for this

**Comment by pkulkark** [comment]
This issue can be closed now that the API.md doc is updated
