### ISSUE TITLE
mount file system fails

### ISSUE THREAD

**Issue by sureshab** [kimchi-project/ginger#165]
valid block device and invalid mount point
[root@zfwcec164 ~]# curl -k -u root -H "Content-Type: application/json" -H "Accept: application/json" -X POST -d '{"type":"local","dev_name":"/dev/dasdc2","mount_point":"invalid"}' 'https://localhost:8001/plugins/ginger/filesystems'
Enter host password for user 'root':
{
  "reason":"GINFS00009E: Require block dev to mount a filesystem",
  "code":"400 Bad Request"
}                                                                                                                                                      

error message is not appropriate.

**Comment by sureshab** [comment]
when block device which is not formatted is used to  mount 

[root@zfwcec164 ~]# curl -k -u root -H "Content-Type: application/json" -H "Accept: application/json" -X POST -d '{"type":"local","dev_name":"/dev/dasdc","mount_point":"/root/mount_pt"}' 'https://localhost:8001/plugins/ginger/filesystems'
Enter host password for user 'root':
{
  "reason":"GINFS00009E: Require block dev to mount a filesystem",
  "code":"400 Bad Request"
}   

error message is not appropriate

**Comment by sureshab** [comment]
[root@zfwcec164 ~]# df -hT
Filesystem             Type      Size  Used Avail Use% Mounted on
/dev/dasda1            ext3       23G  3.2G   18G  16% /
devtmpfs               devtmpfs  1.9G     0  1.9G   0% /dev
tmpfs                  tmpfs     1.9G  4.0K  1.9G   1% /dev/shm
tmpfs                  tmpfs     1.9G   26M  1.9G   2% /run
tmpfs                  tmpfs     1.9G     0  1.9G   0% /sys/fs/cgroup
/dev/dasdc2            ext4      4.7G   20M  4.5G   1% /root/mount_dev
localhost:/var/ftp/nfs nfs4       23G  3.2G   18G  16% /root/dev_mount

using another block device to mount,,but mount point already has another block device mounted

[root@zfwcec164 ~]# curl -k -u root -H "Content-Type: application/json" -H "Accept: application/json" -X POST -d '{"type":"local","blk_dev":"/dev/dasdc1","mount_point":"/root/mount_dev"}' 'https://localhost:8001/plugins/ginger/filesystems'
Enter host password for user 'root':
{
  "use%":"1%",
  "used":"416K",
  "mounted_on":"/root/mount_dev",
  "avail":"443M",
  "filesystem":"/dev/dasdc1",
  "type":"ext3",
  "size":"469M"
}[root@zfwcec164 ~]# 
[root@zfwcec164 ~]# df -hT
Filesystem             Type      Size  Used Avail Use% Mounted on
/dev/dasda1            ext3       23G  3.2G   18G  16% /
devtmpfs               devtmpfs  1.9G     0  1.9G   0% /dev
tmpfs                  tmpfs     1.9G  4.0K  1.9G   1% /dev/shm
tmpfs                  tmpfs     1.9G   26M  1.9G   2% /run
tmpfs                  tmpfs     1.9G     0  1.9G   0% /sys/fs/cgroup
/dev/dasdc1            ext3      469M  416K  443M   1% /root/mount_dev
localhost:/var/ftp/nfs nfs4       23G  3.2G   18G  16% /root/dev_mount
[root@zfwcec164 ~]# 

api removes the previously mounted block device and mounts new device..should it throw error? is it the expected behavior?

**Comment by pkulkark** [comment]
I will be sending a patch for this.

P.S the last behavior is expected. Explanation given in issue 167.
