### ISSUE TITLE
NW: PUT operation with BOOTPROTO as 'none' and no IPV4 addresses given does not raise any exception

### ISSUE THREAD

**Issue by pkulkark** [kimchi-project/ginger#169]
When PUT operation is performed on /plugins/ginger/cfginterfaces/<interfacename> with BOOTPROTO option as 'none', it is required to provide the IPV4 addresses. But the curl command does not raise any exception when IPV4 Addresses are not provided.

curl -k -u root -H "Content-Type: application/json" -H "Accept: application/json" -X PUT -d '{"BASIC_INFO" :{"DEVICE" : "en001530.0010"}, "IPV4_INFO" : {"IPV4INIT" : "yes", "BOOTPROTO" : "none"}}' 'https://127.0.0.1:8001/plugins/ginger/network/cfginterfaces/en001530.0010'
Enter host password for user 'root':
{
  "IPV4_INFO":{
    "IPV4Addresses":[],
    "BOOTPROTO":"none",
    "IPV4INIT":"yes"
  },
  "BASIC_INFO":{
    "DEVICE":"en001530.0010",
    "MTU":"1500",
    "TYPE":"Vlan",
    "NAME":"en001530.0010",
    "VLANINFO":{
      "PHYSDEV":"enccw0.0.1530",
      "VLAN":"yes",
      "VLANID":"10"
    }
  },
  "IPV6_INFO":{}
}

**Comment by danielhb** [comment]
I suppose the behavior is the same with an IPv6 address. I mean, if a IPv6 address is given but no IPv4 should it raise an error?

**Comment by mesmriti** [comment]
I will be working on this issue.
To address your concern , Yes the behavior remains same for the IPv6 address as well wherein the error should be raised if no IPv6 addresses provided when BOOTPROTO is none. The same is handled already in the code for Ipv6 and I will be working on the IPv4 addresses.

**Comment by abhiramkulkarni** [comment]
Working in latest upstreamed code!!
