### ISSUE TITLE
Mock Tests for Ginger-WOK branch

### ISSUE THREAD

**Issue by pkulkark** [kimchi-project/ginger#17]
There are no mock tests created for ginger-WOK branch as found in master branch. 
I am working on adding them to ginger-WOK, but I noticed the following:
- The test cases in the master branch call utils defined in models. These have been modified in WOK branch. 
Should the test cases be modified accordingly for WOK branch to use the changed utils?

**Comment by pkulkark** [comment]
I can take up this issue. Please assign to me.

**Comment by danielhb** [comment]
Consider it assigned to you 

Github does not allow assigning issues unless you're marked as a contributor or something. I'll look into it

**Comment by danielhb** [comment]
To assign the bug you must accept the status of collaborator of the project

The fix was pushed upstream. I'll assign it to you before closing it

Thanks

**Comment by danielhb** [comment]
Issue was fixed by pkulkark and is available upstream in ginger-wok branch

Thanks
