### ISSUE TITLE
GET /plugins/ginger/dasddevs fails with 500

### ISSUE THREAD

**Issue by sureshab** [kimchi-project/ginger#170]
Platform: x86, OS: Fedora 21

[suresh@localhost ginger]$ curl -k -u root -H "Content-Type: application/json" -H "Accept: application/json" -X GET 'https://localhost:8001/plugins/ginger/dasddevs'
Enter host password for user 'root':
{
  "reason":"GINDASD0005E: Failed to retrieve list of DASD devices",
  "code":"500 Internal Server Error"
}

log:

lsdasd -l failed
lsdasd -l failed
GINDASD0001E: Error in executing 'lsdasd -l' command
GINDASD0001E: Error in executing 'lsdasd -l' command
Fetching list of dasd devices failed
Fetching list of dasd devices failed
GINDASD0005E: Failed to retrieve list of DASD devices
GINDASD0005E: Failed to retrieve list of DASD devices

**Comment by danielhb** [comment]
The 500 internal error is correct. The problem is that the host system does not have the 'lsdasd' command. This is the same error that occurs in my F23 machine that does not have the command as well.

The 'is_feature_available' call is probably missing some conditions. I'll have a look.

**Comment by danielhb** [comment]
Here's the output of the capabilities API

```
$ curl -k -u root -H "Content-Type: application/json" -H "Accept: application/json" -X GET 'https://localhost:8001/plugins/ginger/capabilities'
Enter host password for user 'root':
{
  "StorageDevs":true,
  "DASDPartitions":false,
  "PowerProfiles":true,
  "Swaps":true,
  "Cfginterfaces":true,
  "Sep":false,
  "LogicalVolumes":true,
  "SanAdapters":true,
  "VolumeGroups":true,
  "Firmware":false,
  "FirmwareProgress":true,
  "FileSystems":true,
  "SysModules":true,
  "PhysicalVolumes":true,
  "DASDdevs":false,
  "Users":true,
  "Sensors":true,
  "Partitions":true,
  "Backup":true,
  "Network":true
}
```

And the output of the dasd API:

```
[danielhb@arthas ginger]$ curl -k -u root -H "Content-Type: application/json" -H "Accept: application/json" -X GET 'https://localhost:8001/plugins/ginger/dasddevs'
Enter host password for user 'root':
{
  "reason":"GINDASD0005E: Failed to retrieve list of DASD devices",
  "code":"500 Internal Server Error"
}                                                                                                        
```

As you can see, 500 internal error is expected and makes sense in this case. If it's the same in your host (you didn't mention the arch you're running) then this is not a bug.

At any case, I'll enhance the availability of the dasddevs by considering the existence or not of the 'lsdasd'  command.

**Comment by sureshab** [comment]
Architecture is x86,,, i am getting same output with 500 return code.

**Comment by danielhb** [comment]
I've sent a patch to improve the availability check, but there's not much else we can do about it. If you test every API Ginger has in a x86 host, not considering if said API is available at that time or not, you'll see a lot of those 500 errors.

The way to avoid using an API that isn't supposed to be used at a particular time is to check the output of the capabilities API and, if it's marked to False, avoid using it. This is how the Ginger UI can hide the Power Management frame in hosts that don't have the 'tuned-adm' package, for example. The API will be accessible but it will not be functional. I know this is not a perfect design, we can definitely improve the error messages (there's a bug for that), but at this moment this is how it works.

Let me know if you have any doubts or comments about this. If not, please close the issue.

Daniel

**Comment by sureshab** [comment]
I agree with you,,
