### ISSUE TITLE
NW UI: subchannels is not getting displayed in network setting panel

### ISSUE THREAD

**Issue by archu-s** [kimchi-project/ginger#171]
subchannels is not getting displayed in network setting panel, even if RESTful API returns SUBCHANNELS.
Currently UI implementation, reads "SUBCHANNEL" from JSON response instead of "SUBCHANNEL"

**Comment by danielhb** [comment]
I can't test it because I don't have access to a s390x

Please @archu-s see if it's fixed and close the bug

**Comment by abhiramkulkarni** [comment]
Fix is working in latest upstream.
