### ISSUE TITLE
bringing interface up gave an error, UI didn't forward it to the user

### ISSUE THREAD

**Issue by danielhb** [kimchi-project/ginger#179]
Tried to bring a random interface up. After pressing "Up" there's a loading icon and the process appeared to be successful, but the interface wasn't brought up (icon didn't turn green).

Seeing the backend log I saw the following error:

```
Bring up an interface enp0s25
Successfully brought up the interface enp0s25
Activating an interface enp0s25
rc: 4 error: Error: Connection activation failed: No suitable device found for this connection.
 returned from cmd: ifup enp0s25
Unable to activate the interface on enp0s25, Error: Connection activation failed: No suitable device found for this connection.

GINNET0016E: Unable to activate the interface on 'enp0s25', 'Error: Connection activation failed: No suitable device found for this connection.
```

This error needs to be forward by the UI so the user is made aware that the process failed.

**Comment by danielhb** [comment]
Update: an error is being shown in the UI but I couldn't notice it because it appeared in the top of the tab and the screen was scrolled down.

The error wasn't very helpful too:

![image](https://cloud.githubusercontent.com/assets/866780/12321901/e0bee780-ba97-11e5-956b-a7041330c591.png)

I believe there are 2 things to be done here:

- if an error occurs, the page must be automatically scrolled up to see the error message 

- the error message must be way more informative than that.

**Comment by abhiramkulkarni** [comment]
I second with Daniel here. Same issues i had with deactivate as well,

1)Tried to deactivate the interface which does not have ifcfg file. Deactivate fails with error code, but details errors is not shown in UI.
10: wc0: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1348 qdisc pfifo_fast state UNKNOWN group default qlen 500
    link/none 
    inet 9.79.213.27/20 scope global wc0
       valid_lft forever preferred_lft forever
GINNET0017E: Unable to deactivate the interface on 'wc0', 'usage: ifdown <configuration>
2)Tried to activate the VLAN interface, detail error message not displayed in UI.
GINNET0016E: Unable to activate the interface on 'eth1.0001', 'Error: Connection activation failed: Failed to determine connection's virtual interface name
