### ISSUE TITLE
Overlapping pop up windows

### ISSUE THREAD

**Issue by sureshab** [kimchi-project/ginger#18]
Environment: x86
Operating system: Fedora
Browser: Firefox
Steps performed:
1. Installed WOK (https://github.com/kimchi-project/kimchi/tree/wok)
2. Installed GINGER_WOK (https://github.com/kimchi-project/ginger/tree/ginger_wok)
3. Started wokd daemon
4. From browser launched https://127.0.0.1:8001
5. Login screen displayed
6. Entered userid and password
![screenshot from 2015-08-11 13 44 45](https://cloud.githubusercontent.com/assets/12499230/9193207/633de4f6-402f-11e5-82c3-e14ae13708c2.png)

In the "User Management" section, click on "+" to add user. Add user pop up window will be displayed. Fill in the details, (i gave different passwords in "Password" and "Confirm Password" option) and click on submit.

![screenshot from 2015-08-11 13 50 46](https://cloud.githubusercontent.com/assets/12499230/9193319/0f69521a-4030-11e5-9da2-b89e6e4a00d3.png)

after clicking on "Submit" i get below display 

![screenshot from 2015-08-11 13 52 23](https://cloud.githubusercontent.com/assets/12499230/9193337/396a82aa-4030-11e5-940e-084aed4c8b25.png)

"Warning" window and "Add User" window are overlapped and can't see warning message.

**Comment by danielhb** [comment]
I'm closing this issue because the UI changes were massive from Aug 13 up to today. Feel free to reopen it if it happens in the current UI code.
