### ISSUE TITLE
NW: Multiple default DNS edit.

### ISSUE THREAD

**Issue by abhiramkulkarni** [kimchi-project/ginger#180]
Multiple DNS ip is being allowed to enter in UI. 
But when we apply, in /etc/resolv.conf only one that is being edited gets updated in /etc/resolv.conf
and deletes all other entries.

Need to investigate.

**Comment by sureshab** [comment]
i will be fixing this issue

**Comment by abhiramkulkarni** [comment]
This is UI bug.

**Comment by sureshab** [comment]
@abhiramkulkarni this is backend bug,
right now backend code deletes entire content of /etc/resolv.conf file contents whenever there is PUT operation to add new name server

you can have a look at model - network.py file _set_nameservers() method which is called by update() method.

_set_nameservers() opens /etc/resolve.conf in 'w' mode which implies that it deletes file contents.

**Comment by danielhb** [comment]
I'll leave it just as 'Bug' without specifying if it's UI or backend. @sureshab will fix it anyway ;)

**Comment by sureshab** [comment]
@danielhb :+1:

**Comment by chandrureddy** [comment]
So from UI point of view I am thinking of converting  the "DNS IP Address" into editable boot grid as thisk section has lot of issues in adding/updating/removing a DNS IP Address similar to IPv4/IPv6 DNS sections..

I am going to look into this.

If any body have different opinion let me know !!!

**Comment by sureshab** [comment]
@chandrureddy from my point of view, it is okay to go ahead with editable bootgrid if it makes life easy,,, also other sections of network tab are using bootgrid so we have uniform implementation in network tab.

**Comment by chandrureddy** [comment]
Assign this to me ....

**Comment by abhiramkulkarni** [comment]
Working in latest upstreamed code
