### ISSUE TITLE
NW: Removal of libvirt from ginger.

### ISSUE THREAD

**Issue by abhiramkulkarni** [kimchi-project/ginger#181]
Currently with the UI flexibilites, looks like only default gateway is using libvirt.
Libvirt usage need to be removed and updated with alternative for gateway.

**Comment by danielhb** [comment]
As long as the alternative covers Fedora/Ubuntu/Suse I approve

I believe default gateway can be set via iproute2 commands in the OSes we don't support the cfginterfaces API. But we need to verify to be certain

**Comment by danielhb** [comment]
There's a couple of bugs about removal (or not) of libvirt: #7 #45 

#45  is the most recent one and I've engaged with some thoughts there about libvirt and network support to other OSes (aside from Fedora/RHEL)

**Comment by danielhb** [comment]
libvirt is not a Ginger dependency anymore.
