### ISSUE TITLE
NW: Routes and DNS can be applied in automatic mode also. It needs to be enabled in UI.

### ISSUE THREAD

**Issue by abhiramkulkarni** [kimchi-project/ginger#186]
When mode is automatic in ipv4/ipv6 for all the network settings page , DNS and ROUTES should be allowed to provide input.

![screenshot from 2016-01-20 12 51 13](https://cloud.githubusercontent.com/assets/12495213/12442254/85ef5aec-bf74-11e5-8fd0-a887ff7849d4.png)

**Comment by chandrureddy** [comment]
Please assign this ticket to me.

**Comment by abhiramkulkarni** [comment]
Working in latest upstreamed code
