### ISSUE TITLE
Uninstall is not removing controls and models folder in already installed ginger

### ISSUE THREAD

**Issue by abhiramkulkarni** [kimchi-project/ginger#195]
I am aware that controls is changed to control and models to model.

Do we need to take care of removing controls and models folder when we are reinstalling ginger?

bash-4.3# pwd
/usr/lib/python2.7/site-packages/wok/plugins/ginger
bash-4.3# ls -lrt
total 108
drwxrwxr-x. 2 root root  4096 Jan 25 19:44 controls
drwxrwxr-x. 2 root root  4096 Jan 29 12:12 control
drwxrwxr-x. 2 root root  4096 Jan 29 12:41 model
drwxrwxr-x. 2 root root  4096 Jan 29 12:52 models
bash-4.3#

**Comment by danielhb** [comment]
You mean in the RPM spec file? Yeah, we'll probably need to take care of that.  Perhaps with a postun rule or other RPM macro

**Comment by abhiramkulkarni** [comment]
Right @danielhb , i am unaware where the fix goes, while debugging other issue i end up editing files in models folder and restart wokd.. it did not reflect then when i checked the wokd structure, it had both (model and models). So i raised this issue

**Comment by danielhb** [comment]
Yeah, definitely it's an issue. Even if there's no harm in having these extra dirs there.

I'll look into it.

**Comment by abhiramkulkarni** [comment]
Agree, definitely we can leave with bug :)

**Comment by danielhb** [comment]
Solved by d7f4833 for Ginger version 2.3 and beyond

The workaround for the problem of 'models' and 'controls' dir being left in the update is to simply remove the Ginger package, then install the newer version. This is more sane than putting a scriptlet just to clean them up. Refer to the d7f4833 commit msg for more info.
