### ISSUE TITLE
create OVS bridge feature

### ISSUE THREAD

**Issue by danielhb** [kimchi-project/ginger#196]
This issue tracks any progress (or lack of) in implementing the regular management (create, list and delete) of OVS bridges in Ginger.

@chandrureddy do you have any news in this effort? Anyone has done anything in this direction? If not I'll get it started with the backend.

**Comment by chandrureddy** [comment]
Hi Daniel,

So far I was looking into the use cases that we can cover in order to 
support the OVS bridge. I will be sharing the use cases soon in detail.

Otherwise coding not yet started so far in this area. Let us together 
start coding, if you have some bandwidth to contribute in this area !!!

Thanks and Regards
Chandra

**Comment by danielhb** [comment]
Let's do it! 

What I know so far: OVS bridges relies on the 'openvswitch'  package and apparently can be setup only with specific package commands such as ```ovs-vsctl add-br``` to add a bridge. This is good news: it means that we can support this feature across all distros that supports this package, and I believe fedora/ubuntu/opensuse already does.

I haven't thought much about the use cases, but I believe it will be something like

- create / delete / list OVS bridges
- add / remove / list interfaces that belongs to an OVS bridge
- add / remove / list tags of an OVS bridge

I don't know if we need more, perhaps we don't need all these use cases .... this is something we'll need to decide before proceeding.

**Comment by danielhb** [comment]
In time: I've found an interesting OVS cookbook:

http://openvswitch.org/support/config-cookbooks/vlan-configuration-cookbook/

Of course that this one talks a lot about VMs and this is not our scope here, but we can see some use cases going on.

**Comment by danielhb** [comment]
Feature was successfully added!
