### ISSUE TITLE
ginger wok API exceptions referring to kimchi errors

### ISSUE THREAD

**Issue by sureshab** [kimchi-project/ginger#20]
Installed wok and ginger_wok. Started wokd service.
Sample curl output which refers to Kimchi error code and failed to load corresponding  reason.

[suresh@localhost wok]$ curl -k -u root -H "Content-Type: application/json" -H "Accept: application/json" -X POST -d '{"name":"virbr3","editable":true,"ipaddr":"192.168.130.14","netmask":"255.255.255.192"}' https://127.0.0.1:8001/plugins/ginger/network/interfaces
Enter host password for user 'root':
{
  "reason":"KCHAPI0005E: KCHAPI0005E",
  "code":"405 Method Not Allowed"
}

**Comment by danielhb** [comment]
I'm not sure if the error codes were translated in wok. I'll have a look into this when I have the chance

**Comment by danielhb** [comment]
This bug is too old and probably isn't applicable anymore. Feel free to create a new issue if you see it happening again
