### ISSUE TITLE
Wok failed to start due Ginger dependency on libvirt

### ISSUE THREAD

**Issue by alinefm** [kimchi-project/ginger#202]
Originally reported at https://github.com/kimchi-project/wok/issues/31

Wokd fails to start on system boot, because of libvirtd not started before wokd.

Below is the logs from /var/log/messages:

Feb 1 18:36:32 zs95k4 kernel: end_request: I/O error, dev dasdd, sector 4206976
Feb 1 18:36:32 zs95k4 wokd: libvirt: XML-RPC error : Failed to connect socket to '/var/run/libvirt/libvirt-sock': No such file or directory
Feb 1 18:36:32 zs95k4 wokd: Traceback (most recent call last):
Feb 1 18:36:32 zs95k4 wokd: File "/usr/bin/wokd", line 97, in
Feb 1 18:36:32 zs95k4 wokd: sys.exit(main(sys.argv[1:]))
Feb 1 18:36:32 zs95k4 wokd: File "/usr/bin/wokd", line 94, in main
Feb 1 18:36:32 zs95k4 wokd: wok.server.main(options)
Feb 1 18:36:32 zs95k4 wokd: File "/usr/lib/python2.7/site-packages/wok/server.py", line 205, in main
Feb 1 18:36:32 zs95k4 wokd: srv = Server(options)
Feb 1 18:36:32 zs95k4 wokd: File "/usr/lib/python2.7/site-packages/wok/server.py", line 137, in init
Feb 1 18:36:32 zs95k4 wokd: self.load_plugins(options)
Feb 1 18:36:32 zs95k4 wokd: File "/usr/lib/python2.7/site-packages/wok/server.py", line 158, in load_plugins
Feb 1 18:36:32 zs95k4 wokd: plugin_app = import_class(plugin_class)(options)
Feb 1 18:36:32 zs95k4 wokd: File "/usr/lib/python2.7/site-packages/wok/utils.py", line 126, in import_class
Feb 1 18:36:32 zs95k4 wokd: mod = import_module(module_name, class_name)
Feb 1 18:36:32 zs95k4 wokd: File "/usr/lib/python2.7/site-packages/wok/utils.py", line 136, in import_module
Feb 1 18:36:32 zs95k4 wokd: return __import(module_name, globals(), locals(), [class_name])
Feb 1 18:36:32 zs95k4 wokd: File "/usr/lib/python2.7/site-packages/wok/plugins/ginger/init.py", line 20, in
Feb 1 18:36:32 zs95k4 wokd: from ginger import Ginger
Feb 1 18:36:32 zs95k4 wokd: File "/usr/lib/python2.7/site-packages/wok/plugins/ginger/ginger.py", line 34, in
Feb 1 18:36:32 zs95k4 wokd: from models import GingerModel
Feb 1 18:36:32 zs95k4 wokd: File "/usr/lib/python2.7/site-packages/wok/plugins/ginger/models/init.py", line 21, in
Feb 1 18:36:32 zs95k4 wokd: from model import GingerModel
Feb 1 18:36:32 zs95k4 wokd: File "/usr/lib/python2.7/site-packages/wok/plugins/ginger/models/model.py", line 24, in
Feb 1 18:36:32 zs95k4 wokd: from cfginterfaces import CfginterfaceModel, CfginterfacesModel
Feb 1 18:36:32 zs95k4 wokd: File "/usr/lib/python2.7/site-packages/wok/plugins/ginger/models/cfginterfaces.py", line 32, in
Feb 1 18:36:32 zs95k4 wokd: from interfaces import InterfaceModel
Feb 1 18:36:32 zs95k4 wokd: File "/usr/lib/python2.7/site-packages/wok/plugins/ginger/models/interfaces.py", line 52, in
Feb 1 18:36:32 zs95k4 wokd: class InterfaceModel(object):
Feb 1 18:36:32 zs95k4 wokd: File "/usr/lib/python2.7/site-packages/wok/plugins/ginger/models/interfaces.py", line 54, in InterfaceModel
Feb 1 18:36:32 zs95k4 wokd: _conn = libvirt.open("qemu:///system")
Feb 1 18:36:32 zs95k4 wokd: File "/usr/lib64/python2.7/site-packages/libvirt.py", line 255, in open

**Comment by danielhb** [comment]
@pvital are you going to work in this?

**Comment by pvital** [comment]
Not yet.

**Comment by chandrureddy** [comment]
Hi Daniel, Please assign this ticket to me. I will be fixing and sending a patch.

**Comment by danielhb** [comment]
Libvirt is not a dependency of Ginger anymore. CLosing
