### ISSUE TITLE
Ginger is allowing to remove own user profile

### ISSUE THREAD

**Issue by jay-katta** [kimchi-project/ginger#206]
Steps to reproduce-
1. Create new user with admin profile under user management
2. Log out and log in with newly created user
3. Ginger is allowing to remove newly added user while logged in with same user credentials

Note: I think we should disable removing the own user profile from user management

**Comment by danielhb** [comment]
I agree that this would be the easier solution, but I don't think we need to prohibit the user from deleting its own logged account *if*:

- the user get disconnected from WoK the moment after the account is deleted
- the user is not 'root'

I think we can discuss this further in the ML to see if we get more ideas
