### ISSUE TITLE
Add basic install documentation in the Wiki page

### ISSUE THREAD

**Issue by jdgregson** [kimchi-project/ginger#21]
I installed the Ginger 1.3 debian package after updating to Kimchi 1.5.0 and installing python-libuser. I had to install Ginger with "dpkg -i --ignore-depends=kimchi ginger-1.3.0-0.noarch.deb" because Kimchi was installed from source on my system, therefore causing the Ginger installation fail due to the "unmet" dependency. 

Anyway, now that it's installed I go to Kimchi and see absolutely nothing changed. I have restarted Kimchi twice. There is no indication that any plugins were installed anywhere. Is there another step? A URL I should know? Time to read the instructions, right? So I come here to figure out what I'm even supposed to be looking for and see, again, absolutely nothing. There is not one word here saying where to begin, or even how to install it. The readme and install files are literally empty. I can only assume there was anything at all in the 53KB debian package I installed. There is a ticket from February asking for documentation and nobody even responded. What gives?

This project sounds like an extremely useful extension to Kimchi, giving me the exact tools that made me look into other KVM management tools. Can you please take five minutes to tell the world how to turn it on?

**Comment by pvital** [comment]
@jdgregson How did you installed Kimchi from source code? 

I ask because there's an important thing related to installation process when executing "./autogen.sh". If you omit the "--system" the Kimchi files will be installed in a different path from the default by deb package of Ginger (or it's the opposite).

I suggest you to do the following. In the Kimchi source code path, go to plugins directory and clone the Ginger source code from github, and then, install Ginger using the same steps you used to build Kimchi.

**Comment by danielhb** [comment]
Guess it's too late to answer this issue now, but ....

It's unfortunate that you had trouble finding the install docs. They should be available somewhere at the Wiki page, easily accessible. We're going through massive changes for the next release of both Ginger and Kimchi and I'll make sure to include clear install instructions in the Wiki page for this next release in the next weeks.

The .deb package you installed has install instructions inside it in the README file.

**Comment by danielhb** [comment]
Documentation was updated with install instructions using distro packages or source code:

https://github.com/kimchi-project/ginger/blob/master/docs/README.md


Thanks
