### ISSUE TITLE
Would like to understand disabling selinux policy statement and it's consequences:

### ISSUE THREAD

**Issue by chandrureddy** [kimchi-project/ginger#211]
Would like to understand disabling selinux policy statement and it's consequences:

@danielhb @pvital 
I see the following command from the ginger documentation README.md. 
sudo semanage permissive -a tuned_t

Is there any necessity to enable the selinuc policy right now or can live with out enabling it.

**Comment by danielhb** [comment]
General rule is that requiring to disable SELinux for a certain feature to work is borderline bad. We're better always assume that it will be on, even if we need to add new SELinux rules.
