### ISSUE TITLE
Add user adds ID into an existing group (matching new uid) and creates duplicate gid in /etc/group

### ISSUE THREAD

**Issue by harche** [kimchi-project/ginger#212]
Already had an existing group "soltest" with gid 1006.  Last used uid in /etc/passwd was 1005.  When "Add User" was invoked for a kimchiuser profile (with default group settings) it created new user "testuser6" uid 1006.  But it added this id to group "soltest",  and gained soltest privileges (soltest had wheel like sudo privileges).

Looking into /etc/group showed duplicate gid entries.  One for the existing group, and one matching the name of the new user, ex:

```
[root@zs93k3 sudoers.d]# tail /etc/group
testuser:x:1000:
testuser2:x:1001:
markver:x:1002:
markkimchi:x:1003:testuser2
testuser3:x:1003:
testuser4:x:1004:
somegroup:x:1005:
testuser5:x:1005:
soltest:x:1006:
testuser6:x:1006:
[root@zs93k3 sudoers.d]# 
```

#=== Steps to Reproduce ====================================
#===========================================================
1. Create a new group, say "mygroup", ex:
    groupadd mygroup
2. Use kimchi to add new users (until the point where the uid of the new user numerically matches the gid of "mygroup")
3. cat /etc/group and verify that there are now 2 groups with gid that match gid of "mygroup"

**Comment by harche** [comment]
In the case where the existing group that was used had wheel like privileges ...

Users created with kimchiuser profiles are created with /sbin/nologin shell, so elevated privileges are restricted to the HVM gui.

Users created with virtuser profiles are created with a /bin/bash shell, so in that case new user gains elevated privileges both on HVM gui and ssh login.

Users created with admin profiles have elevated privileges to begin with so there is no increase in access.

**Comment by harche** [comment]
I am working on this issue

**Comment by danielhb** [comment]
This issue is fixed upstream.
