### ISSUE TITLE
 HVM user in sudo group can do Admin tasks but GUI shows profile as kimchiuser 

### ISSUE THREAD

**Issue by archu-s** [kimchi-project/ginger#215]
#=== Problem Description ===================================
#===========================================================
If we create a user manually in the wheel group, 
for example:

useradd -g wheel -m wheeluser

The user's primary (and only) group is wheel,  the user has sudo privilege.
When the user logs into the HVM GUI,   it can do all the Admin tasks,  
but its profile is kimchiuser instead of Admin.

#=== Steps to Reproduce ====================================
#===========================================================
1.  Create a user using useradd with default group of wheel or some other sudo group
2.  login to the HVM GUI with that user  - the user can do all the Admin tasks
but the profile for the user is kimchiuser.   The group listed is wheel

cat /etc/system-release
KVM for IBM z Systems release 1.1.1 (Z)

**Comment by archu-s** [comment]
After debugging the issue its looks to me the libuser package issue. As we are using this package for checking if user is in wheel group or not.

In this case if user's primary group is wheel, still libuser says that the user is not a wheel group user.

**Comment by danielhb** [comment]
Do you have a command line example that shows that? If this is a libuser issue it might be reproducible in other platforms as well

**Comment by harche** [comment]
@danielhb useradd -g wheel -m wheeluser

**Comment by sureshab** [comment]
i will be working on this issue.

**Comment by sureshab** [comment]
hi @archu-s 
patch was up-streamed for this issue,,please verify and close the issue if its fixed.
