### ISSUE TITLE
System Modules Details not loaded - Javascript error is console

### ISSUE THREAD

**Issue by atreyeemukhopadhyay** [kimchi-project/ginger#224]
On clicking the system modules tab, loading message is displayed. But details are not loaded.
Browser console displays javascript error.

![sysmodule](https://cloud.githubusercontent.com/assets/13199397/13426158/bb75d0ce-dfd1-11e5-9c42-1c9242eb8fae.jpg)

**Comment by danielhb** [comment]
I don't see this error happening when running wok+gingerbase+ginger from source code:

![image](https://cloud.githubusercontent.com/assets/866780/13426703/faf3ad46-df8d-11e5-8f97-650eb429e6bf.png)


Have you tested it using RPM?

**Comment by danielhb** [comment]
Just confirmed the error here when running wok gingerbase and ginger from RPM

I'll fix it

**Comment by danielhb** [comment]
A fix was pushed to master just now. Let me know if this error still occurs. Otherwise please close the issue

**Comment by atreyeemukhopadhyay** [comment]
System modules details are loading properly now. Closing defect.
