### ISSUE TITLE
Show GiB instead of g for Volume Group sizes

### ISSUE THREAD

**Issue by lcorreia** [kimchi-project/ginger#226]
At Host -> Storage -> Volume Group,volume group sizes are showed with g, which is not the proper way to express gigabytes.

On the other hand, the sizes are correctly showed as G or MiB for File Systems and Swap Devices sections.

**Comment by biancafc** [comment]
Lucio, I'm not able to reproduce this issue, could you please include some image or check if you are still seeing this problem?
