### ISSUE TITLE
SR-IOV enablement for mellanox connectx-4 card - network UI

### ISSUE THREAD

**Issue by danielhb** [kimchi-project/ginger#229]
The backend for this feature is already available in the 'next' branch and will be merged with the 'master' branch in the end of the month.

The API is similar with what we have in sysmodules and SR-IOV for mlx4 module but it is now hosted n the /network/interfaces/<interface_name>/action API. This is an example using curl:

$ curl -k -u root -H "Content-Type: application/json" -H "Accept: application/json" 'https://localhost:8001/plugins/ginger/network/interfaces/<mlx5_interface>/action' -X POST -d'{"name":"SR-IOV", "args":{"num_vfs":"4"}}'

This feature is only enabled for the interfaces loaded with 'mlx5_core/mlx5-core' modules. There is a new attribute called 'module' in the lookup() where the UI can fetch this information.

So, based on the current Network Configuration API, this is what I propose:

- add a new column named 'module' to show the new driver information for all cards
- in the "Actions" menu, create a new option called "Enable SR-IOV". This option will only be available if, and only if, a card with the mlx5_core/mlx5-core driver is selected. Otherwise, no need to show this option
- Clicking on this link will show a modal, something like the following mock:

![image](https://cloud.githubusercontent.com/assets/866780/13826624/38000ba2-eb97-11e5-9066-9d164f659c23.png)

I believe it's self explanatory. Interface name in the title, field receives an integer. 'Cancel" aborts the operation, 'Ok' fires a requisition like the one I mentioned in the 'curl' line above. I don't believe there's a JS call with this specific new API - feel free to add one.

Suggestions are welcome!

**Comment by danielhb** [comment]
@laggarcia @sstoppler any thoughts?

**Comment by laggarcia** [comment]
Sounds good to me.

**Comment by sstoppler** [comment]
I agree

**Comment by samhenri** [comment]
Agreed.

**Comment by sstoppler** [comment]
Patch applied upstream:  
https://github.com/kimchi-project/ginger/commit/8a317a201570549b82dca21e221ec194aada537f

**Comment by danielhb** [comment]
Recent changes in the backend will require changes in this current UI design.

- The most critical change is that now this process is asynchronous. It will generate a task that the UI needs to track when it is finished. My initial idea was to add a small pane under the Network frame to track the progress of this task. When the task is completed, a message will be sent to the user and then this pane disappears. I can draw a mock to illustrate this behavior if necessary.

- We did an API change as well. It is now simpler. Instead of using the 'action' API with the parameter 'name: SRIOV' and  'num_vfs', we will now use the API 'enable_sriov' with only one parameter, 'num_vfs'. So, to enable the 'SR-IOV' function in the 'Actions' menu, simply check if  the 'module' attribute of a given interface is 'mlx5_core' or 'mlx5-core'. The API to start the setup process will be /ginger/network/<interface>/enable_sriov , receiving a 'num_vfs' parameter, and it will return a task_id.

@laggarcia @alinefm @sstoppler @samhenri let me know your thoughts, comments or doubts about these changes.

**Comment by sstoppler** [comment]
Patch applied upstream:  https://github.com/kimchi-project/ginger/commit/f879f46398057e48c9b8361efa45296731fe2aae

**Comment by danielhb** [comment]
I've tested the UI in the actual hardware. It worked out of the box, good job. I just have one suggestion about it:

![image](https://cloud.githubusercontent.com/assets/866780/15604557/716fb680-23d7-11e6-8065-7c4215cad6d1.png)

The new frame opened to track the progress of the task must be closeable. At this moment, clicking in the arrow down icon will just hide the content below the "Enable SR-IOV Progress" title. We need a "X" close icon in the right or left upper corner of this frame to dismiss it after the operation is completed. Only way to dismiss it now is by refreshing the tab.
