### ISSUE TITLE
In Storage tab the bottom lines are miss-aligned on each section expansion

### ISSUE THREAD

**Issue by atreyeemukhopadhyay** [kimchi-project/ginger#232]
Storage tab section's bottom lines are misaligned once sections are expanded.

![storage align](https://cloud.githubusercontent.com/assets/13199397/13845894/16dc0b92-ec69-11e5-8a8f-2f04f6d63b16.jpg)

**Comment by atreyeemukhopadhyay** [comment]
This is fixed and change is available in upstream.

**Comment by alinefm** [comment]
Fixed by c09657edd89ef450e8c50ce841ad8aac21044083
