### ISSUE TITLE
Manage Filesystems using Ginger

### ISSUE THREAD

**Issue by pkulkark** [kimchi-project/ginger#24]
Using the `Ginger` we would like to list/mount/unmount the filesystems used  by the host. Here is the example of filesystems as seen from the host
 
**df -hT**
```
Filesystem              Type      Size  Used Avail Use% Mounted on
devtmpfs                devtmpfs  3.7G     0  3.7G   0% /dev
tmpfs                   tmpfs     3.8G  628K  3.8G   1% /dev/shm
tmpfs                   tmpfs     3.8G  1.2M  3.8G   1% /run
tmpfs                   tmpfs     3.8G     0  3.8G   0% /sys/fs/cgroup
/dev/mapper/fedora-root ext4       50G   17G   30G  37% /
tmpfs                   tmpfs     3.8G   87M  3.7G   3% /tmp
/dev/sda1               ext4      477M  159M  289M  36% /boot
/dev/mapper/fedora-home ext4      237G   14G  211G   7% /home
tmpfs                   tmpfs     760M   24K  759M   1% /run/user/1000
tmpfs                   tmpfs     760M     0  760M   0% /run/user/0
```
 
Here is the proposal for `Ginger` to do file system management on the host - 
 
**Collection: File Systems**
---------------------------------------------------------------------------------------------
 
URI: /plugins/ginger/filesystems
 
**Methods:**
 
**GET**: Retrieve a summarized list of all mounted filesystems

**POST**: Mount a file system
- *blk_dev* : Path of the device to be mounted.
- *mount_point* : Mount point for the filesystem
 
**Resource: File System**
---------------------------------------------------------------------------------------------
URI: /plugins/ginger/filesystems/*:mount_point*
 
**Methods:**
 
**GET**: Retrieve the full description of the mounted filesystem

- *use%*: Percentage of the filesystem used
- *used*: Amount of space used in filesystem
- *size*:  Total size of the filesystem
- *mounted_on*: Mount point of the filesystem
- *avail* : Total space available on the filesystem
- *device_name* : Backing device name of the filesystem.
- *type* : Filesystem type.
 
**DELETE**: Unmount the Filesystem

**Comment by pvital** [comment]
@harche interesting feature, but please, send a RFC (Request For Comments) to ginger mailing list ginger-dev-list@nongnu.org (CC also the old ML ginger-dev@yahoogroups.com due to delivery issues on nongnu lists). There you will get more feedback than here.

**Comment by danielhb** [comment]
Which kind of safeguards are you planning for this feature? Or are you 
going to
assume that the admin will know what he's doing?

We could at least prevent the filesystem that Ginger/Wok is running on to be
unmounted, otherwise we lose control of the host.

**Comment by pkulkark** [comment]
@danielhb We are using [umount] (http://linux.die.net/man/8/umount) in the backend for unmounting the filesystem. 'umount' doesn't allow the filesystem currently used by applications to be unmounted. If user tries to unmount the filesystem that's being used by any application, umount will return with non-zero status code and we will simply pass this error and status all the way up to RESTful API.

**Comment by danielhb** [comment]
I agree with this design

I suggest to copy/paste your first comment to the new ML, ginger-dev-list@googlegroups.com, to see if anyone else from the community wants to comment. 

Thanks

**Comment by danielhb** [comment]
This feature is available upstream
