### ISSUE TITLE
Manage Physical Volumes using Ginger

### ISSUE THREAD

**Issue by pkulkark** [kimchi-project/ginger#25]
Using the Ginger we would like to list/create/remove the Physical Volumes used by the host. Here is the example of Physical Volumes as seen from the host

**pvdisplay**
```
  --- Physical volume ---
  PV Name               /dev/mapper/luks-92ee4956-3fd1-47fa-a603-9b8ad867f66d
  VG Name               fedora
  PV Size               297.60 GiB / not usable 2.00 MiB
  Allocatable           yes 
  PE Size               4.00 MiB
  Total PE              76185
  Free PE               16
  Allocated PE          76169
  PV UUID               Yce0X3-H5vz-65P3-u7Fk-s7Nv-G903-4QJDnb
   
  "/dev/loop0" is a new physical volume of "10.00 MiB"
  --- NEW Physical volume ---
  PV Name               /dev/loop0
  VG Name               
  PV Size               10.00 MiB
  Allocatable           NO
  PE Size               0   
  Total PE              0
  Free PE               0
  Allocated PE          0
  PV UUID               u7OOoW-rL9W-DdJN-kHeM-doXt-grLD-S9yOdc
```

Here is the proposal for Ginger to do Physical Volume management on the host -

# Collection: Physical Volumes

URI: /plugins/ginger/pvs

**Methods:**

**GET**: Retrieve a summarized list of all physical volumes

**POST**: Create a physical volume

  -  *pv_name* : Path of the device to be used as PV.

*Note* - Default options are used for creating the PV. Later releases can implement other options.

# Resource: Physical Volume

URI: /plugins/ginger/pvs/:pv_name

**Methods:**

**GET**: Retrieve the full description of the physical volume

   - *PvName*: Name of the physical volume
   - *Allocatable*: If the PV is allocatable, value is 'yes' otherwise 'no'
   - *PvUUID*: UUID of the physical volume
   - *TotalPE*: Total physical extent
   - *AllocatedPE* : Amount of physical extent allocated
   - *PvSize* : Size of the physical volume
   - *PeSize* : Size of the physical extent
   - *FreePE* : Number of free PEs
   - *VgName* : Name of the volume group to which the PV belongs

**DELETE**: Remove the physical volume

*Note* - Proposal to include volume group management and LVM management could be made at a later stage

**Comment by danielhb** [comment]
Feature is available upstream
