### ISSUE TITLE
[Accessibility: Keyboard] Keyboard navigation in the hosts tab is inconsistent

### ISSUE THREAD

**Issue by ghidasy** [kimchi-project/ginger#261]
The Hosts tab is generally accessible by pressing tab multiple times, once.

When the focus goes to the last active link it does not wrap around, while this is acceptable, its inconsistent with all the other tabs

**Comment by atreyeemukhopadhyay** [comment]
@ghidasy ,
Could you please give more details / screenshot about the issue.

**Comment by ghidasy** [comment]
When the focus reaches the last link in the Hosts tab, it stays there on subsequent pages.
In all other tabs it wraps around, going to the first focus element.
Screenshot attached, with focus in the last enabled link in my system. Pressing tab there does nothing.
![screenshot from 2016-03-28 09-06-39](https://cloud.githubusercontent.com/assets/17005004/14077696/bc333bc0-f4c4-11e5-979d-32f147be4e4f.png)

**Comment by danielhb** [comment]
Just a heads up: this is *not* the current UI we're using. We need to assert that this problem occurs in the existing UI

**Comment by ghidasy** [comment]
Understood, this is the UI found in fedora packages.

I am testing the new UI right now. and I must say it was a great work, almost all problems I found before were fixed
