### ISSUE TITLE
Optimize ginger plugin for loading the modules

### ISSUE THREAD

**Issue by abhiramkulkarni** [kimchi-project/ginger#27]
Currently when we define new resource and collections, it needs to be added/imported to init.py , ginger.py and model.py .

Instead of that we can optimize to load the newly added files automatically similar to kimchi plugin and make this process easy for adding new resource/collection to these files.

**Comment by danielhb** [comment]
@abhiramkulkarni are you willing to give this a shot? I can do it after fixing some stuff first

**Comment by danielhb** [comment]
Optimization done!
