### ISSUE TITLE
[accessibility : Keyboard & navigation] Checkbox are not getting checked using keyboard

### ISSUE THREAD

**Issue by atreyeemukhopadhyay** [kimchi-project/ginger#292]
In bond page , none of the checkbox is  getting checked using keyboard but focus is available for the checkbox.

![checkbox](https://cloud.githubusercontent.com/assets/13199397/14140573/6e17a5fa-f697-11e5-9f53-c572856cf13a.jpg)

**Comment by ghidasy** [comment]
I can't exactly confirm this issue, checkboxes are working here (but they need space to be toggled, while some other items require enter), form fields also work well, being editable when they are in focus

**Comment by atreyeemukhopadhyay** [comment]
@ghidasy ,
thanks for the information. Checkbox is getting checked and unchecked using space bar not Enter button.
