### ISSUE TITLE
Collapse all sessions in Network tab on first access

### ISSUE THREAD

**Issue by alinefm** [kimchi-project/ginger#298]
For an user perspective, it is better to have all sessions collapsed so he/she can easily identify on each one he/she wants to work on.

It is also important when using screen reader, so it will take just a few to read all the sessions and decide on each to open on.

![2a3596453ad38564](https://cloud.githubusercontent.com/assets/4921718/14290249/aef9ed98-fb34-11e5-8752-af5d4d9152d1.jpg)

**Comment by danielhb** [comment]
Fixed in master.
