### ISSUE TITLE
Redesign "Network Configuration" UI

### ISSUE THREAD

**Issue by alinefm** [kimchi-project/ginger#300]
There are a few issues in this "Network Configuration" section:

![2073af205fb2483b](https://cloud.githubusercontent.com/assets/4921718/14297370/c3bbaa44-fb54-11e5-8ce5-e58b635f5ba8.jpg)

1. There are scroll bars when they are not needed.

2. Why allow multiple selection if no actions is allowed when selecting more than one interface ?

3. To keep consistence, I'd suggest to have only one button 'Add'.
    When selecting this Add button, a dialog to choose the network type is displayed (similar to what we have when adding a new Template in Kimchi). According to selected type, display the appropriated inputs.

Said that, my suggestion is do change this section to something like below:

```
| + Add |  | Refresh |                                | Filter                |

| Name      | Type       | Address Space    | MAC Address          |              
| iface 1   | Ethernet   | 1.1.1.1          | 12:34:56:78:90       |  Actions  |
| iface 2   | Vlan       |                  | 12:34:56:78:90       |  Actions  |
| iface 3   | Ethernet   | 2.3.4.6          | 90:34:56:78:90       |  Actions  |

```

When selecting the Actions menu, the list of available actions will be listed: Down/Up, Restart, Settings, Delete.

All the widgets used for this mockup MUST follow Wok style. The idea of this proposal is to have something similar to what we have on Network tab in Kimchi.

**Comment by alinefm** [comment]
More details about the "Add" button behavior can be found at #308

**Comment by alinefm** [comment]
The 'Add' button is a feature provided by Ginger s390x. So I will move the issue #308 to the right project.

**Comment by chandrureddy** [comment]
@alinefm : 
Q. Why multiple selection is enabled if no action can be taken?
Definitely, multiple selection will be enabled and actions can be taken based on the selections. Unfortunately all features are not implemented as per the network design pages been approved by the community. 

We had trouble with python-augeas and restricted to one interface earlier. But now with code optimization multiple selection will be possible for performing certain actions.

**Comment by samhenri** [comment]
Hi @chandrureddy 

Sorry for the delay. On my environment the multiple selection doesn't work. If I select more than one item, the Actions drop-down is disabled. I think we should at least disable the dropdown <li> (adding the class .disabled and checking it with javascript) for the matched actions (If I select only interfaces that are down, then enable the "Up" action and "Restart", if I select multiple interfaces then only Restart is enabled). If this is not possible then I agree with @alinefm mockups, the interface actions button should be moved to each line and the Add and Refresh buttons to the top left of the table.

**Comment by chandrureddy** [comment]
Hi Samuel,

These actions are possible with the current implementations. I guess as 
part of the issue we can work out the solution and fix these.

Again we intentionally not allowed earlier to avoid core dump issues by 
augeas. Now since back end code optimization done we can enable multiple 
selection and possible user actions against them.

Regards
Chandra

**Comment by danielhb** [comment]
This is the proposed fix in the ML:


![image](https://cloud.githubusercontent.com/assets/866780/16732076/b3ada14a-4751-11e6-85a9-a9a7f1b963f0.png)


Note that the 'Add' and 'Refresh' buttons are on the top right side of the table. This is not compliant with the rework being made in the Global Network where, in its first version, put everything on the
top left side:

![image](https://cloud.githubusercontent.com/assets/866780/16732143/027fc186-4752-11e6-9bbc-7f571d7c4957.png)



@alinefm @chandrureddy @samhenri we can't allow 2 features at the same table to have such differences in the layout. We need a consensus of where this 'Refresh' and 'Add' buttons are going to be for both Global Network and Network Settings layout.

**Comment by samhenri** [comment]
@danielhb I believe the current patch sent to the ML was the final patch for Network Configuration using jQuery Bootgrid. Although the title says "redesign "Network Configuration" UI" there's still work to be done. I was waiting this patch in order to work with the DataTables port.

**Comment by danielhb** [comment]
@samhenri are you saying that the relocation of the 'Add' and 'Refresh' button is going to be made by you in this port to DataTables?

If that's the case then I will relieve the current patch in the ML from doing it.

**Comment by samhenri** [comment]
I thought that this what was aligned a few scrum meetings ago, right @alinefm @chandrureddy ?

**Comment by danielhb** [comment]
@samhenri Ok, I'll inform that in the ML

**Comment by alinefm** [comment]
Correct, @samhenri and @danielhb

**Comment by alinefm** [comment]
Sorry, seems more changes are needed to close this issue.

**Comment by samhenri** [comment]
I'm currently working on this redesign but I'll keep the "Actions" drop-down since the multi-selection is now working.  I think the first button should be the Actions drop-down and then the Add drop-down, like this:
```
| Actions v |  | + Add v |  | Refresh |                              | Filter                |

| Name      | Type       | Address Space    | RDMA enabled   | MAC Address                   |
| iface 1   | Ethernet   | 1.1.1.1          | No             | 12:34:56:78:90                |
| iface 2   | Vlan       |                  | No             | 12:34:56:78:90                |
| iface 3   | Ethernet   | 2.3.4.6          | No             | 90:34:56:78:90                |
```

I'm having problems to add a new Bond or Interface, can someone show me a valid PUT request when the user hits the "Save" button? The "Parent Interface" and "Bond Members" selects are empty for me.

**Comment by samhenri** [comment]
Hi, I'm unable to Add a Bond and Add a VLAN with the current code. The JSON from cfginterfaces looks like this:
```
[
  {
    "IPV4_INFO":{
      "PEERROUTES":"yes",
      "IPV4INIT":"yes",
      "DEFROUTE":"yes",
      "PEERDNS":"yes",
      "IPV4_FAILURE_FATAL":"no",
      "IPV4Addresses":[
        {
          "PREFIX":"255.255.255.0",
          "IPADDR":"10.10.71.45",
          "GATEWAY":"10.10.71.1"
        }
      ],
      "BOOTPROTO":"static"
    },
    "BASIC_INFO":{
      "UUID":"6b4d4616-5a39-48a1-b73e-58bef428a1b5",
      "MTU":"1500",
      "HWADDR":"1A:6B:53:EE:BB:29",
      "TYPE":"Ethernet",
      "ONBOOT":"yes",
      "NAME":"ens3"
    },
    "IPV6_INFO":{
      "IPV6INIT":"yes",
      "IPV6_PEERDNS":"yes",
      "IPV6_DEFROUTE":"yes",
      "IPV6_AUTOCONF":"yes",
      "IPV6_FAILURE_FATAL":"no",
      "IPV6_PEERROUTES":"yes"
    }
  }
]
```
I've checked the JS code and found this:

```
if ("BASIC_INFO" in interfaceInfo && "DEVICE" in (interfaceInfo.BASIC_INFO)) {
...
}
```
Is this correct? My CFG file doesn't seem to have the BASIC_INFO key.

**Comment by danielhb** [comment]
"BASIC_INFO" is a grouping of the following parameters:

    * BASIC_INFO: Basic information of network interface:
        * NAME: Name of the interface.
        * DEVICE: Device name of the interface.
        * ONBOOT: 'Yes' if interface is to be brought up during boot,
                  'No' if interface should not be brought up during boot.
        * TYPE: Interface type ('nic', 'bonding', 'vlan')
        * MACADDR: Mac address of ethernet device.
        * VLAN: 'Yes' If its vlan device.
        * VLAN_ID: vlan id of the vlan device.
        * PHYSDEV: physical device associated with the vlan device.
        * BONDING_OPTS: Bonding parameters of the Bond device.
        * BONDING_MASTER: 'yes' if its bond device.
        * SLAVES: Returns slaves associated with the bond.
        * NETTYPE(system z): Returns network device driver type
        * SUBCHANNELS(system z):List of sub channels(network triplets) of
                                the interface

**Comment by samhenri** [comment]
@danielhb I've updated my comment. The BASIC_INFO object is there but I don't have the DEVICE, so the select / comboboxes for Bonds and VLANS are always empty. Is this correct? Can't I look for the interface name instead of the device name if the DEVICE key is not available or is it a problem with my CFG file?
````
      if ("BASIC_INFO" in interfaceInfo && "DEVICE" in (interfaceInfo.BASIC_INFO)) {
        interfaceDetails["value"] = interfaceList[i].BASIC_INFO.DEVICE;
        interfaceDetails["text"] = interfaceList[i].BASIC_INFO.DEVICE;
        memberOptions.push(interfaceDetails);
      }
```

**Comment by danielhb** [comment]
If you're running in a Fedora/RHEL you should have the 'DEVICE' attribute in the cfgfile of a network card. It refers to the device as listed by ifconfig. 

You can put a workaround in the UI to find for NAME if DEVICE isn't found and see if it works though. In some distros DEVICE and NAME are interchangeable.

**Comment by samhenri** [comment]
Yes, i'm running Fedora 23 this time and found this. It seems is happening with some Ubuntu machines but I still need to confirm. I'll make a workaround to use the interface name if device is not available then.

**Comment by jay-katta** [comment]
Hi samhenri, as danielhb said if you are running in Fedora/RHEL you should have DEVICE attribute in ifcfg file of network interface. 
As of now cfginterfaces does not support Ubuntu.
To understand more, can you share your operating system and ifcfg content details.

**Comment by samhenri** [comment]
Hi @chandrureddy @alinefm @danielhb,, I'm almost finishing the redesigned panel but I have a question regarding the buttons.
Since I've added the _lodash library, I can filter arrays by values so I can check if all the selected items have the same network type, module, etc.  For SR-IOV I know I can't display the option with multiple selected items because it opens a modal window and the user has to input the parameters to each network interface.
But for the Delete button, I think I could enable the button if the user selected networks that aren't "nic" type. In this case I would display a wok.confirm() dialog to remove the selected interfaces, including the ones that were selected on the other pages. What do you think?

Another question, when the current script checks if the selected row has the the mlx5-core module installed, we have the following line:
```
if ((selectedIf[0]["module"] != 'mlx5_core' && selectedIf[0]["module"] != 'mlx5-core') || (selectedIf[0]["nic_type"] === 'virtual' )) {
...
}
```
Is this correct? Why do we have to check for mlx5_core twice? As for this feature, I can't test it because I'm running on a virtual environment but I can mock an object and show the option to check if the modal window is at least working.

**Comment by danielhb** [comment]
On 08/16/2016 06:03 PM, Samuel wrote:
>
> Hi @chandrureddy <https://github.com/chandrureddy> @alinefm 
> <https://github.com/alinefm> @danielhb <https://github.com/danielhb>,, 
> I'm almost finishing the redesigned panel but I have a question 
> regarding the buttons.
> Since I've added the _lodash library, I can filter arrays by values so 
> I can check if all the selected items have the same network type, 
> module, etc. For SR-IOV I know I can't display the option with 
> multiple selected items because it opens a modal window and the user 
> has to input the parameters to each network interface.
> But for the Delete button, I think I could enable the button if the 
> user selected networks that aren't "nic" type. In this case I would 
> display a wok.confirm() dialog to remove the selected interfaces, 
> including the ones that were selected on the other pages. What do you 
> think?
>
Go for it

> Another question, when the current script checks if the selected row 
> has the the mlx5-core module installed, we have the following line:
>
> |if ((selectedIf[0]["module"] != 'mlx5_core' && selectedIf[0]["module"] 
> != 'mlx5-core') || (selectedIf[0]["nic_type"] === 'virtual' )) { ... } |
>
> Is this correct? Why do we have to check for mlx5_core twice? As for 
> this feature, I can't test it because I'm running on a virtual 
> environment but I can mock an object and show the option to check if 
> the modal window is at least working.
>

Because the module sometimes appears as 'mlx5_core' and in others 
'mlx5-core'. This happened
a lot with the former mlx4_core driver.

I'll be honest and say that I am not seeing 'mlx5-core' anymore but it's 
better to be on the safe side.

**Comment by chandrureddy** [comment]
@samhenri @danielhb in case of platform s390x interfaces of type 'nic' can also be deleted. So we have enable 'Delete' option in case of s390x for the interfaces of type 'nic' too.

**Comment by samhenri** [comment]
@chandrureddy does the current implementation already checks s390x interfaces?

**Comment by chandrureddy** [comment]
@samhenri I guess so. Removal of interfaces of type 'nic' should already work on s390x.

**Comment by samhenri** [comment]
I meant, how to check if the user is running a s390x or default ginger with JavaScript?

**Comment by chandrureddy** [comment]
I guess recent patch by commit 84f43d5188892e30b39793d9c6e43d555f0ed88d disables button 'Delete'. But I suppose we have to enable 'Delete' in case of s390x. 

May be @atreyeemukhopadhyay  can help us here better as she recently done such changes and code handling in case of s390x.

**Comment by chandrureddy** [comment]
We can rely on the API call  of gingerbase : /plugins/gingerbase/host to know about the architecture. 

In case of s390x you get the following details:

Basic Information
s390x
    Architecture
KVM for IBM z Systems
    OS Distro
1.1.3
    OS Version
Z
    OS Code Name
IBM/2827/743 H43
    Processor
Online: 2    Offline: 2
Book(s): 4    Socket(s): 6    Core(s) per Socket: 6    Thread(s) per Core: 1
    CPU(s)
Shared: 2    Dedicated: 0
    Core(s)
Online: 4GiB    Offline: 0B
    Memory
Name: CSTLIN1    ID: 55
    LPAR Details
Name: PR/SM    Vendor: IBM
    Hypervisor Details
