### ISSUE TITLE
Redesign "File Systems" UI

### ISSUE THREAD

**Issue by alinefm** [kimchi-project/ginger#302]
There are some issues in the File System section:

![2bb1cab93633f2aa](https://cloud.githubusercontent.com/assets/4921718/14304606/ac9ddb76-fb8a-11e5-9c4b-4fd024c30639.jpg)
1. Why multiple selection is enabled if no action can be taken?
2. Paging should be shown only when needed
3. Refresh button and Filter input box are not aligned.
4. File system paths are not aligned when there are long paths.
5. The progress bar for usage is unnecessary. We could change it to other icon to give the user the same visual feedback on which is full or not. Similar to what we have in the Storage tab in Kimchi

![33d343dbad1686c1](https://cloud.githubusercontent.com/assets/4921718/14304635/e59000bc-fb8a-11e5-8ccd-773650e447d2.jpg)

Said that, I suggest to change this section UI to something like below:

```
- File Systems

| Refresh |                    | Filter                   |

| Name    | Mount Point | Type  | Size | Usage            |
| FS1     | /foo        | tmpfs | 10GB | <usage icon> 10% |
| FS2     | /bar        | tmpfs | 12GB | <usage icon> 15% |
```

All the widgets used for this mockup MUST follow Wok style.

**Comment by chandrureddy** [comment]
@alinefm : 
Q. Why multiple selection is enabled if no action can be taken?
Definitely, multiple selection will be enabled and actions can be taken based on the selections. Unfortunately all features are not implemented as per the storage design pages been approved by the community. But to answer short Actions will be implemented and multiples selection are possible based on the action chosen.

**Comment by samhenri** [comment]
@alinefm @chandrureddy should we then redesign it now with multiselection disabled? Can we enable multi-selection for at least one action?

**Comment by chandrureddy** [comment]
@samhenri @alinefm 
Multi selection is required and atreyeemukhopadhyay is working on the actions part. So soon patch will be sent to upstream
