### ISSUE TITLE
[NW]: The activation of interface shows a successful message but is not activated in actual

### ISSUE THREAD

**Issue by mesmriti** [kimchi-project/ginger#304]
#===========================================================
When a interface is activated from the UI the interface is activated successfully message is seen
on the UI but the icon of the interfaces still show that its not activated.

#=== Steps to Reproduce ====================================
#===========================================================
1.. Select a interface.
2. Try to activate or deactivate it
3. Check for the icon that corresponds to activation or deactivation.

**Comment by mesmriti** [comment]
Fixed

**Comment by danielhb** [comment]
The patch isn't upstream yet. Reopening
