### ISSUE TITLE
Redesign "Swap Devices" UI

### ISSUE THREAD

**Issue by alinefm** [kimchi-project/ginger#306]
There are some issues in the Swap Devices section:

![1723960eb826d332](https://cloud.githubusercontent.com/assets/4921718/14371481/8fad31da-fd0e-11e5-870e-ddec61faff90.jpg)
1. Why multiple selection is enabled if no action can be taken?
2. Paging should be shown only when needed
3. Refresh button and Filter input box are not aligned.
4. The progress bar for usage is unnecessary. We could change it to other icon to give the user the same visual feedback on which is full or not. Similar to what we have in the Storage tab in Kimchi
   Similar to what was suggested to File System section in issue #302 

Said that, I suggest to change this section UI to something like below:

```
- Swap Devices

| Refresh |                    | Filter                   |

| Name       | Type         | Capacity | Usage            |
| /swap1     | partition    | 10GB     | <usage icon> 10% |
| /swap2     | partition    | 12GB     | <usage icon> 15% |
```

All the widgets used for this mockup MUST follow Wok style.

**Comment by chandrureddy** [comment]
@alinefm : 
Q. Why multiple selection is enabled if no action can be taken?
Definitely, multiple selection will be enabled and actions can be taken based on the selections. Unfortunately all features are not implemented as per the storage design pages been approved by the community. But to answer short Actions will be implemented and multiples selection are possible based on the action chosen.

**Comment by samhenri** [comment]
@alinefm @chandrureddy should we then redesign it now with multiselection disabled? Can we enable multi-selection for at least one action?
