### ISSUE TITLE
Redesign "Storage Devices" UI

### ISSUE THREAD

**Issue by alinefm** [kimchi-project/ginger#307]
There are a few issues in this "Storage Devices" section:

![5a4b864d641b06ff](https://cloud.githubusercontent.com/assets/4921718/14371591/aa9a657a-fd0f-11e5-95fa-bc65254809f0.jpg)
1. There are scroll bars when they are not needed.
2. Why multiple selection is enabled if no action can be taken?
3. To keep consistence, I'd suggest to have only one button 'Add'.
   When selecting this Add button, a dialog to choose the storage type is displayed (similar to what we have when adding a new Template in Kimchi). According to selected type, display the appropriated inputs.

Said that, my suggestion is do change this section to something like below:

```
| + Add |  | Refresh |         | Filter                |

| ID         | Multipath Links  | Type    | Size       |              
| storage1   | 1                | sata    | 10GB       |
| storage2   | 1                | sata    | 15GB       |
| storage3   | 1                | sata    | 12GB       |
```

All widgets shown on mockup MUST follow Wok style.

**Comment by alinefm** [comment]
I've just noticed the "Add" button is for Ginger s390x proposals. So we must remove it from Ginger.

**Comment by chandrureddy** [comment]
@alinefm: 
Let me answer few of your questions:

Q. Why multiple selection is enabled if no action can be taken?
Definitely, multiple selection will be enabled and actions can be taken based on the selections. Unfortunately all features are not implemented as per the storage design pages been approved by the community.  But to answer short Actions will be implemented and multiples selection are possible based on the action chosen.

Q. To keep consistence, I'd suggest to have only one button 'Add'.
Add is more of feature which will apply only to s390x. So based on your proposal outcome mentioned https://github.com/kimchi-project/ginger/issues/317 this section will be shown in case of s390x.

**Comment by samhenri** [comment]
@chandrureddy I believe my Wok Style @alinefm meant that the table should look like the other tables in Kimchi, Ginger System Services, OVS Bridges and System Modules. Should we limit the panel viewport and display vertical scroll-bars all the time or increase the panel height?
