### ISSUE TITLE
Restrict Interface names and User names/passwords to ASCII characters only during creation

### ISSUE THREAD

**Issue by pkulkark** [kimchi-project/ginger#313]
Interface names created with different characters (non-ascii) fails to activate. Systems with user names or passwords created with other characters cannot be accessed through Operation systems messages console in SE. Hence restrict the characters to ASCII for these two features during creation.

**Comment by pkulkark** [comment]
I will be submitting a patch for this

**Comment by danielhb** [comment]
I don't know what is "operation system messages console in SE" but we can't restrict Ginger features, even if it's interface naming, because of limitations in what I am considering to be external software.

**Comment by alinefm** [comment]
I am not sure about interfaces names and user names, but I am sure we can use non-ASCII characters for passwords. So there is no reason to add this restriction.
