### ISSUE TITLE
Storage Device listing shows "Not Record Found" till the time data is getting fetched

### ISSUE THREAD

**Issue by atreyeemukhopadhyay** [kimchi-project/ginger#315]
when the storage tab is loaded, storage device listing section shows loading message followed by message "No record found" till it gets the data from backend. 
![loading](https://cloud.githubusercontent.com/assets/13199397/14527290/8f9ff71a-0266-11e6-899e-cbc7e30c389b.jpg)

![no result](https://cloud.githubusercontent.com/assets/13199397/14527192/d368f18c-0265-11e6-9ef1-d8029845414a.jpg)
![result](https://cloud.githubusercontent.com/assets/13199397/14527202/e5bd1f66-0265-11e6-95f7-62a997ae02cf.jpg)

**Comment by danielhb** [comment]
Fixed by https://github.com/kimchi-project/ginger/commit/4f178990a1d0a59f4fbdb3400a7003dc86cf0296
