### ISSUE TITLE
System services UI 

### ISSUE THREAD

**Issue by danielhb** [kimchi-project/ginger#316]
This is the discussion of the system services UI. Let me start by listing the 'service' element returned by the backend to exemplify what we're trying to show:

```
[danielhb@arthas ginger]$ curl -k -u danielhb -H "Content-Type: application/json" -H "Accept: application/json"  "https://localhost:8001/plugins/ginger/services/wpa_supplicant.service" -X GET
Enter host password for user 'danielhb':
{
  "load":"loaded",
  "sub":"running",
  "name":"wpa_supplicant.service",
  "autostart":false,
  "active":"active",
  "cgroup":{
    "processes":{
      "1302":"/usr/sbin/wpa_supplicant -c /etc/wpa_supplicant/wpa_supplicant.conf -u..."
    },
    "name":"/system.slice/wpa_supplicant.service"
  },
  "desc":"WPA supplicant"
}[danielhb@arthas ginger]$ 
```

What I've imagined for this interface is something similar to what we already have in system modules:

![image](https://cloud.githubusercontent.com/assets/866780/14531082/43b79814-0232-11e6-90d0-5b35b9a97f44.png)

The frame would be called "System services management" and would be located in the top of this tab. This tab would be renamed to "System resources". Both frames, services and modules, would start closed when first opening the tab. Opening one frame would close the other - these are huge listings and it's easier to deal with them one at a time.

Back to the Services API, using the above picture as a base:

- we do not need the 'load modules' button as we will not load any new service. In fact, in this UI we won't need any modals.
- we definitely want the filter in this UI too
- column names: name, status, autostart, details.
    *  'name' : the name of the service. Yes, the full name, including the usual '.service' suffix 

    *  'load' : the 'load' value of the service.

    * 'status' :  a string that represents the overall status of the service, which will be a merge of the 'loaded' and 'sub' attributes in the format "loaded (sub)". In the example I posted earlier, status would be "active (running)". This format is not random - this is how systemd shows the status of the service when issuing ```systemctl status```.

    * autostart: this field can be simply the value of the 'autostart' attribute. However, if we use a On/OFF switch button to represent it, we can use the same button to also turn it on and off. Toggling it to 'off' would fire the 'disable' action in this service, toggling it to 'on' fires the 'enable' action. This will also save room in the 'Actions' submenu.

    * details: working in the same way as in the system modules, this will show the processes that are being executed by this service. This info is hosted at the 'cgroup' attribute. Note that this attribute is not always present - in such cases there is no need to show the arrow down. If the attribute is present, pressing the arrow down would show the following info, in our example. Please note that we can have more than one process to be shown:
<pre>
    cgroup: /system.slice/wpa_supplicant.service
    processes:
        1302: /usr/sbin/wpa_supplicant -c /etc/wpa_supplicant/wpa_supplicant.conf -u
</pre>
    * actions: a submenu with the following options: 'Start', 'Stop', 'Restart'. Each button will fire the respective action in the backend.

Let me know what you think. @alinefm  @samhenri @laggarcia @sstoppler

**Comment by laggarcia** [comment]
Sounds good to me. Just one minor thing. I think you mixed things in your description of the status column. Are you suggesting to use load (sub) or active (sub) as the value?

**Comment by danielhb** [comment]
active and sub, but I see your point. We can add the 'load' value in a separated column, between 'name' and 'status'.

**Comment by samhenri** [comment]
I'm starting to develop this panel however I need some confirmation regarding the Autostart option. Please read this link:
http://ux.stackexchange.com/questions/63884/checkbox-vs-toggle

What are your thoughts about it? I tend to agree with the selected answer, the toggle switch can be confusing in desktop environments. If we provide labels for on-off then it could give wrong outputs for screen reader software as they would read both labels + the actual state of the switch. Plus, all UI kits and libraries that I've seen actually uses hidden checkboxes for this kind of switch anyway.
If you look into System Services like Windows and Gnome they all use checkboxes as well.

**Comment by danielhb** [comment]
@samhenri I will trust your judgement in this. If you're saying to use checkboxes, go for it.

**Comment by laggarcia** [comment]
@samhenri I trust your judgement as well.

**Comment by samhenri** [comment]
Almost done with this screen but I'm not sure of the columns order and the wok-checkbox:
![system-services-1](https://cloud.githubusercontent.com/assets/326107/15080126/f249dbe6-1392-11e6-9455-dbce67b99885.png)

-I thought about moving the Autostart column to display as the first column however this can mislead users to think they're selecting multiple rows. I'll try some variations showing On / Off label and post it here;
-wok checkbox is nice when you have labels but when you don't they look like static graphics and there's no indication they're interactive
-Not sure about the Details column order, maybe put it after Description? Details will always grow to the end of the table if we leave the way it is.
-OR move Description to Details hidden panel and display above the process.
-Should we add some icons to the Status and Loaded? I'm thinking displaying Loaded as the first column and showing the default power-on / power-off icon we use for Kimchi networks and storage pools. For the Status we could use Bootstrap labels or badges: http://getbootstrap.com/components/#labels

**Comment by danielhb** [comment]
"I thought about moving the Autostart column to display as the first column however this can mislead users to think they're selecting multiple rows. I'll try some variations showing On / Off label and post it here;
Wok checkboxes are nice when they have labels but when they don't, they look like static graphics and there's no indication they're interactive. Maybe the toggle display isn't so bad after all."

Yeah, I guess it's worth changing it to a toggle display to see if it feels more natural

"Not sure about the Details column order, maybe put it after Description? Details will always grow to the end of the table if we leave the way it is.
OR move Description to Details hidden panel and display above the "Process" header."

You can put Details after Description and put a cap on how much characters
you'll show in the Description column to avoid drive the Details column
too far out. If you put the full Description field in the hidden panel too then
there's no loss in putting this cap.

"Should we add some icons to the Status and Loaded? I'm thinking displaying Loaded as the first column and showing the default power-on / power-off icon we use for Kimchi networks and storage pools. For the Status we could use Bootstrap labels or badges: http://getbootstrap.com/components/#labels"

In my opinion, no. I believe the textual values will speak more for people that are used to command-line systemd. If we put icons in those values the person can get confused because there are a lot of status, people might get confused about 'is icon means the process exited or failed?' and the will end up open up the Details pane to see the textual info.

**Comment by samhenri** [comment]
This is what the autostart column would look like with texts:
![system-services-2](https://cloud.githubusercontent.com/assets/326107/15080833/463433d4-1396-11e6-86bd-7046af94037c.png)

As for the status column, I wasn't thinking about hiding the text, but using and icon or colored label to represent the status. Running as green, failed as black / dark red / exited as red. The same way we display the plugins names in the User Log screen.

**Comment by danielhb** [comment]
Not sure about the texts in the autostart with the checkbox. I am really curious about how the toggle on/off button would look like though.

```As for the status column, I wasn't thinking about hiding the text, but using and icon or colored label to represent the status. ```

If  you're talking icon + text, go for it.

**Comment by samhenri** [comment]
Compact version in small screen. CSS3 Flex-box does the trick, I think we can keep the Description column where it is:
![system-services-3](https://cloud.githubusercontent.com/assets/326107/15081738/a5dd8656-139a-11e6-88ea-f9f2a115302a.png)

**Comment by danielhb** [comment]
Looking good

if @laggarcia or @alinefm or @sstoppler has no objections, I believe you can send it to the ML and we can discuss it there

**Comment by samhenri** [comment]
One more option. These are the labels and icons I'm trying with the Status. In this case I think it would be a good idea to separate the "Active" from the "Status" column because the icon is displayed before "Active". In some terminals "active" is displayed with red color or with white background.

![system-services-4](https://cloud.githubusercontent.com/assets/326107/15082390/d000b392-139d-11e6-8cec-ba1f64ab5eea.png)

**Comment by samhenri** [comment]
Toggle Switch variation:
![toggleswitch](https://cloud.githubusercontent.com/assets/326107/15083428/7ea628b4-13a3-11e6-8b9a-157a3b00bb9e.png)

**Comment by laggarcia** [comment]
Either way is good to me regarding toggle switches and check boxes.

I liked the text with icons and colorful background.

**Comment by samhenri** [comment]
Almost finishing. I'm sticking with the toggleswitch. After further reading in this context it makes sense to use this element instead of a checkbox. I just need to confirm something. What should we do once the user enable or disable auto-start? Should we display a message or add to wok.notifications? For now it only shows a message when it has failed to disable/enable.

**Comment by samhenri** [comment]
I wrote a refresh table function to be called once each service is stopped, restarted or started but I was thinking that this may cause some performance issues with the browser window, Do you think we should refresh each row at time?

**Comment by danielhb** [comment]
For autostart enable-disable we can update only the service row.

For start/stop/restart we can refresh the whole frame because there's always a chance that the change of status in a service might affect other running/stopped ones.

**Comment by samhenri** [comment]
Patch sent to Ginger Group. The refresh on the table is silent and it may look like the table wasn't refreshed but if you insert a breakpoint on DOM change, the browser you will see that the table gets rebuilt after calling start, stop or restart buttons.
I wasn't able to test if a refresh delay is necessary because all my services failed to start or stop, but I put a success message claiming that the start, stop or restart process has started successfully, it doesn't mean that the service is in fact running.
