### ISSUE TITLE
Gateway field in Global Network configuration taking invalid values.

### ISSUE THREAD

**Issue by atreyeemukhopadhyay** [kimchi-project/ginger#328]
From UI user is able to enter a blank line, and or any text or numbers as an IP as a valid entry in Gateway field.
Specials characters are the only thing that drives the entry line into a 'invalid' state, and will not allow it.

![gateway](https://cloud.githubusercontent.com/assets/13199397/14782573/df104f9e-0b07-11e6-987c-906576b98af0.jpg)
![gateway2](https://cloud.githubusercontent.com/assets/13199397/14782608/041f38cc-0b08-11e6-8ff5-8833b5ddcdf4.jpg)

**Comment by danielhb** [comment]
Gateway field is now turning red for anything that's not a valid IP address:

![image](https://cloud.githubusercontent.com/assets/866780/16669163/710e9a9a-446a-11e6-9ccf-8b19deea29d4.png)

Closing the bug.
