### ISSUE TITLE
Software update not working in F23

### ISSUE THREAD

**Issue by danielhb** [kimchi-project/ginger#339]
I am having problems with this feature in current master, running Fedora 23.

The package list simply will not load in the UI after almost 5 minutes. When executing 'dnf update' in the terminal it is possible to force the backend to abandon the processing and the UI. A lot of messages like: 

```Problem in lookup of resource 'qt5-qtbase'. Detail: GGBPKGUPD0005E: There is a package manager instance running in the system. ```

Appears in the log and only a portion of the eligible packages shows in the UI. At this moment I have:

Transaction Summary
=================================================================================================
Install    5 Packages
Upgrade  198 Packages
Remove     3 Packages

I know that this is quite a bit of packages but this is not usual. It shouldn't take more than 5 minutes to load. It's hard to know whether this is simply the UI/backend taking too long to load or there is an uncaught problem in the middle that is halting the operation.

I'll mark this as both backend and frontend because I am not sure who is to blame in this case. @pvital @peterpennings  please take a look into this when you can.

@peterpennings no point into testing the UI of updating only the selected packages if we can't figure this out first.

**Comment by laggarcia** [comment]
@danielhb, have you tried to run dnf from command line? The reason I am asking is because since last week I am facing long delays while running dnf commands on Fedora 23 even from command line.

**Comment by pvital** [comment]
@danielhb the new code for package update needs scan for each package its dependencies and also which package provides these dependencies. Because of this new approach the time to build the list of packages to upgrade increased (and I know that increased a lot, specially when you have 198 packages to upgrade).

This approach were choose to make the dependency checking in UI faster, providing the list of packages and the dependencies list of each package together, just once.

**Comment by danielhb** [comment]
What commands the backend fires up in this case? 'dnf update' to fetch
the list of all packages to be updated and then 'update -v' to fetch
each dependency of each package?

I am asking because 'dnf update' runs quite fast here

**Comment by pvital** [comment]
@danielhb 

For Fedora systems, the code follows the following process:

1. GET on collection, that executes the command 'yum check-update -d0'  and creates a list of eligible packages to be updated;
2. for each item of the collection list is executed the command 'dnf -v --assumeno update <pkg_name>' that creates a dict with all necessary information (same of GET on resource).

The point is that in your case, the command of item 2 is executed 198 times.

BTW, software update is a GingerBase feature, not Ginger :-P
