### ISSUE TITLE
 Sysmodules HYGIENE - Scroll bar needed to scroll through the list of kernel modules on sysmodule tab

### ISSUE THREAD

**Issue by mesmriti** [kimchi-project/ginger#341]
Need to have a scroll bar to view the list of kernel modules in sysmodule tab.

**Comment by samhenri** [comment]
Do you mean putting the scrollbar inside the collapsible panel instead of the page?

**Comment by mesmriti** [comment]
yes. The scroll bar is needed to only to scroll through the list of modules available.

**Comment by danielhb** [comment]
Fixed by  707669b
