### ISSUE TITLE
User activity  - The user activity log not captured if the wok-req.log goes missing from the logging path

### ISSUE THREAD

**Issue by mesmriti** [kimchi-project/ginger#344]
#=== Problem Description ===================================
#===========================================================
The user activity log does not get  captured for all the user activities performed if the wok-req.log
goes missing from the /var/log/wok path or the specified path in wok.conf. The log gets generated again 
only when the wokd service is restarted.

#=== Steps to Reproduce ====================================
#===========================================================
1. Login to the machine from the UI screen.
2. Remove the wok-req.log from the /var/log/wok path.
3. Perform some user activity from the UI page.
4. Check for activity log on the UI.

**Comment by sureshab** [comment]
@mesmriti 
Please raise issue in "wok" since "Activity log" is part of wok
