### ISSUE TITLE
API.md file needs to update for the collection/resource -  interfaces

### ISSUE THREAD

**Issue by jay-katta** [kimchi-project/ginger#35]
API.md needs to be update for the following Collection-
URI:  /plugins/ginger/network/interfaces

API.md needs to be update for the following resource-
URI: /plugins/ginger/network/interfaces/:name

**Comment by jay-katta** [comment]
I am working on this issue.

**Comment by danielhb** [comment]
@jay-katta you still interested in working in this documentation or can I do it?

**Comment by jay-katta** [comment]
Yes, I will be working on it. 
Today by EOD will be sending the patch
