### ISSUE TITLE
A black horizontal tab on Host Network configuration info is being shown

### ISSUE THREAD

**Issue by sstoppler** [kimchi-project/ginger#350]
1.  Navigate to 'Host' Frame, move to 'Network' tab and click on 'Network Configuration'.

A black tab(which shows version of Wok) is being displayed on the Network configuration info.
When we have SRIOV VFs  probed on the host and number of ifaces increase we see this issue.

![blackbox](https://cloud.githubusercontent.com/assets/11432111/15551234/efaa2a72-2269-11e6-8533-6888a30f8d12.jpg)

**Comment by samhenri** [comment]
Need more details such as:
-Browser
-Screen resolution

The only way I see this happening is if "#network-content-area .bootgrid-table" removes its height value.

**Comment by laggarcia** [comment]
I think @alinefm was able to reproduce this issue.

**Comment by sstoppler** [comment]
I think the key here is to have many network interfaces in your environment.

**Comment by samhenri** [comment]
I do have lots of interfaces here and the table keeps the scrollbar. Tested in a VM:
![networks](https://cloud.githubusercontent.com/assets/326107/15614347/a9b57eb2-240e-11e6-8de3-027462d7e75a.png)

**Comment by samhenri** [comment]
I can't reproduce a mlx5_core environment here but I think the problem lies with jQuery Bootgrid. We had a similar issue with the Update that was solved with a $().bootgrid('reload') call.

**Comment by alinefm** [comment]
Hi @samhenri 

I saw that while accessing Ginger on Firefox 46.0.1 and screen resolution was 1600x900 pixels
Hope that helps.

**Comment by samhenri** [comment]
@alinefm Yes it does. I think the root cause is that once SR-iOV is enabled and the interfaces are added to the table, jQuery Bootgrid is not refreshed and then this breaks the table styles. The pagination text appears in the same position that it was before enabling SR-IOV.
I've tried but I can't reproduce it here, but I think if we add something like this: 
$("#grid").bootgrid("refresh");
Each time an interface is added to the table, it might fix this problem.

**Comment by samhenri** [comment]
@alinefm I just had an idea. Can you inspect this page with Chrome and copy the HTML content for me?

![chromedevtools](https://cloud.githubusercontent.com/assets/326107/16014930/da6df738-3169-11e6-88ee-115f5e3eaf37.png)

**Comment by sstoppler** [comment]
Request made to test to retry as it may have already been fixed by another patch.

**Comment by danielhb** [comment]
I couldn't reliably reproduce this issue on both Chrome and Firefox running Ginger in a machine with 45 network interfaces. It was probably fixed along the way.

Reopen this bug if the issue reappears.
