### ISSUE TITLE
RFC : iSCSI initiator support from Ginger

### ISSUE THREAD

**Issue by harche** [kimchi-project/ginger#353]
Ginger already supports storage devices from transports like DASD and FC. We are proposing to expand this offering to include iSCSI transport as well. To begin with we would like to add iSCSI initiator support from Ginger, which could later be followed by iSCSI target configuration as well. But this RFC will focus on iSCSI initiator functionality only. This will users to use iSCSI target block devices and perform operations already support by Ginger on them (e.g. partitioning, file system formatting, LVM etc.)
### Collections: IQNs (iSCSI Qualified Name)

**URI:** /ginger/iscsi/iqns

**Methods:**
- **GET**: Return the list of IQNs (iSCSI Qualified Name) already discovered on the system.
- **POST**: perfoms login to iscsi target with respective iqn. After a successful login, a corresponding block device should appear in /ginger/stgdev API.
  - iqn - IQN string (e.g. iqn.2015-06.com.example:target1)
  - username (optional) : Username for the iSCSI Target authentication 
  - password (optional) : Password for the iSCSI Target authentication
### Resource: IQN (iSCSI Qualified Name)

**URI:** /ginger/iscsi/iqns/_:iqn_

**Methods:**
- **GET**: Retrieve the information about specific IQN
  - name: IQN 
  - port : Port on the iSCSI Target
  - ip_address : IP Address of the iSCSI Target
  - discovey_address : Discovery address used for IQN
- **DELETE** : Delete an IQN

**Actions (POST):**
- discover: Discover the available IQNs for the given iSCSI target
  - target_ip : IP Address of the iSCSI Target

**Comment by danielhb** [comment]
This has been implemented a while ago
