### ISSUE TITLE
RFC : List of NFS exports from the remote NFS server

### ISSUE THREAD

**Issue by harche** [kimchi-project/ginger#354]
We already have an ability to mount a NFS file system using Ginger (POST on /plugins/ginger/filesystems). That API takes following input,

   For NFS mount:
       * server : ip address of the remote NFS server
       * share : location of the remote share
       * mount_point : Mount point for the filesystem

While implementing UI, it occurred to us that users might make mistakes in typing the path of the 'share' field there. In order to minimize these potential human errors we are proposing to get the list of shares for the given NFS server automatically (using `showmount -e ip_addr` command) and user just selects the list of NFS shares from a drop down instead of manually typing the path.  

### SimpleCollection: List of NFS exports (shares) on given server

**URI:** /plugins/ginger/nfsshares/:ip_address

**Methods:**

* **GET**: Retrieve a summarized list of all NFS shares for the given NFS server

**Comment by danielhb** [comment]
Backend was implemented upstream.
