### ISSUE TITLE
Refreshing volume groups keeps on loading

### ISSUE THREAD

**Issue by sstoppler** [kimchi-project/ginger#360]
Issue:
Refreshing 'Volume Groups' keeps on loading, waited more than 10 minutes, it still kept on 'loading'.
It is good to have a message if it does not find any groups rather than keeps on loading.

How to reproduce:
1. Navigate to 'Host' Frame, move to 'Storage' tab and click on 'Volume Group'.
3. Click on 'Refresh'

It keeps on on 'loading'.

logs from wok-error.log :
==========================
rc: 5 error: File descriptor 3 (/var/log/wok/wok-req.log) leaked on vgs invocation. Parent PID 5878: python2
File descriptor 8 (/var/log/wok/wok-error.log) leaked on vgs invocation. Parent PID 5878: python2
File descriptor 11 (/dev/urandom) leaked on vgs invocation. Parent PID 5878: python2
File descriptor 21 (/var/log/wok/wok-access.log) leaked on vgs invocation. Parent PID 5878: python2
File descriptor 35 (/dev/mapper/control) leaked on vgs invocation. Parent PID 5878: python2
File descriptor 64 (socket:[1156766]) leaked on vgs invocation. Parent PID 5878: python2
  Volume group "rhel" not found
  Cannot process volume group rhel
 returned from cmd: vgs -o vg_name
GINVG00007E: vgs command failed
failed to list VGs
GINVG00002E: Failed to list VGs

Notes from @Truja 
I could reproduce the problem, making the command "vg -o" fail.
Backend returns the error properly, but UI is not handling it.
Did not check the code, but, maybe it is just a matter of add the error handling function in the Java Script.

**Comment by samhenri** [comment]
I think I found the problem but I can't reproduce the error here. I'm sending a patch to check.

**Comment by samhenri** [comment]
Sent a patch adding error message containers to the HTML and function(err) to Json requests. Not sure if it will check the main issue but at least it should display error messages properly.

**Comment by sstoppler** [comment]
Was able to reproduce the problem using another system (one that has no volume groups) and once the patch was applied, clicking on the Refresh button briefly shows the loading icon and then disappears and the message that states 'No Results Found' is shown.
