### ISSUE TITLE
Retrieval of tasks using Task API fails

### ISSUE THREAD

**Issue by pawankg** [kimchi-project/ginger#37]
Retrieval of tasks using Task API fails

I am using task API for DASD formatting. It is generating a task when I run the code.
[root@zfwcec164 ginger]# curl -k -u root -H "Content-Type: application/json" -H "Accept: application/json" -X POST -d '{"blk_size" : "4096"}' https://9.152.151.164:8001/plugins/ginger/dasddevs/0.0.0224/format

{
  "status":"running",
  "message":"OK",
  "id":"1",
  "target_uri":"/dasddevs/dasdc/blksize/4096"
}

But when I am trying to retrieve task status using task api to see whether it is finished or not, it is returning an empty list.
[root@zfwcec164 ginger]# curl -k -u root -H "Content-Type: application/json" -H "Accept: application/json" 'https://9.152.151.164:8001/tasks'                 
[]

When I am trying to retrieve task status with task api using task_id, it is giving this error.
[root@zfwcec164 ~]# curl -k -u root -H "Content-Type: application/json" -H "Accept: application/json" 'https://9.152.151.164:8001/tasks/1'                    

{
  "reason":"WOKOBJST0001E: Unable to find 1 in datastore",
  "code":"404 Not Found"
} 

But then I tried looking at task data stored in wok objectstore_ginger database. From database, I can see the information saved inside the database but the task api is not able to fetch it.  

[root@zfwcec164 ginger]# sqlite3 /var/lib/wok/objectstore_ginger
SQLite version 3.7.17 2013-05-20 00:56:22
Enter ".help" for instructions
Enter SQL statements terminated with a ";"
sqlite> .dump
PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE objects
                (id TEXT, type TEXT, json TEXT, PRIMARY KEY (id, type));
INSERT INTO "objects" VALUES('1','task','{"status": "finished", "message": "OK", "id": "1", "target_uri": "/dasddevs/dasdc/blksize/4096"}');
COMMIT;
sqlite> ;
sqlite> .quit

It seems that Task API is trying to fetch task information from wok objectstore and not from wok objectstore_ginger, due to which it is returning empty list.

Do some update in code is required or am I accessing the task in some wrong way here?

**Comment by danielhb** [comment]
I'll require some digging because TBH I have no idea. I don't know if this is even a Ginger issue or a WoK one.

I'll ask the WoK maintainer (Aline) about it.

**Comment by danielhb** [comment]
I've checked one Kimchi API test I've made recently and there I retrieved the task status using this uri:

`/plugins/kimchi/tasks/%s`

Where '%s' is replaced by the task id. Perhaps ginger tasks are now being accessed by the `/plugins/ginger/tasks/ %s ` API after changing to WoK and now we need to update the docs. Can you verify if this URI works?

**Comment by pawankg** [comment]
Hi Daniel,
Thanks for your input. I also tried with updated API /plugins/ginger/tasks/ %s, but it is not giving any task related information.

```
[root@zfwcec164 ~]# curl -k -u root -H "Content-Type: application/json" -H "Accept: application/json" -X POST -d ':8001/plugins/ginger/dasddevs/0.0.0224/format
{
  "status":"running",
  "message":"OK",
  "id":"2",
  "target_uri":"/dasddevs/dasdc/blksize/4096"
}

[root@zfwcec164 ~]# curl -k -u root -H "Content-Type: application/json" -H "Accept: application/json" 'https://9.152.151.164:8001/plugins/ginger/tasks/2'
{}
```
The updated API also don't seems to be working to fetch the task information.

**Comment by danielhb** [comment]
Yeah ... it appears that a patch will be required. There were changes introducing WoK that will require extra code in Kimchi.

I'll look into it.

**Comment by chandrureddy** [comment]
Daniel, Any update on this code changes ?
Thanks in advance !!!

**Comment by danielhb** [comment]
I'll speak with the WoK guys to see if they're working in it. Otherwise we'll probably need to investigate it ourselves.

Is this issue blocking any other feature/work? If that's the case I'll prioritize it

**Comment by chandrureddy** [comment]
Yes Daniel. We should prioritize this as it is stopping on few 
implementations in the storage/network areas which needs task api.

**Comment by danielhb** [comment]
I've talked with the WoK folks and they have the unification under their radar, but with no ETA unfortunately. So I'll patch in the task API support for Ginger and s390x myself. 

I expect to send a fix for this in a few days.

**Comment by chandrureddy** [comment]
Daniel, FYI s390x task API code works fine.

**Comment by danielhb** [comment]
Good to know. One less thing to worry about :)

Although it is funny that it works. Probably s390x already contemplated the model changes required when it was created

**Comment by danielhb** [comment]
update: after starting working in this issue and trying to make a test case for it I've found out, speaking with @alinefm , that Kimchi is holding some stuff in its tests/utils.py that should be moved on to WoK. This will require some changes in WoK as well to export its wok.utils properly so other plug-ins can use its functions.

I'll attend to it at Kimchi (will probably create an issue for that) and, at the same time, see if I can get our side fixed as well.

**Comment by danielhb** [comment]
I'll be sending a patch to solve the WoK part soon ( kimchi bug https://github.com/kimchi-project/kimchi/issues/760 ). While it's under review I'll resume workiing in the task API issue described here.

**Comment by danielhb** [comment]
There is an issue with how current WoK is loading existing objstores from Ginger and Gingerbase due to changes in WoK/Kimchi master. This needs to be fixed before I can proceed with this issue because the tasks backend uses the objectstore.

This WoK issue was created here: https://github.com/kimchi-project/kimchi/issues/764

**Comment by danielhb** [comment]
The patches that fixes this issue are *finally* available upstream!

@pawankg can you please verify if the fix works for you? Remember that the Task API for ginger is accessed by the ```/plugins/ginger/tasks/ ``` URI. If the fix works for you, please close this issue.

**Comment by danielhb** [comment]
@pawankg I'll close this issue because other developers are already using the Task API from Ginger without any issues

Let me know if you are still getting issues with it. Then we can reopen this issue or create a new one.

Thanks!
