### ISSUE TITLE
Creating disk partitions is not updated to take integer input for size

### ISSUE THREAD

**Issue by pkulkark** [kimchi-project/ginger#371]
The API for creating disk partitions should be changed to accept integer input for size parameter. The size passed should be in MBs.

**Comment by pkulkark** [comment]
I will be sending a patch for this

**Comment by danielhb** [comment]
I think we need to standardize the unit size of these storage related features. bug https://github.com/kimchi-project/ginger/issues/226 complains about some units being on Gigabytes, others on megabytes.
