### ISSUE TITLE
Unable to edit the text field or click submit/cancel after press ESC or click outside the error message dialog of Add User

### ISSUE THREAD

**Issue by atreyeemukhopadhyay** [kimchi-project/ginger#376]
While trying to create a new user in Administration tab, user inputs unmatched password and click submit

error message was displayed to notify user that password and confirm password does not match.
User is unable to edit the fields after clicks out side the error message.
The text fields can not edited after user press ESC too.
![143565-1](https://cloud.githubusercontent.com/assets/13199397/17358137/f2fe39c0-597d-11e6-9de6-71ed22e21aec.jpg)

![143565-2](https://cloud.githubusercontent.com/assets/13199397/17358205/5732d572-597e-11e6-8dc6-a5cb6a925a16.jpeg)

**Comment by danielhb** [comment]
I saw that the patch was sent to WoK, I'll take a look and see if this behavior can be seen in other plug-ins too and if the patch fixes all of them.

Now, what's up with this 'Confirm' and 'Cancel' window in this case. "Password does not match" and user press Cancel means what? "I am the user and the password matches"? hehehe

We need to change this dialog to be a simple "Ok" button.

**Comment by danielhb** [comment]
Even if we change the dialog we can't let the existing window broken. The bug was fixed upstream and a new bug to change the window will be opened.
