### ISSUE TITLE
Change confirmation dialog of password mismatch in Add User window

### ISSUE THREAD

**Issue by danielhb** [kimchi-project/ginger#378]
![image](https://cloud.githubusercontent.com/assets/866780/17370680/54ebf254-5973-11e6-9265-dbbe9a93e91d.png)

his screenshot was taken from a (now closed) bug @atreyeemukhopadhyay opened

It makes no sense asking "Confirm" and "Cancel" in this scenario. What does "cancel" do? Abort the add user operation? 

We need to either change it to be only a single "Ok" button or make it clearer in the modal what happens when pressing "Cancel"

**Comment by alinefm** [comment]
The error message should be displayed in the same way the other error messages are: in the red box in the dialog view, instead a popup.
