### ISSUE TITLE
audit backend isn't including User Log messages

### ISSUE THREAD

**Issue by danielhb** [kimchi-project/ginger#380]
Audit backend went upstream without proper User Log behavior.

**Comment by danielhb** [comment]
@lcorreia added you as assignee too but no rush. I'll try to fix it myself when I can

**Comment by lcorreia** [comment]
I'm reverting some commits to use present verbs again in user log messages and can leverage the opportunity to review all plugins for missing messages, aiming to test this only once.

**Comment by lcorreia** [comment]
Sent fix to ML

**Comment by alinefm** [comment]
@lcorreia @danielhb What is the status? Was the patch merged?

**Comment by lcorreia** [comment]
Yes, commit 10af984cf47d9f0cfd7abbaa2a2a509a3efa8e4d .
