### ISSUE TITLE
Failed to import plugin plugins.ginger.Ginger

### ISSUE THREAD

**Issue by chandrureddy** [kimchi-project/ginger#39]
Failed to import plugin plugins.ginger.Ginger 

because model/utils.py is referring to 
from wok.plugins.kimchi.disks import _get_dev_major_min
from wok.plugins.kimchi.disks import _get_dev_node_path

> /usr/lib/python2.7/site-packages/wok/plugins/ginger/models/model.py(35)<module>()
-> from users import UsersModel, UserModel
(Pdb) n
> /usr/lib/python2.7/site-packages/wok/plugins/ginger/models/model.py(36)<module>()
-> from swaps import SwapsModel, SwapModel
(Pdb) n
ImportError: 'No module named kimchi.disks'
> /usr/lib/python2.7/site-packages/wok/plugins/ginger/models/model.py(36)<module>()
-> from swaps import SwapsModel, SwapModel
(Pdb) c

**Comment by danielhb** [comment]
Nice catch. Only happened because you've ran Ginger without Kimchi I believe.

We'll need to either move this to WoK or import it to Ginger. I guess the first option is better because it avoids duplicating code. Any comments, @alinefm  ?

**Comment by danielhb** [comment]
Moving to ginger-base is another option as well

**Comment by alinefm** [comment]
Hi @danielhb! Hi @chandrureddy!

Wok should only contain what is needed to start up the web server. So it is not a option for this. 
I suggest move the common code to ginger-base and adjust the imports in Kimchi and Ginger.

**Comment by danielhb** [comment]
Thanks for the input @alinefm !

For anyone willing to solve this issue: be careful with adjusting Kimchi imports. They'll not appear only as 'wok.plugins.kimchi.disks' but also as 'import disks' in all the source files inside /plugins/kimchi/model/ dir. 

I can work in this after fixing #37 .

**Comment by pkulkark** [comment]
Hi @danielhb 

I will be taking care of this in my next patch.

**Comment by danielhb** [comment]
Thanks @pkulkark

**Comment by danielhb** [comment]
This bug was referring specifically to errors in the the 'disks' module. These errors were fixed upstream a while ago.
