### ISSUE TITLE
Ubuntu-16.04: Make Network Configuration able to manage with /etc/network/interfaces

### ISSUE THREAD

**Issue by pvital** [kimchi-project/ginger#390]
Using Ubuntu 16.04 and https://github.com/lcorreia/ginger/commit/89bf175d2ae7593245f21f5b66868e7bf8ed171f as HEAD, I got the error " Persistent file is not available for interface ens7." when trying to edit a network card (even it's up or down).

![screenshot from 2016-09-13 16-00-05](https://cloud.githubusercontent.com/assets/699330/18487456/b767effa-79cb-11e6-82f9-2537e4a4afaf.png)

From wok-error.log I got:

```
Reading ifcfg file for interface ens7
ifcfg file not exist for interface :ens7
GINNET0080E: Interface 'ens7' doesn't exist. Please refresh the network list to fetch the latest list of interfaces
```

**Comment by ramonmedeiros** [comment]
Ginger is pointing incorrectly to network file (/etc/sysconfig/network-scripts/ifcfg) instead of /etc/network/interfaces. Also, the parser isn't able to work with /etc/network/interfaces

**Comment by ramonmedeiros** [comment]
Reproduced with SuSE. Same error: ginger is pointing to /etc/sysconfig/network-scripts/ifcfg, instead of /etc/sysconfig/networks/ifcfg
