### ISSUE TITLE
Ubuntu-16.04: Unable to turn on and off a network card

### ISSUE THREAD

**Issue by pvital** [kimchi-project/ginger#393]
Using Ubuntu 16.04 and lcorreia@89bf175 as HEAD, I got the error " Failed to bring up the interface ens7. GINNET0016E: Unable to activate the interface on 'ens7', 'Unknown interface ens7 '." when trying to turn down a network card.

![screenshot from 2016-09-13 16-16-18](https://cloud.githubusercontent.com/assets/699330/18487986/d69bbdfa-79cd-11e6-98c0-e98e89cbeddf.png)

From wok-error.log I got:

```
Activating an interface ens7
rc: 1 error: Unknown interface ens7
 returned from cmd: ifup ens7
GINNET0016E: Unable to activate the interface on 'ens7', 'Unknown interface ens7
```

After enter the command 'sudo ifconfig ens7 up' on console, I could see the interface activated on network tab, and when trying to deactivate it, I got the error " Failed to bring down the interface ens7. GINNET0017E: Unable to deactivate the interface on 'ens7', 'Unknown interface ens7 '." 

![screenshot from 2016-09-13 16-05-41](https://cloud.githubusercontent.com/assets/699330/18487578/30693bd4-79cc-11e6-88ef-f66371b1d789.png)

From wok-error.log I got:

```
Deactivating an interface ens7
rc: 1 error: Unknown interface ens7
 returned from cmd: ifdown ens7
GINNET0017E: Unable to deactivate the interface on 'ens7', 'Unknown interface ens7
```

**Comment by lcorreia** [comment]
Not reproducible on Ubuntu 16.10.
