### ISSUE TITLE
Ubuntu-16.04: Delete network configuration disable

### ISSUE THREAD

**Issue by pvital** [kimchi-project/ginger#394]
Using Ubuntu 16.04 and lcorreia@89bf175 as HEAD, the option to delete any selected network configuration is always disabled:

![screenshot from 2016-09-13 16-44-09](https://cloud.githubusercontent.com/assets/699330/18488844/89325778-79d1-11e6-9f96-b745654db4e4.png)

**Comment by ramonmedeiros** [comment]
According to @danielhb, NIC interfaces are not allowed to be deleted (This behaviour happens in all distros).

Can i close this issue?
