### ISSUE TITLE
Ubuntu-16.04: Error in listing pre-discovered iSCSI targets

### ISSUE THREAD

**Issue by pvital** [kimchi-project/ginger#400]
Using Ubuntu 16.04 and lcorreia@89bf175 as HEAD, the GINISCSI005E error message is presented on iSCSI tab and no more information  is provided:

![screenshot from 2016-09-14 10-55-16](https://cloud.githubusercontent.com/assets/699330/18514963/f44403ca-7a69-11e6-9590-651c9499a288.png)

The same message is presented in wok-error.log:

```
GINISCSI005E: Error in listing pre-discovered iSCSI targets - 
```

**Comment by biancafc** [comment]
Same error with Fedora 24.

**Comment by alinefm** [comment]
Similar to #383 ?

**Comment by pvital** [comment]
@alinefm yes, they are the same!

**Comment by alinefm** [comment]
I will close it so and use #383 to track this issue.
