### ISSUE TITLE
Volume Group list is not getting refreshed post deletion of volume group.

### ISSUE THREAD

**Issue by atreyeemukhopadhyay** [kimchi-project/ginger#437]
This issue is reproducible when list is having single record and we try to delete the same.
After successful deletion list still shows the record.

![vg1](https://cloud.githubusercontent.com/assets/13199397/19180472/abf7538e-8c83-11e6-92df-68ee3c68878b.jpg)
![vg del 2](https://cloud.githubusercontent.com/assets/13199397/19180474/b035bfbc-8c83-11e6-870e-4022d75316a8.jpg)

**Comment by danielhb** [comment]
Fixed by 924b7260f9a65c9b4746acee8c854c4d626c9b6f
