### ISSUE TITLE
make check-local must verify trailing whitespaces in docs/API.md

### ISSUE THREAD

**Issue by danielhb** [kimchi-project/ginger#44]
Because seeing the whitespaces appearing after applying a patch is killing my vibe.

**Comment by pvital** [comment]
"...killing my vibe."??!!
LOL

**Comment by danielhb** [comment]
Patch was sent to ML. Hopefully my vibe will survive until it's fixed!

**Comment by danielhb** [comment]
Fix is available upstream! Rejoice!
