### ISSUE TITLE
Validation failing for DNS field in Global Network Configuration

### ISSUE THREAD

**Issue by atreyeemukhopadhyay** [kimchi-project/ginger#447]
In Global Network Configuration section of Network tab, input value for DNS field is not getting validated against IPv4 , Ipv6 or hostname.
User is able to provide any arbitrary value.

![dns](https://cloud.githubusercontent.com/assets/13199397/19640360/dad424c4-99f9-11e6-9f48-4ee4d5a4d2ae.jpg)

![network](https://cloud.githubusercontent.com/assets/13199397/19640172/29bdcb7c-99f9-11e6-9467-c08c8c436025.jpg)

![net](https://cloud.githubusercontent.com/assets/13199397/19640259/7efa81d4-99f9-11e6-83dd-311ab6947f19.jpg)

**Comment by danielhb** [comment]
Fixed by 1346ba3b445504f1c0f060fa13486c628a83fa01
