### ISSUE TITLE
Ginger : Removal of libvirt dependency on interfaces

### ISSUE THREAD

**Issue by chandrureddy** [kimchi-project/ginger#45]
Ginger : Removal of libvirt dependency  on interfaces

Ideally All host management plugins should not have any dependency on libvirt or any KVM components as such these plugins can be very well used on machines with out KVM installed. 

So I guess forward we should eliminate such dependencies whenever possible.

**Comment by danielhb** [comment]
Do you know which libvirt dependencies we have left?

**Comment by chandrureddy** [comment]
network.py and interfaces.py are still referring to libvirt directly. 
models/network.py:23:import libvirt
models/interfaces.py:21:import libvirt

**Comment by danielhb** [comment]
I believe the removal of libvirt is related with the new network APIs, such as the cfginterface. To fully remove libvirt we'll need to make this new network backend to work at least the same way the current backend does, and with Ubuntu support. I understand that the Ubuntu support is lacking/none in the cfginterface API and this is something that's under my radar after 2.0.

**Comment by danielhb** [comment]
Now that we have the new network UI are we still relying on libvirt? After fixing cfginterfaces to work with Ubuntu and Opensuse I do believe libvirt will be gone.


I'll put this to Ginger 2.1 because I really think we can make this change to the next  release.

**Comment by chandrureddy** [comment]
Daniel, new network UI is using the API "URI: /plugins/ginger/network/interfaces" which is right now have libvirt dependency back end. I guess it is matter of time we can eliminate this dependency.

**Comment by danielhb** [comment]
Well, this is actually fortunate. It means that the network UI isn't broken in Ubuntu and openSUSE as I thought it would. 

I'd say that we need to fix bugs #93  and #94  before thinking about moving the UI from /network/interfaces API to the /cfginterfaces API ... or we can remove the libvirt code inside the network/interfaces API. Whatever works better

**Comment by chandrureddy** [comment]
Yes. I agree.

**Comment by danielhb** [comment]
I am changing the milestone back to Backlog. Reason is that Debian/Ubuntu networking differs from what we've been doing with cfginterfaces for Fedora/RHEL in such a great deal that I am skeptical about adapting it for those OSes.

Libvirt, as hard as it is to admit it, is an OK solution for handling the network config there. We can remove libvirt dependency from Fedora/RHEL and even openSuse though.

**Comment by danielhb** [comment]
This was done by @jay-katta in the following commits:

337bf95757a06117f8b9053669f2d31a09817aa8
9430c8c8c2f954f7c1e76f0b49cc682af71f19e1
7328bfb023976f8532afac2086e4dd0b94fff37f
