### ISSUE TITLE
File system filter not working.

### ISSUE THREAD

**Issue by atreyeemukhopadhyay** [kimchi-project/ginger#454]
Firebug is displaying javascript error when user tries to filter file system data. It's preventing the filter functionality and even after having matching data only loading message is displayed in place of filter data.

![filter](https://cloud.githubusercontent.com/assets/13199397/19917690/728c91fa-a0eb-11e6-8e71-61bac0f01d66.jpg)

![fs filter](https://cloud.githubusercontent.com/assets/13199397/19917641/0762c7b4-a0eb-11e6-9684-6628b666034e.jpg)

**Comment by danielhb** [comment]
Fixed by 1bb2ec574a63b5170aa070c282d835f83b269c89
