### ISSUE TITLE
UI issues related to Volume group

### ISSUE THREAD

**Issue by atreyeemukhopadhyay** [kimchi-project/ginger#458]
1)Add in Vg → select a physical volume → instead of done press next → press previous --- Done option not there to create VG. Done option should be available when previous is clicked.
2)In resize Add in Vg → select a physical volume → instead of done press next → previous --- Done option not there to create VG. Done option should be available when previous is clicked.
3)Label for volume group creation steps should be improvised for user understanding.
4)Instead of Create PV button in the add feature, Pv creation can be achieved with Next button click.
5)Resize button does not give any warning when clicked without selecting any vg.
6)Steps description strings should be externalized.

**Comment by danielhb** [comment]
Fixed by 7447ed26fd0f33f82f3b66af2c908832a58039a3
