### ISSUE TITLE
[TODO] Write unit tests for the feature, Delete an interface of type "Vlan" and "Bond" 

### ISSUE THREAD

**Issue by jay-katta** [kimchi-project/ginger#46]
Write unit tests for the feature, Delete an interface of type "Vlan" and "Bond"

**Comment by danielhb** [comment]
@jay-katta  let me know if you're going to work in this issue

**Comment by jay-katta** [comment]
yes, I will be working on this issue

**Comment by danielhb** [comment]
Unit tests were written by Jay a while ago.
