### ISSUE TITLE
UI issues for System Call rule

### ISSUE THREAD

**Issue by atreyeemukhopadhyay** [kimchi-project/ginger#463]
1)Not able to add system rules with Fields as key.
Click on Add rules and add with type system call rules, action always, filter exit, system calls fork, Fields key = abc and key name as abc.
Click on save. It gives error message like "Execution of auditctl command failed with error 'Error sending add rule data request (invalid argument)".

![1](https://cloud.githubusercontent.com/assets/13199397/20133179/6e47648e-a68c-11e6-9649-594c3b1011f8.jpg)

2)UI breaks if add all system calls are added in the rule.
UI is not able to handle showing detail info of rules properly if it has rules has all system call added in it.
(or more than certain count).
![3](https://cloud.githubusercontent.com/assets/13199397/20133267/d9cbc6c8-a68c-11e6-8c64-f2b6a19db18f.jpg)

3)Not able to delete a rule with operator like < or > <= or >= added in fields.

4)Not able to add path as field in system call rules.
Edit one of system call rules and add field as path and its value as /etc/passwd. Click on save it failed with error "Nothing matches the given URI" 
![4](https://cloud.githubusercontent.com/assets/13199397/20133301/0a5973d0-a68d-11e6-83e9-a10ff93fe938.jpg)

**Comment by danielhb** [comment]
Fixed by 3c3bcd40b09cb80df0118b21961e77d154fb0b68
