### ISSUE TITLE
 [Audit] Minor UI and Backend issues related to Audit Logs

### ISSUE THREAD

**Issue by mesmriti** [kimchi-project/ginger#468]
#=== Problem Description ===================================
#===========================================================
Issues are related to Audit log in Ginger Plugin --> Administration tab

1. No error is shown when wrong Audit file is given.
ausearch -if <filename>
2. Invalid output is shown when valid Audit event ID is given
ausearch -a 123
3. Invalid output is shown when valid Syscall Exit code is given
ausearch -e -13
4. Invalid output is shown when valid success value is given
ausearch -su 12
5. No error message is shown when non numeric value is given

#=== Steps to Reproduce ====================================
#===========================================================
Go to Host --> Administration tab, under Audit log section
1. Audit log -->Filter log --> log file name
2. Audit log -->Filter Log-->Add new filter-->Audit event ID - value 123
3. Audit log -->Filter Log-->Syscall Exit code - value 13
4. Audit log -->Filter Log-->Success value - value 12
5. Audit log -->Filter Log - For all filters given any non numeric value

**Comment by mesmriti** [comment]
Fixed following issues -
Following issues got fixed-
1. Correct error message to display while generating a report with invalid data
2. Correct error message to displaywhile filtering log with invalid data
3. Fixed user activity log for the audit

**Comment by jay-katta** [comment]
For the above third point, we have an issue already- 
Failing to generate user activity log #464 is
