### ISSUE TITLE
Unable to compile Ginger 

### ISSUE THREAD

**Issue by harche** [kimchi-project/ginger#49]
Hi,

After latest merges in Ginger code, I am not able to do `make`. 

```
echo "Compiling .scss file src/ginger.scss"
Compiling .scss file src/ginger.scss
sassc -s expanded src/ginger.scss ginger.css
echo "Compiling .scss file src/host-admin.scss"
Compiling .scss file src/host-admin.scss
sassc -s expanded src/host-admin.scss host-admin.css
sassc: error: Error: file to import not found or unreadable: ../../../../../../../ui/css/src/modules/wok-variables
       Current dir: /home/harshal/git/ginger/ui/css/src/
        on line 20 of src/host-admin.scss
>> @import "../../../../../../../ui/css/src/modules/wok-variables";
   --------^

make[3]: *** [host-admin.css] Error 1
make[3]: Leaving directory `/home/harshal/git/ginger/ui/css'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/home/harshal/git/ginger/ui/css'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/harshal/git/ginger/ui'
make: *** [all-recursive] Error 1
```

**Comment by danielhb** [comment]
Have you tried rebuilding WoK from scratch (make clean; ./autogen.sh --system; make) ?

I am not seeing this error here in my current working dir. I'll try with a new project clone

**Comment by danielhb** [comment]
Just verified here that even with a new project clone, building everything from scratch, it works.

Check if you have all the README dependencies installed. Perhaps you're missing a package

**Comment by samhenri** [comment]
I believe you have to build Ginger from src/wok/plugins/ginger. From the output log I can see that you're building it from "/home/harshal/git/ginger/".
The module "wok-variables" is an .scss import from Wok and looks for a relative path to "/kimchi/ui/css/src/modules/".
Please pull the latest changes from Wok (Kimchi project) and init Ginger submodule from there ($ git submodule init / git submodule update)

**Comment by danielhb** [comment]
@harche were you able to compile Ginger? Follow these steps and let me know the errors you've got:

```
$ git clone https://github.com/kimchi-project/wok.git
$ cd wok
$ git submodule init
$ git submodule update --remote
$ ./build-all.sh
```

**Comment by danielhb** [comment]
@harche have you been able to compile Ginger? Can we close this issue?

**Comment by harche** [comment]
@danielhb Hi, yes you can close the issue now. Thanks.

**Comment by danielhb** [comment]
@harche thanks! Feel free to reopen this issue or create a new one if the problem persists.
