### ISSUE TITLE
Usage icon is not displayed for File System and Swap Devices.

### ISSUE THREAD

**Issue by atreyeemukhopadhyay** [kimchi-project/ginger#491]
Usage icon is displayed as background image url is not recognized  by browser.

![usage](https://cloud.githubusercontent.com/assets/13199397/20707956/cb0f35da-b653-11e6-82f1-b2e0a326d012.jpg)

**Comment by danielhb** [comment]
Fixed by 2ae952a183ece4c56152734f4547457a4a3e1917
