### ISSUE TITLE
Update existing Ginger and Gingerbase objstores with 'Version' field

### ISSUE THREAD

**Issue by alinefm** [kimchi-project/ginger#51]
Originally created on https://github.com/kimchi-project/kimchi/issues/764
Please, check the discussion there.

After the patch set "Upgrade ObjectStore data to Kimchi-2.0" went upstream, existing Ginger objstore files fails to load with the following error:

[23/Nov/2015:10:45:18] ENGINE Started monitor thread 'Autoreloader'.
[23/Nov/2015:10:45:19] ENGINE Serving on http://127.0.0.1:37848
[23/Nov/2015:10:45:19] ENGINE Bus STARTED
Traceback (most recent call last):
  File "/home/danielhb/kimchi/wok/kimchi/src/wok/asynctask.py", line 65, in _save_helper
    session.store('task', self.id, obj)
  File "/home/danielhb/kimchi/wok/kimchi/src/wok/objectstore.py", line 92, in store
    (ident, obj_type, jsonstr, version))
OperationalError: table objects has no column named version

WOKASYNC0002E: WOKASYNC0002E 

The changes made in Kimchi object store must be done in Ginger and Gingerbase object stores as well.

**Comment by pvital** [comment]
Please, assign this issue to me.

**Comment by pvital** [comment]
Submitted the following patches as part of solution:

* [Wok] Upgrade objectstore schema.
* [Kimchi] Update Kimchi objectstore versioning.
* [Ginger] Issue #51 - Update objectstores with 'Version' field.
* [GingerBase] Issue #51 - Update objectstores with 'Version' field.

Wok and Kimchi patches were submitted to Kimchi devel ML. Ginger and GingerBase to Ginger devel ML.

**Comment by pvital** [comment]
All patches were committed to their repositories. @danielhb you can close this issue now.

Wok - https://github.com/kimchi-project/wok/commit/818d9c59b418718e345cf1978ee9bc7f576a0506
Kimchi - https://github.com/kimchi-project/kimchi/commit/7891f1f89d5da7d1ebc0392642f55d4eaf67155d
Ginger - https://github.com/kimchi-project/ginger/commit/94d048764dd39830a4d7d17bf0ab29780e3b0b7c
GingerBase - https://github.com/kimchi-project/gingerbase/commit/1d9e6401460c37d85e2140763e3cb1689c925658
