### ISSUE TITLE
Network listing section shows line after the content 

### ISSUE THREAD

**Issue by chandrureddy** [kimchi-project/ginger#52]
Network listing section shows line after the content, I guess this line should be under the header section ????

![virtualbox_fedora22_04_12_2015_11_41_01](https://cloud.githubusercontent.com/assets/10830725/11583100/2d8e8d22-9a7c-11e5-985d-f078cb96d6c3.png)

**Comment by chandrureddy** [comment]
Since I am working on creating a separate tab, I might take of the alignment part too.

**Comment by danielhb** [comment]
I appreciate it if you can take a look into it,  @chandrureddy

**Comment by samhenri** [comment]
If by this line you mean the <hr> element, I'm going to send a patch to fix that soon once I finish Kimchi bugs. I have to review some of Ginger UI elements and CSS, specially to implement the CSS Media Queries for small screens.

**Comment by samhenri** [comment]
I believe this issue was already fixed in the latest commits sent to Ginger mailing list. Either way I'll send a SCSS patch today that will probably fix this if you still having the same issue.

**Comment by samhenri** [comment]
Can you check again? I think this is already fixed.

**Comment by danielhb** [comment]
Fixed a while ago.
