### ISSUE TITLE
Configuration Backup UI should show the 'description' field

### ISSUE THREAD

**Issue by danielhb** [kimchi-project/ginger#54]
This is what we have ATM:

![image](https://cloud.githubusercontent.com/assets/866780/11633097/cf551808-9cf0-11e5-87ff-881afb9c40c6.png)

There is no way of telling which backup is a default or custom backup, for example. We need the 'description' field in this table to be able to differentiate between backups. Showing only the filename and timestamp is not enough.

**Comment by samhenri** [comment]
I believe this was fixed with the new-ui. Check the "arrow-down" sign.

**Comment by alinefm** [comment]
I could confirm the description field is displayed in the 'arrow-down' content.
I will close this issue.
