### ISSUE TITLE
Rest API for storage devices fails on Ubuntu 14.04

### ISSUE THREAD

**Issue by harche** [kimchi-project/ginger#56]
Hi,

API for listing storage devices (/plugins/ginger/stgdevs/) fails on ubuntu. It returns empty list even though the disks are present on the system. 

The issue is caused by the command `lsblk`. The implementation of `lsblk` on Ubuntu doesn't have a way to infer `transport` which is found in `lsblk` in other distribution. The fix would be to handle the lack of `transport` in `lsblk` on ubuntu gracefully instead of failing at it completely.

**Comment by danielhb** [comment]
Patch applied to remote master/next branches

Thanks for the fix!
