### ISSUE TITLE
New Ginger UI on Firefox vs chrome

### ISSUE THREAD

**Issue by chandrureddy** [kimchi-project/ginger#58]
I have tried to open the ginger on both firefox and chorome. Couple of observations.
1. Overall the pages are looking better in chrome than on firefox
2. there are some issues like mentioned #52 in firefox but not the case on chrome.
3. Table content or any bold contents shown better in chrome than fire fox.

So My suggestion is people who are experts in correcting these aspects could compare one to one on chrome vs firefox vs internet explorer (now whatever) and if can get all browsers give the same user experience then it would be great !!!

Regards
Chandra

**Comment by samhenri** [comment]
There are some known font rendering issues when using custom webfonts on Firefox vs Chrome. It seems that Firefox is not finding the correct Open Sans font for Medium and Bold font weights and I was able to reproduce this on Fedora 20.
Acessing the same host by Firefox on Windows displayed the correct fonts.
I'll investigate if forcing a "font stack" works, but this affects Wok, Kimchi and Gingerbase as well.
As for other elements, @andreteodoro is already looking into this issue.

**Comment by danielhb** [comment]
I don't see any differences between the user experience on Chrome and Firefox anymore.

I'll close the issue. Feel free to reopen if you still see such differences.
