### ISSUE TITLE
Modal pages and their scope on new UI

### ISSUE THREAD

**Issue by chandrureddy** [kimchi-project/ginger#59]
I have observed the following with the modal pages/pop ups 
1. When you click let us say Administation -> User Management -> Add User
It will open up the modal page nicely for the new user creation
2. Catch is let us say for some reason unfortunately I click the main page out side the modal page, it simply closes the modal page and take you to the main page.

 I would not expect modal page simply vanish unless I completed my work on the modal or I explicitly click cancel or whatever exit button on the modal page. As per my understand Modal page/dialog should not allow you to leave the page unless you say to leave the page.

I am not sure is there any reason doing this but I feel this could be potential issue when I filled most of the data in the modal page but unknowingly clicked on the main page.

**Comment by samhenri** [comment]
This is Bootstrap default behavior. http://getbootstrap.com/javascript/#modals

**Comment by laggarcia** [comment]
@samhenri, is it possible to change the default behavior? I mean, I see this as the default behavior in a mobile environment, but I agree with @chandrureddy that can be annoying in a web interface.

**Comment by samhenri** [comment]
Just add to each ```<div class="modal fade in">``` the attributes ```data-keyboard="false"``` and  ```data-backdrop="static"``` instance. This will prevent closing when clicking in the backdrop or by pressing esc key.

**Comment by danielhb** [comment]
How do we proceed in this case? Do we change the default behavior in all cases or change it just when not opening in a mobile browser?

We need to consider that this default behavior must be changed across all the plug-ins, or at least wok/gingerbase. Otherwise we'll have different behaviors in different tabs.

**Comment by samhenri** [comment]
Well, I'm already updating Kimchi modal windows with the fixed backdrop since I identified some issues with Edit and Add Templates so I believe it is safe to override the default behavior on all screens and plugins. This could also be done by JS on wok.window.js but I believe we should let this up to each developer.

**Comment by danielhb** [comment]
@samhenri I understand your point about letting the developer decide, but in this specific case I am not so sure about it. I would rather have some level of standardization in all the plug-ins than having modal windows that behaves differently depending on the tab/plug-in. 

For such changes I believe the way to go would be to change the base UI classes in WoK and all the plug-ins would inherit them. This would guarantee that all the WoK plug-ins behaves the same way, giving the impression of an unified software.

I would like to ask  @alinefm  and @laggarcia  to weight in here

**Comment by laggarcia** [comment]
I agree with @danielhb in this case. I would rather prefer to see the same behavior for all modal windows throughout the application and its plug-ins.

**Comment by samhenri** [comment]
Just to let you know, yesterday I've sent a patch to Wok that fixes this issue with all wok.window instances. Now in order to close the modal windows, the user has to click either on the X sign (when available) or Cancel button.

**Comment by danielhb** [comment]
@samhenri that's good news. Let us know when it is accepted and then we can close this issue


Thanks

**Comment by danielhb** [comment]
Issue fixed in the following WoK commit:

https://github.com/kimchi-project/wok/commit/8b57e2a416d0e61a5bf1ff2cdc63415ea70000af
