### ISSUE TITLE
plugin ginger not work

### ISSUE THREAD

**Issue by shizhiqin** [kimchi-project/ginger#62]
system：centos7.1 

"Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; rv:11.0) like Gecko"
INFO:cherrypy.access.48227024:192.168.1.20 - - [11/Dec/2015:22:31:20] "GET /css/bootstrap-select.custom.css?cacheBust=1449844142.12 HTTP/1.0" 304 - "https://192.168.1.224:8001/" "Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; rv:11.0) like Gecko"
INFO:cherrypy.access.48227024:192.168.1.20 - - [11/Dec/2015:22:31:20] "GET /libs/es5-shim/es5-shim.min.js?cacheBust=1449844142.98 HTTP/1.0" 304 - "https://192.168.1.224:8001/" "Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; rv:11.0) like Gecko"
INFO:cherrypy.access.48227024:192.168.1.20 - - [11/Dec/2015:22:31:20] "GET /libs/jquery-ui/jquery-ui.min.js?cacheBust=1449844142.78 HTTP/1.0" 304 - "https://192.168.1.224:8001/" "Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; rv:11.0) like Gecko"
INFO:cherrypy.access.48227024:192.168.1.20 - - [11/Dec/2015:22:31:20] "GET /libs/jquery-i18n/jquery.i18n.min.js?cacheBust=1449844143.05 HTTP/1.0" 304 - "https://192.168.1.224:8001/" "Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; rv:11.0) like Gecko"
INFO:cherrypy.access.48227024:192.168.1.20 - - [11/Dec/2015:22:31:20] "GET /libs/bootstrap-select/dist/js/bootstrap-select.min.js?cacheBust=1449844142.9 HTTP/1.0" 304 - "https://192.168.1.224:8001/" "Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; rv:11.0) like Gecko"
INFO:cherrypy.access.48227024:192.168.1.20 - - [11/Dec/2015:22:31:20] "GET /libs/jquery-ui/jquery-ui-i18n.min.js?cacheBust=1449844142.75 HTTP/1.0" 304 - "https://192.168.1.224:8001/" "Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; rv:11.0) like Gecko"
INFO:cherrypy.access.48227024:192.168.1.20 - - [11/Dec/2015:22:31:20] "GET /libs/jquery/jquery.min.js?cacheBust=1449844142.47 HTTP/1.0" 304 - "https://192.168.1.224:8001/" "Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; rv:11.0) like Gecko"
INFO:cherrypy.access.48227024:192.168.1.20 - - [11/Dec/2015:22:31:20] "GET /libs/bootstrap/bootstrap.min.js?cacheBust=1449844142.41 HTTP/1.0" 304 - "https://192.168.1.224:8001/" "Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; rv:11.0) like Gecko"
INFO:cherrypy.access.48227024:192.168.1.20 - - [11/Dec/2015:22:31:20] "GET /base64/jquery.base64.js?cacheBust=1449844141.87 HTTP/1.0" 200 4498 "https://192.168.1.224:8001/" "Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; rv:11.0) like Gecko"
INFO:cherrypy.access.48227024:192.168.1.20 - - [11/Dec/2015:22:31:20] "GET /js/wok.min.js?cacheBust=1449844142.32 HTTP/1.0" 304 - "https://192.168.1.224:8001/" "Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; rv:11.0) like Gecko"
INFO:cherrypy.access.48227024:192.168.1.20 - - [11/Dec/2015:22:31:20] "GET /fonts/OpenSans-LightItalic.ttf HTTP/1.0" 304 - "https://192.168.1.224:8001/" "Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; rv:11.0) like Gecko"
INFO:cherrypy.access.48227024:192.168.1.20 - - [11/Dec/2015:22:31:20] "GET /fonts/OpenSans-Light.ttf HTTP/1.0" 304 - "https://192.168.1.224:8001/" "Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; rv:11.0) like Gecko"
INFO:cherrypy.access.48227024:192.168.1.20 - - [11/Dec/2015:22:31:20] "GET /fonts/OpenSans-Semibold.ttf HTTP/1.0" 304 - "https://192.168.1.224:8001/" "Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; rv:11.0) like Gecko"
INFO:cherrypy.access.48227024:192.168.1.20 - - [11/Dec/2015:22:31:20] "GET /fonts/OpenSans-SemiboldItalic.ttf HTTP/1.0" 304 - "https://192.168.1.224:8001/" "Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; rv:11.0) like Gecko"
INFO:cherrypy.access.48227024:192.168.1.20 - - [11/Dec/2015:22:31:20] "GET /fonts/OpenSans-Regular.ttf HTTP/1.0" 304 - "https://192.168.1.224:8001/" "Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; rv:11.0) like Gecko"
INFO:cherrypy.access.48227024:192.168.1.20 - - [11/Dec/2015:22:31:20] "GET /fonts/OpenSans-Bold.ttf HTTP/1.0" 304 - "https://192.168.1.224:8001/" "Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; rv:11.0) like Gecko"
INFO:cherrypy.access.48227024:192.168.1.20 - - [11/Dec/2015:22:31:20] "GET /fonts/OpenSans-BoldItalic.ttf HTTP/1.0" 304 - "https://192.168.1.224:8001/" "Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; rv:11.0) like Gecko"
INFO:cherrypy.access.48227024:192.168.1.20 - - [11/Dec/2015:22:31:20] "GET /fonts/OpenSans-Italic.ttf HTTP/1.0" 304 - "https://192.168.1.224:8001/" "Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; rv:11.0) like Gecko"
INFO:cherrypy.access.48227024:192.168.1.20 - - [11/Dec/2015:22:31:20] "GET /fonts/OpenSans-ExtraBoldItalic.ttf HTTP/1.0" 304 - "https://192.168.1.224:8001/" "Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; rv:11.0) like Gecko"
INFO:cherrypy.access.48227024:192.168.1.20 - - [11/Dec/2015:22:31:20] "GET /fonts/OpenSans-ExtraBold.ttf HTTP/1.0" 304 - "https://192.168.1.224:8001/" "Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; rv:11.0) like Gecko"
INFO:cherrypy.access.48227024:192.168.1.20 - - [11/Dec/2015:22:31:21] "GET /fonts/fontawesome-webfont.ttf HTTP/1.0" 304 - "https://192.168.1.224:8001/" "Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; rv:11.0) like Gecko"
INFO:cherrypy.access.48227024:192.168.1.20 - - [11/Dec/2015:22:31:21] "GET /i18n.json HTTP/1.0" 200 458 "https://192.168.1.224:8001/" "Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; rv:11.0) like Gecko"
INFO:cherrypy.access.48227024:192.168.1.20 - - [11/Dec/2015:22:31:21] "GET /plugins HTTP/1.0" 200 14 "https://192.168.1.224:8001/" "Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; rv:11.0) like Gecko"
INFO:cherrypy.access.48227024:192.168.1.20 - - [11/Dec/2015:22:31:21] "GET /plugins/ginger/i18n.json HTTP/1.0" 404 513 "https://192.168.1.224:8001/" "Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; rv:11.0) like Gecko"
INFO:cherrypy.access.48227024:192.168.1.20 - - [11/Dec/2015:22:31:21] "GET /plugins/ginger/ui/config/tab-ext.xml HTTP/1.0" 404 850 "https://192.168.1.224:8001/" "Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; rv:11.0) like Gecko"

**Comment by danielhb** [comment]
I'll make tests with a CentOS 7.1 VM when I have the chance.

**Comment by danielhb** [comment]
We'll diagnose and try to solve this issue in issue #86  with the current version.
