### ISSUE TITLE
GET on network interface file, give {} if file not found, error while reading file, file is empty

### ISSUE THREAD

**Issue by archu-s** [kimchi-project/ginger#68]
GET operation on network interface, returns {} in all of the below cases. Does it more sense to return proper reason instead of {}.

1) file not present
2) error while reading file
3) file is empty.

**Comment by danielhb** [comment]
What API are we talking about here? I suppose it is the one that's implemented by cfginterfaces model?

**Comment by archu-s** [comment]
yes cfginterfaces.
