### ISSUE TITLE
Network interface file has value in quotes, then rest API call return the attribute value in quotes inside quotes

### ISSUE THREAD

**Issue by archu-s** [kimchi-project/ginger#70]
Network interface file has value in quotes, then rest API call return the attribute value in quotes inside quotes. For example:

TYPE="Ethernet"
BOOTPROTO="dhcp"
DEFROUTE="yes"
IPV4_FAILURE_FATAL="no"
IPV6INIT="yes"
IPV6_AUTOCONF="yes"
IPV6_DEFROUTE="yes"
IPV6_FAILURE_FATAL="no"
NAME="enp0s3d"
UUID="7241d3b4-2b15-49a8-994e-b788062a9b02"
HWADDR="08:00:27:65:33:7F"
PEERDNS="yes"
PEERROUTES="yes"
IPV6_PEERDNS="yes"
IPV6_PEERROUTES="yes"
DEVICE="enp0s3de"
ONBOOT="no"

GET API call returns:

{
  "IPV4_INFO":{
    "PEERROUTES":"\"yes\"",
    "BOOTPROTO":"\"dhcp\"",
    "DEFROUTE":"\"yes\"",
    "PEERDNS":"\"yes\"",
    "IPV4_FAILURE_FATAL":"\"no\""
  },
  "BASIC_INFO":{
    "UUID":"\"7241d3b4-2b15-49a8-994e-b788062a9b02\"",
    "HWADDR":"\"08:00:27:65:33:7F\"",
    "DEVICE":"\"enp0s3de\"",
    "TYPE":"\"Etherne\"t",
    "ONBOOT":"\"no\"",
    "NAME":"enp0s3d"
  },
  "IPV6_INFO":{
    "IPV6INIT":"\"yes\"",
    "IPV6_PEERDNS":"\"yes\"",
    "IPV6_DEFROUTE":"\"yes\"",
    "IPV6_AUTOCONF":"\"yes\"",
    "IPV6_FAILURE_FATAL":"\"no\"",
    "IPV6_PEERROUTES":"\"yes\""
  }
}

Does it make more sense to remove the redundant double quotes in JSON response?

**Comment by danielhb** [comment]
In my opinion we can remove the extra double quotes surrounding these values in the JSON response. It is awkward indeed.

**Comment by danielhb** [comment]
@chandrureddy  you are directly involved in the new Network UI. Is the UI already parsing and dealing with these quote inside quote values from the backend?

Because if the UI is already dealing with it we'd rather close this bug and forget about it

**Comment by abhiramkulkarni** [comment]
Archana, one doubt here, 

the config files i have noticed are in the format key=value.
Example:
bash-4.3# cat ifcfg-enp0s25
TYPE=Ethernet
DEFROUTE=yes
IPV4_FAILURE_FATAL=no
IPV6INIT=yes
IPV6_AUTOCONF=yes
IPV6_DEFROUTE=yes
IPV6_FAILURE_FATAL=no
NAME=enp0s25
DEVICE=enp0s25
UUID=340503b4-e679-f113-2778-985445badaee
BOOTPROTO=dhcp
HWADDR=00:21:CC:72:D0:2F
PEERDNS=yes
PEERROUTES=yes
IPV6_PEERDNS=yes
IPV6_PEERROUTES=yes
bash-4.3#
These ifcfg files has been generated via Network manager as reference, and values are not present in quote.

Can you share me any document or reference which says values can be given in quotes and these quotes has to be ignored?
If values can be given in quotes, then it calls up for a discussion whether to ignore these quotes?
What if user intention is to have the quote in value?

**Comment by archu-s** [comment]
@abhiramkulkarni ,

The ifcfg files has values in doubt quotes in my virtual box having fedora release 21. The file was generated by system after I installed it on my virtual box.
But it really does not affect my network connectivity if I remove these quotes from the file.

But when I was doing the REST API call of ginger, I notice it as giving me quotes inside quotes. And hence in UI also I was getting value in double quotes.
Ya, we should have a discussion whether to ignore these quotes in API response or not. 
And in my fedora system I can give value in both ways..quotes and without quotes in ifcfg files.

**Comment by abhiramkulkarni** [comment]
To investigate and discuss further!!

**Comment by danielhb** [comment]
In this link

https://docs.fedoraproject.org/en-US/Fedora/23/html/Networking_Guide/sec-Using_the_Command_Line_Interface.html#sec-Configuring_a_Network_Interface_Using_ifcg_Files

We can see that the values in the ifcfg files don't need to be wrapped with double quotes. In Fedora 14 docs there is at least one exception: fields with multiple values 

```
ETHTOOL_OPTS=<options> where <options> are any device-specific options supported by ethtool. For example, if you wanted to force 100Mb, full duplex:

ETHTOOL_OPTS="autoneg off speed 100 duplex full"
```

I don't know if this option ETHTOOL_OPTS is still supported but it would be a case of using double quotes as well.

In my opinion, given that apparently there is no UI consuming this API, we should take the double quotes away from the values of the ifcfg files for better clarity of the API (unless in those cases of multiple values, if we support any).

For Ubuntu and openSUSE I've checked that they either (1) discourage manual configuration via ifcfg files or (2) have CLI tools to do it. This is something that we must take into account. Perhaps we can use other mechanisms for them and leave this cfginterfaces model to support RHEL/Fedora only.

**Comment by abhiramkulkarni** [comment]
Fix is working in latest code.
