### ISSUE TITLE
API endpoint for updating network interface file info has the resource name, does really required to mandate DEVICE to be pass in data, if user is just interested in updating any other optional parameter?

### ISSUE THREAD

**Issue by archu-s** [kimchi-project/ginger#71]
PUT operation on network interface file mandates DEVICE to be passed in data, even if user just want to update any optional parameter. 
As the API endpoint will have the resource name, does it really required to mandate this?

**Comment by abhiramkulkarni** [comment]
Here DEVICE can be removed from data in PUT curl command.

As identifier is already present in curl, that will be the device name.

@mesmriti please work on the issue as discussed.

**Comment by mesmriti** [comment]
I am working on this issue.According to the code changes the DEVICE parameter will not be a mandatory option in the PUT curl command.
