### ISSUE TITLE
Filter loopback(lo) and virtual bridge from network interfaces list 

### ISSUE THREAD

**Issue by jay-katta** [kimchi-project/ginger#74]
Network interfaces list can display host physical NICs and Vlan/Bond (Bridge/OVS in near future) and filter out loopback and Virtual bridge.

Current list looks like below-
curl -k -u user:password -H "Content-Type: application/json" -H "Accept: application/json" 'https://127.0.0.1:8001/plugins/ginger/network/interfaces'
[
  {
    "status":"active",
    "name":"enccw0.0.3b00",
    "editable":true,
    "ipaddr":"9.x.x.x",
    "netmask":"255.255.254.0",
    "type":"nic"
  },
  {
    "status":"active",
    "name":"lo",
    "editable":true,
    "ipaddr":"127.0.0.1",
    "netmask":"255.0.0.0",
    "type":"unknown"
  },
  {
    "status":"inactive",
    "name":"virbr0",
    "editable":false,
    "ipaddr":"192.168.122.1",
    "netmask":"255.255.255.0",
    "type":"bridge"
  },
  {
    "status":"inactive",
    "name":"virbr0-nic",
    "editable":false,
    "ipaddr":"",
    "netmask":"",
    "type":"unknown"
  }
]

Can have like this -
curl -k -u user:password -H "Content-Type: application/json" -H "Accept: application/json" 'https://127.0.0.1:8001/plugins/ginger/network/interfaces'
[
  {
    "status":"active",
    "name":"enccw0.0.3b00",
    "editable":true,
    "ipaddr":"9.x.x.x",
    "netmask":"255.255.254.0",
    "type":"nic"
  },
]

**Comment by danielhb** [comment]
This is fixed upstream. This is the output of curl:

[danielhb@arthas ginger]$ curl -k -u danielhb -H "Content-Type: application/json" -H "Accept: application/json" 'https://127.0.0.1:8001/plugins/ginger/network/interfaces'Enter host password for user 'danielhb':
[
  {
    "status":"up",
    "nic_type":"N/A",
    "netmask":"",
    "macaddr":"68:f7:28:26:ab:cd",
    "rdma_enabled":false,
    "device":"enp0s25.987",
    "ipaddr":"",
    "type":"vlan",
    "module":"unknown"
  },
  {
    "status":"up",
    "nic_type":"physical",
    "netmask":"255.255.255.0",
    "macaddr":"68:f7:28:26:ab:cd",
    "rdma_enabled":false,
    "device":"enp0s25",
    "ipaddr":"9.18.239.78",
    "type":"nic",
    "module":"e1000e"
  }
]

lo and virtual bridges aren't being shown anymore.
