### ISSUE TITLE
cfginterface: In ipv4info,PUT API call does not give option to remove ipv4 address

### ISSUE THREAD

**Issue by archu-s** [kimchi-project/ginger#79]
cfginterface PUT operation with IPV4_INFO, does edit to the interfaces passed.For example
If ifcfg file has 3 ipv4address , and in PUT if two ipv4 addresses is passed, code just update first two info in ifcfg file as per sequence. And if four is passed, code update all three and add fourth one as per sequence. 
There is no option to delete existing IPv4 Addresses. say if we have 3 ipv4 addresses in ifcfg file, there is no option to delete the any one of it.

**Comment by abhiramkulkarni** [comment]
With the current code implementation, UI will be sending all the input required.
In UI you will be able to add/delete the ipv4s, hence UI point of view this is not a required feature.

With curl command, as well it is required user to know what he is doing, hence probably he should do get on interface. And pass the ips that are required and to be present in ifcfg file. This will help maintain consistency with UI.

For now this will be an invalid feature.

**Comment by abhiramkulkarni** [comment]
With the current design we have there is no scope of giving partial update of ip addresses.

This will be an invalid feature.
