### ISSUE TITLE
Update README to include Build Instructions (get WoK and Gingerbase code)

### ISSUE THREAD

**Issue by lcorreia** [kimchi-project/ginger#80]
Distro: Ubuntu 15.10 x86_64
Tried to clone ginger separately from wok and could not build it. The same problem occurs trying to build ginger in wok tree before building wok itself.

Compiling .scss file src/ginger.scss
sassc -s expanded src/ginger.scss ginger.css
sassc: error: Error: File to import not found or unreadable: ../../../../../../../ui/css/src/modules/wok-variables
       Parent style sheet: /home/dev/ginger/ui/css/src/ginger.scss
        on line 20 of src/ginger.scss
>> @import "../../../../../../../ui/css/src/modules/wok-variables";
   ^

Makefile:699: recipe for target 'ginger.css' failed
make[3]: *** [ginger.css] Error 1
make[3]: Leaving directory '/home/dev/ginger/ui/css'
Makefile:428: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/home/dev/ginger/ui/css'
Makefile:373: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/dev/ginger/ui'
Makefile:547: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

**Comment by danielhb** [comment]
I've given some thought about it and perhaps this will not be possible due to how the new UI works. The UI of the plug-ins uses WoK basic UI classes and declarations, like you reported in the issue. In my opinion this can't be avoided and we'll have to deal with it. 

I'll ask the input of @samhenri in this matter.

**Comment by danielhb** [comment]
As per https://github.com/kimchi-project/gingerbase/issues/17, we would better update the README to say that we'll need WoK and Gingerbase source to build Ginger than to try to run Ginger standalone and being unable to run the unit tests, for example.

I'll update the bug title to reflect this new goal.
