### ISSUE TITLE
Ginger make is not cleaning existing ginger.css file

### ISSUE THREAD

**Issue by atreyeemukhopadhyay** [kimchi-project/ginger#89]
With the latest change , ginger.css file is not getting cleaned. It's retaining the file generated earlier. Current changes in scss files are not reflecting.

**Comment by danielhb** [comment]
It's not a bug. It is the intended way to work with the UI, although it is not well documented I admit.

The idea is to not require the UI packages (libsass, cython) to build the source of the plug-ins. To make that happen, @alinefm  removed the .css files from .gitignore. When changing the scss source you need to re-generate the plug-in.css file by doing ``` sudo make -C ui/css css ``` .

The css file will be updated and then you commit the changes in the patch as well. Let me know if you have any doubts about the process.
