### ISSUE TITLE
develop the initial UI of the sysmodules feature

### ISSUE THREAD

**Issue by danielhb** [kimchi-project/ginger#92]
The initial UI for this feature will cover only the simple cases described in #91 :

- listing all loaded kernel modules
- fetching info of one specific kernel module 
- loading a kernel module
- unloading a kernel module

I believe that any table-like view is acceptable for the listing. The fields we would be interested into would be the module name, size, used_by, depends_on, version.

The load module interface will need to have 2 fiels for this initial UI: one is the module name, other is a blank fields to pass parameters for the loading process.

Unloading a module can be a regular delete element UI with a confirmation box "Are you sure you want to unload module X" before executing the action.

I'll keep posting here my insights about the UI while I'm developing the backend.

**Comment by danielhb** [comment]
I have more insights about the load module interface.

As I've said, 2 fields: module name and parameters. What I would to see also is an extra button, an exclamation mark, right after the parameters text field. Pressing this button will show all the options available for the module in a pop-up window. This info is retrieved from the lookup of the module in the API. 

Of course that there is no way to predict which module the user will want to load, so this API call will be made when the dialog is opened and the user already inputted the module name. Another alternative would be to have a button called 'load module info' right beside the module name field to let the UI know when to fetch the information. Otherwise there's the risk of spamming the user with errors when he's typing the module name, for example. I would like the input of @laggarcia and @samhenri  here with this 'load module info' button. 

This will be the basic UI for all modules and the information is already available. I'll talk more about SRIOV support in another issue, but this work will need to be done anyway.

**Comment by laggarcia** [comment]
Can't we try to validate the module name as the user types it?

If this is too slow, we shall ask the module name and have a button to load it. Then we check if the module exists or not. If not, we show an error.

BTW, it would be good if the back-end has some intelligence here. I understand that we cannot predict which module the user will try to load. But if the user unloads a module, we should not remove it from the list in the back-end, so that the user can easily bring it up back again if desired without having to type the module name.

**Comment by danielhb** [comment]
The validation of the module name without the 'load' button would be made by watching the interval of the key strokes. If a certain amount of time (1 second for example) passes between strokes, the UI can fire the API to fetch the information. 

What we can do to avoid spamming errors why the user type is to simply not show these 'validation' errors in this field. If the user does not see any change in the UI with any additional info popping he/she can deduce that the module name is wrong. Trying to press 'load' in this scenario would result in an UI error, as expected.

"We can have a 'history' capability in the backend to remember the last unloaded modules to prevent the user from typing them again."

We can have a 'history' capability in the backend to remember the last unloaded modules to prevent the user from typing them again. But, as any backend capability, it will be fetched by an extra AJAX call. 

One way to easily implement it is doing in the frontend, using the history of the browser itself. I believe there are some Kimchi features (NFS pool comes to mind) that have this history capability.

**Comment by samhenri** [comment]
NFS Pool and ICSSI history are all fetched by kimchi.getStorageServers(), not the browser history. I believe it is currently impossible to get browser autofill values and style them with the wok.combobox() widget. BTW, I was planning to change wok.combobox to typeahead.js: https://twitter.github.io/typeahead.js/examples/

**Comment by samhenri** [comment]
I've created this quick wireframe for the main panel. I've seen the patch in the ML but wasn't able to apply locally yet. For now I just need to confirm if the Details with expandable panel is ok for the "fetching info of one specific kernel module" requirement. It should act like the Backup History section in Ginger or Storage Volume in Kimchi.

![sr-iov-table](https://cloud.githubusercontent.com/assets/326107/12231321/b7147f6e-b83d-11e5-8a08-d16eecf54c65.png)

**Comment by danielhb** [comment]
I am OK with this style of 'Details'. Just a few pointers:

- 'size' and 'used by' isn't available in this API yet due to a WoK limitation

- the details will be quite dynamic. Not all modules has authors, description, aliases, parameters ... the UI will need to be highly adaptable. The fields that I've noticed that are always presented are 'filename', 'license', 'intree', 'depends', 'version' and 'srcversion'.

**Comment by samhenri** [comment]
I guess then the details panel should be a list instead of a table or we'll have to use CSS3 flexbox to arrange the items like a table. I think Sensor Monitor in Ginger follows the same pattern here. The only problem with Flexbox is that it is not supported by IE9 and it has some known issues with IE10 and 11.

**Comment by samhenri** [comment]
The Load Modules dialog: http://jsfiddle.net/samhenri/9o50kq4a/
For this fiddle I used the Typeahead.js plugin but I think the proper widget for this should be a "Select" component that the user can type and filter the available modules. We can still disable the "Save" button if a invalid module is typed but the other solutions available are:
Select2 - https://select2.github.io/examples.html
Chosen - http://julesjanssen.github.io/chosen/
Either one we would have to customize the CSS to match the new-ui.

**Comment by danielhb** [comment]
"We can still disable the "Save" button if a invalid module is typed"

Agreed

**Comment by danielhb** [comment]
Please consider also that the latest version of the API was posted at https://github.com/kimchi-project/ginger/issues/137

**Comment by samhenri** [comment]
Thanks! I think CSS3 flexbox can handle this even if a module doesn't have all properties. I'm probably gonna take this task but I already have some Kimchi backlog to do that will take the whole week

**Comment by samhenri** [comment]
I'm almost finished with the Details area and It will be very similar with Configuration Backup except that we won't show the empty fields. Just need to confirm which fields are going to appear and priority / order.
For now It is:

       * filename
       * description
       * author
       * license
       * signer
       * sig_key
       * sig_hashalgo
       * intree
       * vermagic

And if available, the aliases and parameters appear in another "table".
I'm using Flexbox to make sure that all columns have the same height: http://osvaldas.info/examples/flexbox-based-responsive-equal-height-blocks-with-javascript-fallback/

**Comment by danielhb** [comment]
sig_key, sig_hashalgo and signer can be moved to the bottom of the priority. The rest looks good to me.

**Comment by samhenri** [comment]
What does sig_key, sig_hashalgo, intree and vermagic stands for? I'm putting the details table headers in the i18n file for readability and localization purposes but I could just get the json object keys and change the first letter to uppercase with CSS.

**Comment by danielhb** [comment]
Just to make it clear: the sysmodules backend, today, does **not** return the unloaded modules. We can use typeahead in the UI to allow the user to quickly reload a module, but for any module that isn't loaded (and as such will not be returned by the API) the UI will need to do a lookup() to see if the module name is valid.

**Comment by sstoppler** [comment]
Patch applied upstream:  
https://github.com/kimchi-project/ginger/commit/9588c87eb81f5fd2df448c90fcc83f799ea2bb7c
