### ISSUE TITLE
GET /plugins/ginger/stgdevs fails with 500

### ISSUE THREAD

**Issue by sureshab** [kimchi-project/ginger#98]
[root@zfwcec103 gingers390x]# curl -k -u root -H "Content-Type: application/json" -H "Accept: application/json" -X GET 'https://127.0.0.1:8001/plugins/ginger/stgdevs'
Enter host password for user 'root':
{
  "reason":"GINSD00005E: Error getting list of storage devices, size",
  "code":"500 Internal Server Error"
}  

log:

Error getting list of storage devices
Error getting list of storage devices
GINSD00005E: Error getting list of storage devices, size
GINSD00005E: Error getting list of storage devices, size

**Comment by harche** [comment]
I will be working on this issue

**Comment by danielhb** [comment]
Please verify if the fix works

Thanks

**Comment by harche** [comment]
@danielhb The fix works fine.
