### ISSUE TITLE
cfginterface listing failed with the following error on Fedora 22

### ISSUE THREAD

**Issue by chandrureddy** [kimchi-project/ginger#99]
[root@localhost dist]# curl -k -u root:passw0rd -H "Content-Type: application/json" -H "Accept: application/json" -X GET 'https://127.0.0.1:8001/plugins/ginger/network/cfginterfaces'
{
  "reason":"GINNET0057E: Persistent file is not available for an interface, 'enp0s8'",
  "code":"500 Internal Server Error"
}                                                                                                                                                                 

Interfaces available on my machine are:
[root@localhost dist]# ifconfig
enp0s3: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.0.2.15  netmask 255.255.255.0  broadcast 10.0.2.255
        inet6 fe80::a00:27ff:febd:ce67  prefixlen 64  scopeid 0x20<link>
        ether 08:00:27:bd:ce:67  txqueuelen 1000  (Ethernet)
        RX packets 155766  bytes 180670380 (172.3 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 60144  bytes 4249141 (4.0 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

enp0s8: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        ether 08:00:27:5e:64:dc  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

enp0s9: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        ether 08:00:27:29:58:09  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 0  (Local Loopback)
        RX packets 24515  bytes 19539741 (18.6 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 24515  bytes 19539741 (18.6 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

virbr0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet 192.168.122.1  netmask 255.255.255.0  broadcast 192.168.122.255
        ether 52:54:00:6b:d0:5b  txqueuelen 0  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

[root@localhost network-scripts]# ls
ifcfg-enp0s3             ifdown       ifdown-ipv6  ifdown-routes    ifdown-tunnel  ifup-eth   ifup-plip   ifup-routes    ifup-tunnel        network-functions-ipv6
ifcfg-lo                 ifdown-bnep  ifdown-isdn  ifdown-sit       ifup           ifup-ippp  ifup-plusb  ifup-sit       ifup-wireless
ifcfg-VLAN_connection_1  ifdown-eth   ifdown-post  ifdown-Team      ifup-aliases   ifup-ipv6  ifup-post   ifup-Team      init.ipv6-global
ifcfg-VLAN_connection_2  ifdown-ippp  ifdown-ppp   ifdown-TeamPort  ifup-bnep      ifup-isdn  ifup-ppp    ifup-TeamPort  network-functions

At least I would expect GET of cfginterfaces should return me only that interfaces which have the cfg files instead of failing the whole GET operation.

Otherwise there will have compatible issues with the existing machine which has mixed type of interfaces ie interfaces with cfg files and interfaces without cfg files.

**Comment by abhiramkulkarni** [comment]
I am working on this patch.

This issue is related to github #68 and #77

getList in cfginterfaces will give all the interfaces that are active.
Fix here done is to remove the interface which does not have ifcfg file, as cfginterface is currently dealing with interfaces that are having ifcfg files. Will be sending patch with the fix.

We have to see/discuss in mailing list for interfaces which tend to not have ifcfg files for any valid reason.

**Comment by danielhb** [comment]
Fix is available upstream. Please verify if the issue still occurs

**Comment by chandrureddy** [comment]
Fix is working as expected. Please close the ticket !!!
